import { db } from '@sim/db'
import { workspaceFiles } from '@sim/db/schema'
import { createLogger } from '@sim/logger'
import { toError } from '@sim/utils/errors'
import { and, asc, desc, eq, isNull, or } from 'drizzle-orm'
import { type FileReadResult, readFileRecord } from '@/lib/copilot/vfs/file-reader'
import {
  type GrepCountEntry,
  type GrepMatch,
  type GrepOptions,
  grepReadResult,
  WorkspaceFileGrepError,
} from '@/lib/copilot/vfs/operations'
import { decodeVfsSegment, encodeVfsSegment } from '@/lib/copilot/vfs/path-utils'
import { getServePathPrefix } from '@/lib/uploads'
import type { WorkspaceFileRecord } from '@/lib/uploads/contexts/workspace/workspace-file-manager'

const logger = createLogger('OutputFileReader')

/**
 * Chat-scoped agent outputs (`context='output'`) are the write side's twin of chat
 * uploads (`context='mothership'`): same `workspace_files` table and workspace bucket,
 * but generated by the AGENT for one-off files instead of uploaded by the user. This
 * module is the read side, mirroring upload-file-reader.ts for the `outputs/` namespace.
 */

/**
 * Canonical comparison key for an output's VFS name. Accepts both the raw display
 * name and a percent-encoded segment so either spelling resolves the same row.
 */
function canonicalOutputKey(name: string): string {
  let decoded = name
  try {
    decoded = decodeVfsSegment(name)
  } catch {
    decoded = name
  }
  try {
    return encodeVfsSegment(decoded)
  } catch {
    return name.trim()
  }
}

/** VFS-visible name. Coalesces to originalName for safety, though outputs always set displayName. */
function vfsName(row: typeof workspaceFiles.$inferSelect): string {
  return row.displayName ?? row.originalName
}

function toWorkspaceFileRecord(row: typeof workspaceFiles.$inferSelect): WorkspaceFileRecord {
  const pathPrefix = getServePathPrefix()
  return {
    id: row.id,
    workspaceId: row.workspaceId || '',
    name: vfsName(row),
    key: row.key,
    path: `${pathPrefix}${encodeURIComponent(row.key)}?context=output`,
    size: row.size,
    type: row.contentType,
    uploadedBy: row.userId,
    deletedAt: row.deletedAt,
    uploadedAt: row.uploadedAt,
    updatedAt: row.updatedAt,
    storageContext: 'output',
  }
}

/**
 * Resolve a chat-scoped output row by VFS name. Prefers an exact DB match; falls back
 * to a normalized scan (encoded vs decoded names). On ambiguity returns the most recent.
 */
export async function findChatOutputRowByChatAndName(
  chatId: string,
  fileName: string
): Promise<typeof workspaceFiles.$inferSelect | null> {
  const exactRows = await db
    .select()
    .from(workspaceFiles)
    .where(
      and(
        eq(workspaceFiles.chatId, chatId),
        eq(workspaceFiles.context, 'output'),
        or(
          eq(workspaceFiles.displayName, fileName),
          and(isNull(workspaceFiles.displayName), eq(workspaceFiles.originalName, fileName))
        ),
        isNull(workspaceFiles.deletedAt)
      )
    )
    .orderBy(desc(workspaceFiles.uploadedAt), desc(workspaceFiles.id))
    .limit(1)

  if (exactRows[0]) {
    return exactRows[0]
  }

  const allRows = await db
    .select()
    .from(workspaceFiles)
    .where(
      and(
        eq(workspaceFiles.chatId, chatId),
        eq(workspaceFiles.context, 'output'),
        isNull(workspaceFiles.deletedAt)
      )
    )
    .orderBy(desc(workspaceFiles.uploadedAt), desc(workspaceFiles.id))

  const segmentKey = canonicalOutputKey(fileName)
  return allRows.find((r) => canonicalOutputKey(vfsName(r)) === segmentKey) ?? null
}

/**
 * List all chat-scoped outputs for a given chat in creation order.
 */
export async function listChatOutputs(chatId: string): Promise<WorkspaceFileRecord[]> {
  try {
    const rows = await db
      .select()
      .from(workspaceFiles)
      .where(
        and(
          eq(workspaceFiles.chatId, chatId),
          eq(workspaceFiles.context, 'output'),
          isNull(workspaceFiles.deletedAt)
        )
      )
      .orderBy(asc(workspaceFiles.uploadedAt), asc(workspaceFiles.id))

    return rows.map(toWorkspaceFileRecord)
  } catch (err) {
    logger.warn('Failed to list chat outputs', {
      chatId,
      error: toError(err).message,
    })
    return []
  }
}

/**
 * Read a specific output file by display name within a chat session.
 */
export async function readChatOutput(
  filename: string,
  chatId: string
): Promise<FileReadResult | null> {
  try {
    const row = await findChatOutputRowByChatAndName(chatId, filename)
    if (!row) return null
    return readFileRecord(toWorkspaceFileRecord(row))
  } catch (err) {
    logger.warn('Failed to read chat output', {
      filename,
      chatId,
      error: toError(err).message,
    })
    return null
  }
}

/**
 * Grep the content of a single chat output (`outputs/<name>`), mirroring
 * {@link grepChatUpload}. Resolves the output by name, reads its text per file type,
 * and greps it. Throws {@link WorkspaceFileGrepError} when the output is missing or
 * has no searchable text so the caller surfaces the message verbatim.
 */
export async function grepChatOutput(
  filename: string,
  chatId: string,
  pattern: string,
  options?: GrepOptions
): Promise<GrepMatch[] | string[] | GrepCountEntry[]> {
  const row = await findChatOutputRowByChatAndName(chatId, filename)
  if (!row) {
    throw new WorkspaceFileGrepError(
      `Output not found: "${filename}". Use glob("outputs/*") to list available outputs.`
    )
  }
  const record = toWorkspaceFileRecord(row)
  const result = await readFileRecord(record)
  if (!result) {
    throw new WorkspaceFileGrepError(`Output content not found for "${filename}".`)
  }
  const outputsPath = `outputs/${canonicalOutputKey(record.name)}`
  return grepReadResult(outputsPath, result, pattern, outputsPath, options)
}
