export const OUTBOX_PROCESSOR_MAX_RUNTIME_MS = 760_000
export const OUTBOX_PROCESSOR_RECOVERY_CUTOFF_MS = 770_000
export const OUTBOX_PROCESSOR_MAX_DURATION_SECONDS = 900
export const OUTBOX_PROCESSOR_INTERVAL_MS = 60_000
