/**
 * Generates `apps/sim/blocks/manifest-data.ts` — the registry-free aggregation
 * index over the per-block `<name>.display.ts` files (the source of truth). Run
 * after adding/renaming a block: `bun run blocks:manifest-data`.
 * CI re-runs it and fails if `git diff` is non-empty.
 *
 * `BLOCK_DISPLAY` (light presentation slice), `TOOL_TO_BLOCK` (tool id → block),
 * and `BLOCK_CATALOG` (the `{Service}BlockMeta` catalog data) are all aggregated
 * from the `.display.ts` files — none of the heavy block configs are imported.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { getAllBlockTypes, getBlock } from '@/blocks/registry'

const APP = process.cwd()
const BLOCK_DIR = path.join(APP, 'blocks/blocks')
const OUT = path.join(APP, 'blocks/manifest-data.ts')

interface DisplayEntry {
  constName: string
  type: string
  base: string
}

const entries: DisplayEntry[] = []
const metaRaw: { constName: string; base: string }[] = []
for (const file of readdirSync(BLOCK_DIR).filter((f) => f.endsWith('.display.ts'))) {
  const base = file.replace(/\.display\.ts$/, '')
  const src = readFileSync(path.join(BLOCK_DIR, file), 'utf8')
  const re = /export const (\w+) = \{([\s\S]*?)\n\} satisfies BlockDisplay/g
  let m: RegExpExecArray | null
  while ((m = re.exec(src))) {
    const constName = m[1]
    const typeMatch = m[2].match(/^\s*type:\s*'([^']+)'/m)
    if (!typeMatch) throw new Error(`No type field in ${file} const ${constName}`)
    entries.push({ constName, type: typeMatch[1], base })
  }
  for (const mm of src.matchAll(/export const (\w+BlockMeta)\b/g)) {
    metaRaw.push({ constName: mm[1], base })
  }
}
entries.sort((a, b) => a.type.localeCompare(b.type))

// Each `<X>BlockMeta` belongs to its sibling `<X>BlockDisplay`; key the catalog by that display's type.
const displayByConst = new Map(entries.map((e) => [e.constName, e]))
const metaEntries = metaRaw
  .map((mr) => {
    const displayConst = mr.constName.replace(/Meta$/, 'Display')
    const e = displayByConst.get(displayConst)
    if (!e)
      throw new Error(
        `Meta ${mr.constName} in ${mr.base}.display.ts has no sibling display ${displayConst}`
      )
    return { constName: mr.constName, base: mr.base, key: e.type }
  })
  .sort((a, b) => a.key.localeCompare(b.key))

// TOOL_TO_BLOCK from the registry (offline; the generated map is plain data)
const toolToBlock: Record<string, string> = {}
for (const type of getAllBlockTypes()) {
  const cfg = getBlock(type)
  for (const tool of cfg?.tools?.access ?? []) toolToBlock[tool] = type
}

// One import per base, combining its display + meta consts.
const importsByBase = new Map<string, Set<string>>()
for (const e of [...entries, ...metaEntries]) {
  if (!importsByBase.has(e.base)) importsByBase.set(e.base, new Set())
  importsByBase.get(e.base)!.add(e.constName)
}
const imports = [...importsByBase]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(
    ([base, names]) =>
      `import { ${[...names].sort().join(', ')} } from '@/blocks/blocks/${base}.display'`
  )
  .join('\n')

const displayMap = entries.map((e) => `  ${JSON.stringify(e.type)}: ${e.constName},`).join('\n')
const toolMap = Object.keys(toolToBlock)
  .sort()
  .map((t) => `  ${JSON.stringify(t)}: ${JSON.stringify(toolToBlock[t])},`)
  .join('\n')
const catalogMap = metaEntries.map((e) => `  ${JSON.stringify(e.key)}: ${e.constName},`).join('\n')

const body = `// @generated by scripts/generate-block-manifest-data.ts — do not edit by hand.
// Source of truth is each blocks/blocks/<name>.display.ts. Run \`bun run blocks:manifest-data\`.
${imports}
import type { BlockDisplay } from '@/blocks/manifest'
import type { BlockMeta } from '@/blocks/types'

/** Light display slice for every registered block, keyed by registry type. */
export const BLOCK_DISPLAY: Record<string, BlockDisplay> = {
${displayMap}
}

/** Tool id → owning block type, for tool-name → icon/color resolution. */
export const TOOL_TO_BLOCK: Record<string, string> = {
${toolMap}
}

/** Catalog meta (tags/templates/skills) keyed by base block type. */
export const BLOCK_CATALOG: Record<string, BlockMeta> = {
${catalogMap}
}
`

writeFileSync(OUT, body)
console.log(
  `Wrote blocks/manifest-data.ts — ${entries.length} display, ${metaEntries.length} catalog, ${Object.keys(toolToBlock).length} tool mappings.`
)
