/**
 * Mapping from our emcn icon export name -> Hugeicons (free, stroke-rounded) export name.
 * `null` = keep our existing custom glyph (brand/mascot/bespoke animated), do not vendor.
 * Keys mirror the previous map so already-migrated consumers stay valid.
 */
export const HUGEICONS_MAP: Record<string, string | null> = {
  // Arrows & chevrons
  ArrowDown: 'ArrowDown01Icon',
  ArrowLeft: 'ArrowLeft01Icon',
  ArrowRight: 'ArrowRight01Icon',
  ArrowUp: 'ArrowUp01Icon',
  ArrowUpDown: 'ArrowUpDownIcon',
  ArrowLeftRight: 'ArrowLeftRightIcon',
  ArrowUpLeft: 'ArrowUpLeft01Icon',
  ArrowRight2: 'ArrowRight02Icon',
  ArrowUp2: 'ArrowUp02Icon',
  ChevronDown: 'ChevronDownIcon',
  ChevronUp: 'ChevronUpIcon',
  ChevronLeft: 'ChevronLeftIcon',
  ChevronRight: 'ChevronRightIcon',
  ChevronsUpDown: 'UnfoldMoreIcon',
  ChevronsDownUp: 'ChevronsDownUpIcon',
  RotateCcw: 'RotateLeft01Icon',
  RefreshCw: null,
  Undo: 'ArrowTurnBackwardIcon',
  Redo: 'ArrowTurnForwardIcon',
  Shuffle: 'ShuffleIcon',
  Repeat: 'RepeatIcon',
  Split: 'SplitIcon',
  SendToBack: 'LayerSendToBackIcon',

  // Actions & controls
  Search: 'Search01Icon',
  Plus: 'Add01Icon',
  Minus: 'MinusSignIcon',
  X: 'Cancel01Icon',
  Check: 'Tick02Icon',
  Pencil: 'PencilEdit01Icon',
  Trash: 'Delete02Icon',
  Trash2: 'Delete02Icon',
  Settings: 'Settings01Icon',
  Settings2: 'Settings02Icon',
  MoreHorizontal: 'MoreHorizontalIcon',
  MoreVertical: 'MoreVerticalIcon',
  Send: 'Navigation03Icon',
  Download: null,
  Upload: 'Upload01Icon',
  Duplicate: 'Copy01Icon',
  Clipboard: 'ClipboardIcon',
  ClipboardList: 'ClipboardListIcon',
  Scissors: 'Scissor01Icon',
  Scan: 'ScanIcon',
  SelectAll: 'AlignSelectionIcon',
  Expand: 'ArrowExpand01Icon',
  Cursor: 'Cursor01Icon',
  Hammer: 'HammerIcon',
  Wrench: 'Wrench01Icon',
  Wand2: 'MagicWand01Icon',
  Share2: 'Share08Icon',
  ExternalLink: 'LinkSquare02Icon',
  SquareArrowUpRight: 'ArrowUpRight01Icon',
  Link: 'Link01Icon',

  // Files, folders, data
  File: 'File01Icon',
  FileText: 'File02Icon',
  FileX: 'FileRemoveIcon',
  Files: 'Files01Icon',
  Folder: 'Folder01Icon',
  FolderOpen: 'FolderOpenIcon',
  FolderPlus: 'FolderAddIcon',
  FolderInput: 'FolderUploadIcon',
  FolderCode: 'FolderCodeIcon',
  Table: 'TableIcon',
  TableX: 'Table01Icon',
  Database: 'DatabaseIcon',
  DatabaseX: 'Database01Icon',
  Library: 'Bookshelf01Icon',
  LibraryBig: 'Bookshelf01Icon',
  Columns2: 'LayoutTwoColumnIcon',
  Columns3: 'LayoutThreeColumnIcon',
  Rows3: 'LayoutThreeRowIcon',
  Layout: null,
  PanelLeft: 'PanelLeftIcon',
  PanelRight: 'PanelRightIcon',
  Logs: 'ThirdBracketSquareIcon',
  Card: 'Cards01Icon',
  Image: 'Image01Icon',
  ImageUp: 'Image01Icon',
  Paperclip: 'Attachment01Icon',
  Filter: 'FilterIcon',
  ListFilter: 'FilterHorizontalIcon',

  // Status & primitives
  Eye: 'ViewIcon',
  EyeOff: 'ViewOffSlashIcon',
  Lock: 'LockIcon',
  Unlock: 'SquareUnlock02Icon',
  Key: 'Key01Icon',
  KeyRound: 'Key01Icon',
  Info: 'InformationCircleIcon',
  HelpCircle: 'HelpCircleIcon',
  Square: 'Square01Icon',
  Circle: 'CircleIcon',
  CircleOff: 'UnavailableIcon',
  Ban: 'UnavailableIcon',
  Network: 'GlobalIcon',
  CircleCheck: 'CheckmarkCircle01Icon',
  CircleAlert: 'AlertCircleIcon',
  XCircle: 'CancelCircleIcon',
  TriangleAlert: 'Alert02Icon',
  ShieldCheck: 'Shield01Icon',
  Asterisk: 'AsteriskIcon',
  Slash: 'MinusSignIcon',
  Calendar: 'Calendar01Icon',
  CalendarClock: 'CalendarClockIcon',
  Clock: 'Clock01Icon',
  Loader: null,
  Bell: 'Notification03Icon',
  Pin: 'PinIcon',
  PinOff: 'PinOffIcon',
  TagIcon: 'Tag01Icon',
  Credit: 'CreditCardIcon',
  Bug: 'Bug01Icon',
  History: 'TimeQuarterPassIcon',
  Hash: 'HashtagIcon',

  // Media / comms
  PlayOutline: 'PlayIcon',
  Play: 'PlayIcon',
  Pause: 'PauseIcon',
  PauseCircle: 'PauseCircleIcon',
  Mic: 'Mic01Icon',
  MicOff: 'MicOff01Icon',
  Camera: 'Camera01Icon',
  Music: 'MusicNote01Icon',
  Phone: 'SmartPhone01Icon',
  Mail: 'Mail01Icon',
  MessageCircle: 'BubbleChatIcon',
  BubbleChatDelay: 'BubbleChatDelayIcon',
  BubbleChatSpark: 'BubbleChatSparkIcon',
  Bell2: 'Notification03Icon',

  // People
  User: 'UserIcon',
  Users: 'UserMultipleIcon',
  UserPlus: 'UserAdd01Icon',
  ManageWorkspace: 'UserGroupIcon',

  // Objects / domain
  Home: 'Home01Icon',
  Rocket: 'Rocket01Icon',
  Server: 'ServerStack01Icon',
  Terminal: 'ComputerTerminal01Icon',
  TerminalWindow: 'ComputerTerminal01Icon',
  Palette: 'PaintBoardIcon',
  Globe: 'GlobalIcon',
  Compass: 'Compass01Icon',
  Building2: 'Building06Icon',
  GraduationCap: 'Mortarboard02Icon',
  Sparkles: 'SparklesIcon',
  Bot: 'BotIcon',
  Webhook: 'WebhookIcon',
  Workflow: 'WorkflowSquare08Icon',
  WorkflowX: 'WorkflowSquare01Icon',
  Connections: 'ConnectIcon',
  Integration: 'Plug02Icon',
  GitBranch: 'GitBranchIcon',
  Rss: 'RssIcon',
  FormInput: 'CursorTextIcon',
  Moon: 'Moon02Icon',
  Sun: 'Sun03Icon',
  Task: 'CheckmarkSquare01Icon',
  LogIn: 'Login03Icon',
  LogOut: 'Logout03Icon',
  Fingerprint: 'FingerPrintIcon',
  Wrap: 'TextWrapIcon',
  NoWrap: 'ArrowRight01Icon',
  ZoomIn: 'ZoomInAreaIcon',
  ZoomOut: 'ZoomOutAreaIcon',
  ThumbsUp: 'ThumbsUpIcon',
  ThumbsDown: 'ThumbsDownIcon',
  Hand: 'Hold01Icon',
  BookOpen: 'BookOpen01Icon',

  // Type markers
  TypeText: 'TextFontIcon',
  TypeNumber: 'TextNumberSignIcon',
  TypeBoolean: 'ToggleOnIcon',
  TypeJson: 'CodeSquareIcon',

  // Brand / mascot — keep custom
  Sim: null,
  Wordmark: null,
  Blimp: null,
  Github: null,
  HexSimple: null,
  PillsRing: null,
  BubbleChatPreview: null,
  BubbleChatClose: null,
}
