version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/sim" 
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "fix"
      include: "scope"
    groups:
      development-tools:
        patterns:
          - "*eslint*"
          - "*prettier*"
          - "*test*"
      ui-components:
        patterns:
          - "@shadcn/*"
          - "tailwind*"
      react-ecosystem:
        patterns:
          - "react*"
          - "next*"
    target-branch: "main"
    versioning-strategy: auto
    pull-request-branch-name:
      separator: "-"
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github-actions" 