import {
  ASSOCIATED_ASSET_OUTPUT_PROPERTIES,
  BILL_ADJUSTMENT_OUTPUT_PROPERTIES,
  BILL_LINE_OUTPUT_PROPERTIES,
  BILL_TO_ACCOUNT_OUTPUT_PROPERTIES,
  BILL_TO_SITE_OUTPUT_PROPERTIES,
  CHARGE_ADJUSTMENT_OUTPUT_PROPERTIES,
  CHARGE_OUTPUT_PROPERTIES,
  CHILD_COVERED_LEVEL_OUTPUT_PROPERTIES,
  COVERED_LEVEL_OUTPUT_PROPERTIES,
  ORGANIZATION_OUTPUT_PROPERTIES,
  type OracleFusionSubscriptionResponse,
  PRODUCT_OUTPUT_PROPERTIES,
  SUBSCRIPTION_ASSET_OUTPUT_PROPERTIES,
  SUBSCRIPTION_ITEM_OUTPUT_PROPERTIES,
  SUBSCRIPTION_OUTPUT_PROPERTIES,
  SUBSCRIPTION_PROFILE_OUTPUT_PROPERTIES,
  VALIDATION_RESULT_OUTPUT_PROPERTIES,
} from '@/tools/oracle_fusion_subscription_management/types'
import type { InternalToolConfig, OAuthConfig, OutputProperty, ToolConfig } from '@/tools/types'

export const ORACLE_FUSION_SUBSCRIPTION_OAUTH_CONFIG = {
  required: true,
  provider: 'oracle_fusion_subscription_management',
  credentialKind: 'service-account',
  authoritativeParams: ['instanceUrl'],
} as const satisfies OAuthConfig

export type OracleFusionSubscriptionFieldKind =
  | 'string'
  | 'id'
  | 'ruleId'
  | 'number'
  | 'integer'
  | 'boolean'
  | 'date'
  | 'datetime'

export interface OracleFusionSubscriptionField {
  oracle: string
  param: string
  kind: OracleFusionSubscriptionFieldKind
  nullable: boolean
  max?: number
  create: boolean
  update: boolean
  required: boolean
}

export interface OracleFusionSubscriptionEntity {
  resource: string
  keyParam: string
  publicKey: string | null
  parents: readonly string[]
  scope: boolean
  fields: readonly OracleFusionSubscriptionField[]
  outputProperties: Record<string, OutputProperty>
  idFields: readonly string[]
  ruleIdFields: readonly string[]
}

export interface OracleFusionSubscriptionOperation {
  entity: string
  kind: 'list' | 'get' | 'create' | 'update' | 'delete' | 'action'
  action?: string
  fields?: readonly OracleFusionSubscriptionField[]
  result?: 'string' | 'number'
}

/** Scope variants were verified independently and have identical selected field contracts. */
export const ORACLE_FUSION_SUBSCRIPTION_ENTITIES: Record<string, OracleFusionSubscriptionEntity> = {
  subscription: {
    resource: 'subscriptions',
    keyParam: 'subscriptionNumber',
    publicKey: 'SubscriptionNumber',
    parents: [],
    scope: false,
    fields: [
      {
        oracle: 'SubscriptionNumber',
        param: 'newSubscriptionNumber',
        kind: 'string',
        nullable: false,
        max: 120,
        create: true,
        update: false,
        required: true,
      },
      {
        oracle: 'Description',
        param: 'description',
        kind: 'string',
        nullable: true,
        max: 1995,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'ShortDescription',
        param: 'shortDescription',
        kind: 'string',
        nullable: true,
        max: 600,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'PrimaryPartyId',
        param: 'primaryPartyId',
        kind: 'id',
        nullable: false,
        create: true,
        update: false,
        required: true,
      },
      {
        oracle: 'BillToAccountId',
        param: 'billToAccountId',
        kind: 'id',
        nullable: false,
        create: true,
        update: true,
        required: true,
      },
      {
        oracle: 'BillToSiteUseId',
        param: 'billToSiteUseId',
        kind: 'id',
        nullable: false,
        create: true,
        update: true,
        required: true,
      },
      {
        oracle: 'BillToContactId',
        param: 'billToContactId',
        kind: 'id',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'BusinessUnitId',
        param: 'businessUnitId',
        kind: 'id',
        nullable: false,
        create: true,
        update: false,
        required: true,
      },
      {
        oracle: 'LegalEntityId',
        param: 'legalEntityId',
        kind: 'id',
        nullable: false,
        create: true,
        update: false,
        required: true,
      },
      {
        oracle: 'SubscriptionProfileId',
        param: 'subscriptionProfileId',
        kind: 'id',
        nullable: false,
        create: true,
        update: false,
        required: true,
      },
      {
        oracle: 'DefinitionOrganizationId',
        param: 'definitionOrganizationId',
        kind: 'id',
        nullable: false,
        create: true,
        update: false,
        required: true,
      },
      {
        oracle: 'AccountingRuleId',
        param: 'accountingRuleId',
        kind: 'ruleId',
        nullable: false,
        create: true,
        update: true,
        required: true,
      },
      {
        oracle: 'InvoicingRuleId',
        param: 'invoicingRuleId',
        kind: 'ruleId',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'TransactionTypeName',
        param: 'transactionTypeName',
        kind: 'string',
        nullable: false,
        max: 80,
        create: true,
        update: true,
        required: true,
      },
      {
        oracle: 'Currency',
        param: 'currency',
        kind: 'string',
        nullable: false,
        max: 15,
        create: true,
        update: true,
        required: true,
      },
      {
        oracle: 'StartDate',
        param: 'startDate',
        kind: 'date',
        nullable: false,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'EndDate',
        param: 'endDate',
        kind: 'date',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'Duration',
        param: 'duration',
        kind: 'integer',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'Period',
        param: 'period',
        kind: 'string',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'PartialPeriodStart',
        param: 'partialPeriodStart',
        kind: 'string',
        nullable: false,
        max: 30,
        create: true,
        update: false,
        required: true,
      },
      {
        oracle: 'PartialPeriodType',
        param: 'partialPeriodType',
        kind: 'string',
        nullable: false,
        max: 30,
        create: true,
        update: false,
        required: true,
      },
      {
        oracle: 'BillingFrequency',
        param: 'billingFrequency',
        kind: 'string',
        nullable: true,
        max: 30,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'PaymentTermsId',
        param: 'paymentTermsId',
        kind: 'id',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'PaymentMethod',
        param: 'paymentMethod',
        kind: 'string',
        nullable: true,
        max: 30,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'PONumber',
        param: 'pONumber',
        kind: 'string',
        nullable: true,
        max: 50,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'RenewalType',
        param: 'renewalType',
        kind: 'string',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'RenewalProcess',
        param: 'renewalProcess',
        kind: 'string',
        nullable: true,
        max: 30,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'RenewalDuration',
        param: 'renewalDuration',
        kind: 'integer',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'RenewalDurationPeriod',
        param: 'renewalDurationPeriod',
        kind: 'string',
        nullable: true,
        max: 30,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'SourceSystem',
        param: 'sourceSystem',
        kind: 'string',
        nullable: true,
        max: 30,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'SourceKey',
        param: 'sourceKey',
        kind: 'string',
        nullable: true,
        max: 120,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'SourceNumber',
        param: 'sourceNumber',
        kind: 'string',
        nullable: true,
        max: 120,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'SubscriptionInvoiceText',
        param: 'subscriptionInvoiceText',
        kind: 'string',
        nullable: true,
        max: 4000,
        create: true,
        update: true,
        required: false,
      },
    ],
    outputProperties: SUBSCRIPTION_OUTPUT_PROPERTIES,
    idFields: [
      'SubscriptionId',
      'PrimaryPartyId',
      'BillToAccountId',
      'BillToSiteUseId',
      'BillToContactId',
      'BusinessUnitId',
      'LegalEntityId',
      'SubscriptionProfileId',
      'DefinitionOrganizationId',
      'PaymentTermsId',
      'SystemActionRequestId',
    ],
    ruleIdFields: ['AccountingRuleId', 'InvoicingRuleId'],
  },
  product: {
    resource: 'products',
    keyParam: 'subscriptionProductPuid',
    publicKey: 'SubscriptionProductPuid',
    parents: ['subscriptionNumber'],
    scope: false,
    fields: [
      {
        oracle: 'SubscriptionProductPuid',
        param: 'newSubscriptionProductPuid',
        kind: 'string',
        nullable: false,
        max: 120,
        create: true,
        update: false,
        required: true,
      },
      {
        oracle: 'LineNumber',
        param: 'lineNumber',
        kind: 'string',
        nullable: false,
        max: 300,
        create: true,
        update: false,
        required: true,
      },
      {
        oracle: 'InventoryItemId',
        param: 'inventoryItemId',
        kind: 'id',
        nullable: false,
        create: true,
        update: true,
        required: true,
      },
      {
        oracle: 'DefinitionOrganizationId',
        param: 'definitionOrganizationId',
        kind: 'id',
        nullable: false,
        create: true,
        update: false,
        required: true,
      },
      {
        oracle: 'AccountingRuleId',
        param: 'accountingRuleId',
        kind: 'ruleId',
        nullable: false,
        create: true,
        update: true,
        required: true,
      },
      {
        oracle: 'InvoicingRuleId',
        param: 'invoicingRuleId',
        kind: 'ruleId',
        nullable: false,
        create: true,
        update: true,
        required: true,
      },
      {
        oracle: 'BillToAccountId',
        param: 'billToAccountId',
        kind: 'id',
        nullable: false,
        create: true,
        update: true,
        required: true,
      },
      {
        oracle: 'BillToSiteUseId',
        param: 'billToSiteUseId',
        kind: 'id',
        nullable: false,
        create: true,
        update: true,
        required: true,
      },
      {
        oracle: 'BillToContactId',
        param: 'billToContactId',
        kind: 'id',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'BillingFrequency',
        param: 'billingFrequency',
        kind: 'string',
        nullable: false,
        max: 30,
        create: true,
        update: true,
        required: true,
      },
      {
        oracle: 'Currency',
        param: 'currency',
        kind: 'string',
        nullable: false,
        max: 15,
        create: true,
        update: false,
        required: true,
      },
      {
        oracle: 'TransactionTypeName',
        param: 'transactionTypeName',
        kind: 'string',
        nullable: false,
        max: 30,
        create: true,
        update: true,
        required: true,
      },
      {
        oracle: 'StartDate',
        param: 'startDate',
        kind: 'date',
        nullable: false,
        create: true,
        update: true,
        required: true,
      },
      {
        oracle: 'EndDate',
        param: 'endDate',
        kind: 'date',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'Quantity',
        param: 'quantity',
        kind: 'number',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'UnitPrice',
        param: 'unitPrice',
        kind: 'number',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'Description',
        param: 'description',
        kind: 'string',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'PaymentTermsId',
        param: 'paymentTermsId',
        kind: 'id',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'PaymentMethod',
        param: 'paymentMethod',
        kind: 'string',
        nullable: true,
        max: 30,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'PONumber',
        param: 'pONumber',
        kind: 'string',
        nullable: true,
        max: 50,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'ItemUnitOfMeasure',
        param: 'itemUnitOfMeasure',
        kind: 'string',
        nullable: true,
        max: 15,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'InvoiceText',
        param: 'invoiceText',
        kind: 'string',
        nullable: true,
        max: 4000,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'ExternalAssetKey',
        param: 'externalAssetKey',
        kind: 'string',
        nullable: true,
        max: 120,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'SourceSystem',
        param: 'sourceSystem',
        kind: 'string',
        nullable: true,
        max: 30,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'SourceKey',
        param: 'sourceKey',
        kind: 'string',
        nullable: true,
        max: 120,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'SourceLineKey',
        param: 'sourceLineKey',
        kind: 'string',
        nullable: true,
        max: 120,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'SourceLineNumber',
        param: 'sourceLineNumber',
        kind: 'string',
        nullable: true,
        max: 120,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'RenewalType',
        param: 'renewalType',
        kind: 'string',
        nullable: true,
        max: 30,
        create: true,
        update: true,
        required: false,
      },
    ],
    outputProperties: PRODUCT_OUTPUT_PROPERTIES,
    idFields: [
      'SubscriptionId',
      'SubscriptionProductId',
      'InventoryItemId',
      'DefinitionOrganizationId',
      'BillToAccountId',
      'BillToSiteUseId',
      'PaymentTermsId',
    ],
    ruleIdFields: ['AccountingRuleId', 'InvoicingRuleId'],
  },
  coveredLevel: {
    resource: 'coveredLevels',
    keyParam: 'coveredLevelPuid',
    publicKey: 'CoveredLevelPuid',
    parents: ['subscriptionNumber', 'subscriptionProductPuid'],
    scope: false,
    fields: [
      {
        oracle: 'CoveredLevelPuid',
        param: 'newCoveredLevelPuid',
        kind: 'string',
        nullable: false,
        max: 120,
        create: true,
        update: false,
        required: true,
      },
      {
        oracle: 'Type',
        param: 'type',
        kind: 'string',
        nullable: false,
        max: 30,
        create: true,
        update: false,
        required: true,
      },
      {
        oracle: 'StartDate',
        param: 'startDate',
        kind: 'date',
        nullable: false,
        create: true,
        update: true,
        required: true,
      },
      {
        oracle: 'EndDate',
        param: 'endDate',
        kind: 'date',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'Description',
        param: 'description',
        kind: 'string',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'AssetId',
        param: 'assetId',
        kind: 'id',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'PartyId',
        param: 'partyId',
        kind: 'id',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'CustomerAccountId',
        param: 'customerAccountId',
        kind: 'id',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'ProductGroupId',
        param: 'productGroupId',
        kind: 'id',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'InventoryItemId',
        param: 'inventoryItemId',
        kind: 'id',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'Quantity',
        param: 'quantity',
        kind: 'number',
        nullable: false,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'UnitPrice',
        param: 'unitPrice',
        kind: 'number',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'ItemUnitOfMeasure',
        param: 'itemUnitOfMeasure',
        kind: 'string',
        nullable: true,
        max: 15,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'InvoiceText',
        param: 'invoiceText',
        kind: 'string',
        nullable: true,
        max: 2000,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'SourceSystem',
        param: 'sourceSystem',
        kind: 'string',
        nullable: true,
        max: 30,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'SourceKey',
        param: 'sourceKey',
        kind: 'string',
        nullable: true,
        max: 120,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'SourceLineKey',
        param: 'sourceLineKey',
        kind: 'string',
        nullable: true,
        max: 120,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'SourceLineNumber',
        param: 'sourceLineNumber',
        kind: 'string',
        nullable: true,
        max: 120,
        create: true,
        update: true,
        required: false,
      },
    ],
    outputProperties: COVERED_LEVEL_OUTPUT_PROPERTIES,
    idFields: [
      'CoveredLevelId',
      'ParentCoveredLevelId',
      'SubscriptionId',
      'SubscriptionProductId',
      'AssetId',
      'PartyId',
      'CustomerAccountId',
      'ProductGroupId',
      'InventoryItemId',
    ],
    ruleIdFields: [],
  },
  associatedAsset: {
    resource: 'associatedAsset',
    keyParam: 'associatedAssetPuid',
    publicKey: 'AssociatedAssetPuid',
    parents: ['subscriptionNumber', 'subscriptionProductPuid'],
    scope: false,
    fields: [
      {
        oracle: 'AssociatedAssetPuid',
        param: 'associatedAssetPuid',
        kind: 'string',
        nullable: false,
        max: 120,
        create: true,
        update: false,
        required: false,
      },
      {
        oracle: 'AssetId',
        param: 'assetId',
        kind: 'id',
        nullable: true,
        create: true,
        update: false,
        required: false,
      },
      {
        oracle: 'AssetName',
        param: 'assetName',
        kind: 'string',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'AssetSerialNumber',
        param: 'assetSerialNumber',
        kind: 'string',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'InventoryItemId',
        param: 'inventoryItemId',
        kind: 'id',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'ProductName',
        param: 'productName',
        kind: 'string',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'Quantity',
        param: 'quantity',
        kind: 'number',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'UnitOfMeasureCode',
        param: 'unitOfMeasureCode',
        kind: 'string',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'SourceSystem',
        param: 'sourceSystem',
        kind: 'string',
        nullable: true,
        max: 30,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'SourceKey',
        param: 'sourceKey',
        kind: 'string',
        nullable: true,
        max: 120,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'SourceLineKey',
        param: 'sourceLineKey',
        kind: 'string',
        nullable: true,
        max: 120,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'SourceLineNumber',
        param: 'sourceLineNumber',
        kind: 'string',
        nullable: true,
        max: 120,
        create: true,
        update: true,
        required: false,
      },
    ],
    outputProperties: ASSOCIATED_ASSET_OUTPUT_PROPERTIES,
    idFields: [
      'AssociatedAssetId',
      'SubscriptionId',
      'SubscriptionProductId',
      'AssetId',
      'InventoryItemId',
    ],
    ruleIdFields: [],
  },
  charge: {
    resource: 'charges',
    keyParam: 'chargePuid',
    publicKey: 'ChargePuid',
    parents: ['subscriptionNumber', 'subscriptionProductPuid'],
    scope: true,
    fields: [
      {
        oracle: 'ChargePuid',
        param: 'chargePuid',
        kind: 'string',
        nullable: true,
        max: 120,
        create: true,
        update: false,
        required: false,
      },
      {
        oracle: 'ChargeName',
        param: 'chargeName',
        kind: 'string',
        nullable: true,
        max: 120,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'ChargeDefinition',
        param: 'chargeDefinition',
        kind: 'string',
        nullable: true,
        max: 30,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'PriceType',
        param: 'priceType',
        kind: 'string',
        nullable: false,
        max: 30,
        create: true,
        update: true,
        required: true,
      },
      {
        oracle: 'UnitListPrice',
        param: 'unitListPrice',
        kind: 'number',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'PricePeriodicity',
        param: 'pricePeriodicity',
        kind: 'string',
        nullable: true,
        max: 30,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'BillingFreq',
        param: 'billingFreq',
        kind: 'string',
        nullable: true,
        max: 30,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'InvoicingRuleId',
        param: 'invoicingRuleId',
        kind: 'ruleId',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'SequenceNumber',
        param: 'sequenceNumber',
        kind: 'integer',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'UsageUnitOfMeasure',
        param: 'usageUnitOfMeasure',
        kind: 'string',
        nullable: true,
        max: 3,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'MinimumAmount',
        param: 'minimumAmount',
        kind: 'number',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'MinimumQuantity',
        param: 'minimumQuantity',
        kind: 'number',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
    ],
    outputProperties: CHARGE_OUTPUT_PROPERTIES,
    idFields: ['ChargeId', 'SubscriptionId', 'SubscriptionProductId', 'CoveredLevelId'],
    ruleIdFields: ['InvoicingRuleId'],
  },
  chargeAdjustment: {
    resource: 'adjustments',
    keyParam: 'chargeAdjustmentPuid',
    publicKey: 'ChargeAdjustmentPuid',
    parents: ['subscriptionNumber', 'subscriptionProductPuid', 'chargePuid'],
    scope: true,
    fields: [
      {
        oracle: 'ChargeAdjustmentPuid',
        param: 'chargeAdjustmentPuid',
        kind: 'string',
        nullable: true,
        max: 120,
        create: true,
        update: false,
        required: false,
      },
      {
        oracle: 'AdjustmentName',
        param: 'adjustmentName',
        kind: 'string',
        nullable: true,
        max: 120,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'AdjustmentType',
        param: 'adjustmentType',
        kind: 'string',
        nullable: true,
        max: 30,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'AdjustmentValue',
        param: 'adjustmentValue',
        kind: 'number',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'AdjustmentBasis',
        param: 'adjustmentBasis',
        kind: 'string',
        nullable: true,
        max: 30,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'AdjustmentReasonCode',
        param: 'adjustmentReasonCode',
        kind: 'string',
        nullable: true,
        max: 30,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'Effectivity',
        param: 'effectivity',
        kind: 'string',
        nullable: true,
        max: 30,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'PeriodFrom',
        param: 'periodFrom',
        kind: 'number',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'PeriodUntil',
        param: 'periodUntil',
        kind: 'number',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'NumberOfPeriods',
        param: 'numberOfPeriods',
        kind: 'number',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'ValidFrom',
        param: 'validFrom',
        kind: 'datetime',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'ValidUntil',
        param: 'validUntil',
        kind: 'datetime',
        nullable: true,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'RevenueOptionChargeAdjustment',
        param: 'revenueOptionChargeAdjustment',
        kind: 'string',
        nullable: true,
        max: 30,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'RevenuePeriodChargeAdjustment',
        param: 'revenuePeriodChargeAdjustment',
        kind: 'string',
        nullable: true,
        max: 30,
        create: true,
        update: true,
        required: false,
      },
      {
        oracle: 'Reason',
        param: 'reason',
        kind: 'string',
        nullable: true,
        max: 120,
        create: true,
        update: true,
        required: false,
      },
    ],
    outputProperties: CHARGE_ADJUSTMENT_OUTPUT_PROPERTIES,
    idFields: ['ChargeAdjustmentId', 'ChargeId', 'SubscriptionId', 'SubscriptionProductId'],
    ruleIdFields: [],
  },
  billLine: {
    resource: 'billLines',
    keyParam: 'billLinePuid',
    publicKey: 'BillLinePuid',
    parents: ['subscriptionNumber', 'subscriptionProductPuid'],
    scope: true,
    fields: [],
    outputProperties: BILL_LINE_OUTPUT_PROPERTIES,
    idFields: [
      'BillLineId',
      'SubscriptionId',
      'SubscriptionProductId',
      'CoveredLevelId',
      'ChargeId',
      'TrxId',
      'TrxLineId',
    ],
    ruleIdFields: [],
  },
  billAdjustment: {
    resource: 'billAdjustments',
    keyParam: 'billAdjustmentPuid',
    publicKey: 'BillAdjustmentPuid',
    parents: ['subscriptionNumber', 'subscriptionProductPuid', 'billLinePuid'],
    scope: true,
    fields: [],
    outputProperties: BILL_ADJUSTMENT_OUTPUT_PROPERTIES,
    idFields: [
      'BillAdjustmentId',
      'BillLineId',
      'ChargeAdjustmentId',
      'SubscriptionId',
      'SubscriptionProductId',
    ],
    ruleIdFields: [],
  },
  validationResult: {
    resource: 'validateSubscription',
    keyParam: 'validationResultKey',
    publicKey: null,
    parents: ['subscriptionNumber'],
    scope: false,
    fields: [],
    outputProperties: VALIDATION_RESULT_OUTPUT_PROPERTIES,
    idFields: ['ObjectId', 'RelatedObjectId'],
    ruleIdFields: [],
  },
  subscriptionProfile: {
    resource: 'subscriptionProfiles',
    keyParam: 'subscriptionProfileKey',
    publicKey: null,
    parents: [],
    scope: false,
    fields: [],
    outputProperties: SUBSCRIPTION_PROFILE_OUTPUT_PROPERTIES,
    idFields: ['SubscriptionProfileId', 'PaymentTermsId'],
    ruleIdFields: ['AccountingRuleId', 'InvoicingRuleId'],
  },
  subscriptionItem: {
    resource: 'subscriptionItems',
    keyParam: 'subscriptionItemKey',
    publicKey: null,
    parents: [],
    scope: false,
    fields: [],
    outputProperties: SUBSCRIPTION_ITEM_OUTPUT_PROPERTIES,
    idFields: ['InventoryItemId', 'OrganizationId'],
    ruleIdFields: [],
  },
  subscriptionAsset: {
    resource: 'subscriptionAssets',
    keyParam: 'subscriptionAssetKey',
    publicKey: null,
    parents: [],
    scope: false,
    fields: [],
    outputProperties: SUBSCRIPTION_ASSET_OUTPUT_PROPERTIES,
    idFields: ['AssetId', 'InventoryItemId', 'OrganizationId', 'CustomerId', 'PartyId', 'BuId'],
    ruleIdFields: [],
  },
  organization: {
    resource: 'organizationCodes',
    keyParam: 'organizationKey',
    publicKey: null,
    parents: [],
    scope: false,
    fields: [],
    outputProperties: ORGANIZATION_OUTPUT_PROPERTIES,
    idFields: ['OrganizationId'],
    ruleIdFields: [],
  },
  billToAccount: {
    resource: 'billToAccounts',
    keyParam: 'billToAccountKey',
    publicKey: null,
    parents: [],
    scope: false,
    fields: [],
    outputProperties: BILL_TO_ACCOUNT_OUTPUT_PROPERTIES,
    idFields: ['CustAccountId', 'PartyId'],
    ruleIdFields: [],
  },
  billToSite: {
    resource: 'billToSites',
    keyParam: 'billToSiteKey',
    publicKey: null,
    parents: [],
    scope: false,
    fields: [],
    outputProperties: BILL_TO_SITE_OUTPUT_PROPERTIES,
    idFields: ['SiteUseId', 'CustAccountId'],
    ruleIdFields: [],
  },
  childCoveredLevel: {
    resource: 'childCoveredLevels',
    keyParam: 'childCoveredLevelPuid',
    publicKey: 'CoveredLevelPuid',
    parents: ['subscriptionNumber', 'subscriptionProductPuid', 'coveredLevelPuid'],
    scope: false,
    fields: [],
    outputProperties: CHILD_COVERED_LEVEL_OUTPUT_PROPERTIES,
    idFields: [
      'CoveredLevelId',
      'ParentCoveredLevelId',
      'SubscriptionId',
      'SubscriptionProductId',
      'AssetId',
      'PartyId',
      'CustomerAccountId',
      'ProductGroupId',
      'InventoryItemId',
    ],
    ruleIdFields: [],
  },
}

export const ORACLE_FUSION_SUBSCRIPTION_OPERATIONS: Record<
  string,
  OracleFusionSubscriptionOperation
> = {
  activate_subscription: {
    entity: 'subscription',
    kind: 'action',
    action: 'activate',
    result: 'string',
    fields: [
      {
        oracle: 'ignoreWarnings',
        param: 'ignoreWarnings',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
    ],
  },
  amend_product: {
    entity: 'product',
    kind: 'action',
    action: 'amend',
    result: 'string',
    fields: [
      {
        oracle: 'copyCustomChildObjects',
        param: 'copyCustomChildObjects',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'amendCreditMethod',
        param: 'amendCreditMethod',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'defaultRevenueAction',
        param: 'defaultRevenueAction',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'copyCharges',
        param: 'copyCharges',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'copyAdjustments',
        param: 'copyAdjustments',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'creditType',
        param: 'creditType',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'amendDescription',
        param: 'amendDescription',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'amendReason',
        param: 'amendReason',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'overrideCreditAmount',
        param: 'overrideCreditAmount',
        kind: 'number',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'copyOneTimeCharges',
        param: 'copyOneTimeCharges',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'revenueOption',
        param: 'revenueOption',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'balanceTermLineTerminatedPartialPeriodOption',
        param: 'balanceTermLineTerminatedPartialPeriodOption',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'lineNumber',
        param: 'lineNumber',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'amendEffectiveDate',
        param: 'amendEffectiveDate',
        kind: 'date',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'balanceNewLineFirstPartialPeriodOption',
        param: 'balanceNewLineFirstPartialPeriodOption',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
    ],
  },
  calculate_product_credit: {
    entity: 'product',
    kind: 'action',
    action: 'calculateCreditAmount',
    result: 'string',
    fields: [
      {
        oracle: 'closedDate',
        param: 'closedDate',
        kind: 'date',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'closeCreditMethod',
        param: 'closeCreditMethod',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'coveredLevelPuid',
        param: 'coveredLevelPuid',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'externalAssetKey',
        param: 'externalAssetKey',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
    ],
  },
  calculate_product_termination_fee: {
    entity: 'product',
    kind: 'action',
    action: 'calculateEarlyTerminationFee',
    result: 'number',
    fields: [
      {
        oracle: 'closedDate',
        param: 'closedDate',
        kind: 'date',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
    ],
  },
  cancel_product: {
    entity: 'product',
    kind: 'action',
    action: 'cancel',
    result: 'string',
    fields: [
      {
        oracle: 'canceledDate',
        param: 'canceledDate',
        kind: 'date',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'cancelDescription',
        param: 'cancelDescription',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'cancelReason',
        param: 'cancelReason',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
    ],
  },
  cancel_subscription: {
    entity: 'subscription',
    kind: 'action',
    action: 'cancel',
    result: 'string',
    fields: [
      {
        oracle: 'canceledDate',
        param: 'canceledDate',
        kind: 'date',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'cancelDescription',
        param: 'cancelDescription',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'cancelReason',
        param: 'cancelReason',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
    ],
  },
  close_product: {
    entity: 'product',
    kind: 'action',
    action: 'close',
    result: 'string',
    fields: [
      {
        oracle: 'closeDescription',
        param: 'closeDescription',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'closedDate',
        param: 'closedDate',
        kind: 'date',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'overrideCreditAmount',
        param: 'overrideCreditAmount',
        kind: 'number',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'closeCreditMethod',
        param: 'closeCreditMethod',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'revenueOption',
        param: 'revenueOption',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'balanceTerminatedPartialPeriodOption',
        param: 'balanceTerminatedPartialPeriodOption',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'earlyTerminationFee',
        param: 'earlyTerminationFee',
        kind: 'number',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'closeReason',
        param: 'closeReason',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'creditType',
        param: 'creditType',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
    ],
  },
  close_subscription: {
    entity: 'subscription',
    kind: 'action',
    action: 'close',
    result: 'string',
    fields: [
      {
        oracle: 'closeDescription',
        param: 'closeDescription',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'closedDate',
        param: 'closedDate',
        kind: 'date',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'overrideCreditAmount',
        param: 'overrideCreditAmount',
        kind: 'number',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'closeCreditMethod',
        param: 'closeCreditMethod',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'revenueOption',
        param: 'revenueOption',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'balanceTerminatedPartialPeriodOption',
        param: 'balanceTerminatedPartialPeriodOption',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'closeReason',
        param: 'closeReason',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'creditType',
        param: 'creditType',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
    ],
  },
  create_associated_asset: {
    entity: 'associatedAsset',
    kind: 'create',
  },
  create_charge: {
    entity: 'charge',
    kind: 'create',
  },
  create_charge_adjustment: {
    entity: 'chargeAdjustment',
    kind: 'create',
  },
  create_covered_level: {
    entity: 'coveredLevel',
    kind: 'create',
  },
  create_product: {
    entity: 'product',
    kind: 'create',
  },
  create_subscription: {
    entity: 'subscription',
    kind: 'create',
  },
  delete_associated_asset: {
    entity: 'associatedAsset',
    kind: 'delete',
  },
  delete_charge: {
    entity: 'charge',
    kind: 'delete',
  },
  delete_charge_adjustment: {
    entity: 'chargeAdjustment',
    kind: 'delete',
  },
  delete_covered_level: {
    entity: 'coveredLevel',
    kind: 'delete',
  },
  delete_product: {
    entity: 'product',
    kind: 'delete',
  },
  delete_subscription: {
    entity: 'subscription',
    kind: 'delete',
  },
  get_associated_asset: {
    entity: 'associatedAsset',
    kind: 'get',
  },
  get_bill_adjustment: {
    entity: 'billAdjustment',
    kind: 'get',
  },
  get_bill_line: {
    entity: 'billLine',
    kind: 'get',
  },
  get_charge: {
    entity: 'charge',
    kind: 'get',
  },
  get_charge_adjustment: {
    entity: 'chargeAdjustment',
    kind: 'get',
  },
  get_child_covered_level: {
    entity: 'childCoveredLevel',
    kind: 'get',
  },
  get_covered_level: {
    entity: 'coveredLevel',
    kind: 'get',
  },
  get_product: {
    entity: 'product',
    kind: 'get',
  },
  get_subscription: {
    entity: 'subscription',
    kind: 'get',
  },
  get_subscription_asset: {
    entity: 'subscriptionAsset',
    kind: 'get',
  },
  get_subscription_item: {
    entity: 'subscriptionItem',
    kind: 'get',
  },
  get_subscription_profile: {
    entity: 'subscriptionProfile',
    kind: 'get',
  },
  get_validation_result: {
    entity: 'validationResult',
    kind: 'get',
  },
  hold_product: {
    entity: 'product',
    kind: 'action',
    action: 'putOnHold',
    result: 'string',
    fields: [],
  },
  hold_subscription: {
    entity: 'subscription',
    kind: 'action',
    action: 'putOnHold',
    result: 'string',
    fields: [],
  },
  list_associated_assets: {
    entity: 'associatedAsset',
    kind: 'list',
  },
  list_bill_adjustments: {
    entity: 'billAdjustment',
    kind: 'list',
  },
  list_bill_lines: {
    entity: 'billLine',
    kind: 'list',
  },
  list_charge_adjustments: {
    entity: 'chargeAdjustment',
    kind: 'list',
  },
  list_charges: {
    entity: 'charge',
    kind: 'list',
  },
  list_child_covered_levels: {
    entity: 'childCoveredLevel',
    kind: 'list',
  },
  list_covered_levels: {
    entity: 'coveredLevel',
    kind: 'list',
  },
  list_products: {
    entity: 'product',
    kind: 'list',
  },
  list_subscription_assets: {
    entity: 'subscriptionAsset',
    kind: 'list',
  },
  list_subscription_items: {
    entity: 'subscriptionItem',
    kind: 'list',
  },
  list_subscription_profiles: {
    entity: 'subscriptionProfile',
    kind: 'list',
  },
  list_subscriptions: {
    entity: 'subscription',
    kind: 'list',
  },
  list_validation_results: {
    entity: 'validationResult',
    kind: 'list',
  },
  remove_product_hold: {
    entity: 'product',
    kind: 'action',
    action: 'removeHold',
    result: 'string',
    fields: [],
  },
  remove_subscription_hold: {
    entity: 'subscription',
    kind: 'action',
    action: 'removeHold',
    result: 'string',
    fields: [],
  },
  renew_subscription: {
    entity: 'subscription',
    kind: 'action',
    action: 'renew',
    result: 'string',
    fields: [
      {
        oracle: 'duration',
        param: 'duration',
        kind: 'number',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'period',
        param: 'period',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'subscriptionNumber',
        param: 'newSubscriptionNumber',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'revenueOption',
        param: 'revenueOption',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'ignoreWarning',
        param: 'ignoreWarning',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'revenueAction',
        param: 'revenueAction',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
    ],
  },
  resume_product: {
    entity: 'product',
    kind: 'action',
    action: 'resume',
    result: 'string',
    fields: [
      {
        oracle: 'resumePeriod',
        param: 'resumePeriod',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'resumeDuration',
        param: 'resumeDuration',
        kind: 'number',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'autoExtendFlag',
        param: 'autoExtendFlag',
        kind: 'boolean',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'resumeDate',
        param: 'resumeDate',
        kind: 'date',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
    ],
  },
  suspend_product: {
    entity: 'product',
    kind: 'action',
    action: 'suspend',
    result: 'string',
    fields: [
      {
        oracle: 'suspendReason',
        param: 'suspendReason',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'resumePeriod',
        param: 'resumePeriod',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'resumeDuration',
        param: 'resumeDuration',
        kind: 'number',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'suspendedDate',
        param: 'suspendedDate',
        kind: 'date',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'autoExtendFlag',
        param: 'autoExtendFlag',
        kind: 'boolean',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
      {
        oracle: 'resumeDate',
        param: 'resumeDate',
        kind: 'date',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
    ],
  },
  update_associated_asset: {
    entity: 'associatedAsset',
    kind: 'update',
  },
  update_charge: {
    entity: 'charge',
    kind: 'update',
  },
  update_charge_adjustment: {
    entity: 'chargeAdjustment',
    kind: 'update',
  },
  update_covered_level: {
    entity: 'coveredLevel',
    kind: 'update',
  },
  update_product: {
    entity: 'product',
    kind: 'update',
  },
  update_subscription: {
    entity: 'subscription',
    kind: 'update',
  },
  validate_subscription: {
    entity: 'subscription',
    kind: 'action',
    action: 'submitValidation',
    result: 'string',
    fields: [
      {
        oracle: 'ignoreWarnings',
        param: 'ignoreWarnings',
        kind: 'string',
        nullable: true,
        create: false,
        update: false,
        required: false,
      },
    ],
  },
  withdraw_subscription: {
    entity: 'subscription',
    kind: 'action',
    action: 'withdraw',
    result: 'string',
    fields: [],
  },
}

export const oracleFusionSubscriptionAuthParams = {
  oauthCredential: {
    type: 'string',
    required: true,
    visibility: 'user-only',
    description: 'Oracle Fusion service-account credential',
  },
  accessToken: {
    type: 'string',
    required: false,
    visibility: 'hidden',
    description: 'Basic authentication value injected from the selected credential',
  },
  instanceUrl: {
    type: 'string',
    required: false,
    visibility: 'hidden',
    description: 'Credential-authoritative Fusion Applications origin',
  },
} as const satisfies ToolConfig['params']

const stringParam = (description: string, required = false) => ({
  type: 'string' as const,
  required,
  visibility: 'user-or-llm' as const,
  description,
})

export const oracleFusionSubscriptionPageParams = {
  q: stringParam('Documented Oracle q filter, up to 2,048 characters'),
  finder: stringParam('Documented Oracle finder and bind parameters, up to 2,048 characters'),
  orderBy: stringParam('Oracle attributes with optional :asc or :desc, up to 1,024 characters'),
  limit: {
    type: 'number',
    required: false,
    visibility: 'user-or-llm',
    default: 50,
    description: 'Records in this page (1-100; default 50)',
  },
  offset: {
    type: 'number',
    required: false,
    visibility: 'user-or-llm',
    default: 0,
    description: 'Non-negative safe integer offset; default 0',
  },
  totalResults: {
    type: 'boolean',
    required: false,
    visibility: 'user-or-llm',
    default: false,
    description: 'Request the estimated total matching record count',
  },
} satisfies ToolConfig['params']

export function getOracleFusionSubscriptionOperation(
  name: string
): OracleFusionSubscriptionOperation {
  if (!Object.hasOwn(ORACLE_FUSION_SUBSCRIPTION_OPERATIONS, name)) {
    throw new Error('Unsupported Oracle Fusion Subscription Management operation')
  }
  return ORACLE_FUSION_SUBSCRIPTION_OPERATIONS[name]
}

export function getOracleFusionSubscriptionFields(
  operation: OracleFusionSubscriptionOperation
): readonly OracleFusionSubscriptionField[] {
  if (operation.kind === 'action') return operation.fields ?? []
  const fields = ORACLE_FUSION_SUBSCRIPTION_ENTITIES[operation.entity].fields
  if (operation.kind === 'create') return fields.filter((field) => field.create)
  if (operation.kind === 'update') return fields.filter((field) => field.update)
  return []
}

/** Browser-safe declarations; credentials are resolved only by the shared executor. */
export function getOracleFusionSubscriptionParams(name: string): ToolConfig['params'] {
  const operation = getOracleFusionSubscriptionOperation(name)
  const entity = ORACLE_FUSION_SUBSCRIPTION_ENTITIES[operation.entity]
  const params: ToolConfig['params'] = { ...oracleFusionSubscriptionAuthParams }
  for (const parent of entity.parents) {
    params[parent] = stringParam('Parent public number or PUID, not a numeric database ID', true)
  }
  if (['get', 'update', 'delete', 'action'].includes(operation.kind)) {
    params[entity.keyParam] = stringParam(
      entity.publicKey
        ? 'Exact Oracle public number or PUID returned by the corresponding list tool'
        : 'Opaque resourceKey from the corresponding list tool; never construct it from an ID',
      true
    )
  }
  if (entity.scope) {
    params.billingScope = {
      ...stringParam('Choose product or covered_level; default product'),
      default: 'product',
    }
    params.coveredLevelPuid = stringParam('Required only for covered_level billing scope')
  }
  if (operation.kind === 'list') Object.assign(params, oracleFusionSubscriptionPageParams)
  for (const field of getOracleFusionSubscriptionFields(operation)) {
    const required = operation.kind === 'create' && field.required
    const exact = field.kind === 'id' || field.kind === 'ruleId'
    params[field.param] = {
      type: ['number', 'integer'].includes(field.kind)
        ? 'number'
        : field.kind === 'boolean'
          ? 'boolean'
          : 'string',
      required,
      visibility: 'user-or-llm',
      description:
        field.oracle +
        (exact ? ' as an exact decimal string' : '') +
        (field.kind === 'date' ? ' (YYYY-MM-DD)' : '') +
        (field.kind === 'datetime' ? ' (ISO 8601 date-time with timezone)' : '') +
        (field.nullable && !required ? '; explicit null is passed to Oracle' : '') +
        (operation.action === 'renew' && field.param === 'newSubscriptionNumber'
          ? '; number for the renewed subscription'
          : ''),
    }
  }
  return params
}

/** Strip inactive controls before entering the operation-specific strict schema. */
export function createOracleFusionSubscriptionTool<Params extends object>(definition: {
  id: string
  operation: string
  name: string
  description: string
  outputs: Record<string, OutputProperty>
}): InternalToolConfig<Params, OracleFusionSubscriptionResponse> {
  const params = getOracleFusionSubscriptionParams(definition.operation)
  return {
    id: definition.id,
    name: definition.name,
    description: definition.description,
    version: '1.0.0',
    oauth: ORACLE_FUSION_SUBSCRIPTION_OAUTH_CONFIG,
    params,
    operation: {
      input: (values) => {
        const source = values as Record<string, unknown>
        return Object.fromEntries(
          Object.keys(params)
            .filter((key) => source[key] !== undefined)
            .map((key) => [key, source[key]])
        )
      },
    },
    outputs: definition.outputs,
  }
}
