services:
  simstudio:
    image: simstudio-dev:latest
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./apps/sim:/app/apps/sim
      - ./packages:/app/packages
    deploy:
      resources:
        limits:
          memory: 8G
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/simstudio
      - BETTER_AUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - BETTER_AUTH_SECRET=your_auth_secret_here
      - ENCRYPTION_KEY=your_encryption_key_here
      - FREESTYLE_API_KEY=placeholder
      - GOOGLE_CLIENT_ID=placeholder  
      - GOOGLE_CLIENT_SECRET=placeholder
      - GITHUB_CLIENT_ID=placeholder
      - GITHUB_CLIENT_SECRET=placeholder
      - RESEND_API_KEY=placeholder
      - OLLAMA_URL=http://localhost:11434
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'wget', '--spider', '--quiet', 'http://127.0.0.1:3000']
      interval: 90s
      timeout: 5s
      retries: 3
      start_period: 30s

  db:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simstudio
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
