import type { OAuthConfig, OutputProperty, ToolConfig } from '@/tools/types'

export const ORACLE_FUSION_SCM_OAUTH_CONFIG = {
  required: true,
  provider: 'oracle_fusion_scm',
  credentialKind: 'service-account',
  authoritativeParams: ['instanceUrl'],
} as const satisfies OAuthConfig

/** Projects only this operation's public inputs and the trusted injected credential fields. */
export function createOracleFusionScmOperationInput<Params extends object>(
  params: Params,
  activeParams: ToolConfig['params']
): Params {
  const record = params as Record<string, unknown>
  return Object.fromEntries(
    Object.entries(activeParams).flatMap(([key, definition]) => {
      const value = record[key]
      return value == null && !definition.required ? [] : [[key, value]]
    })
  ) as Params
}

export const oracleFusionScmAuthParamFields = {
  oauthCredential: {
    type: 'string',
    required: true,
    visibility: 'user-only',
    description: 'Oracle Fusion Cloud SCM service-account credential',
  },
  accessToken: {
    type: 'string',
    required: false,
    visibility: 'hidden',
    description: 'Base64 Basic authentication value injected from the selected credential',
  },
  instanceUrl: {
    type: 'string',
    required: false,
    visibility: 'hidden',
    description: 'Canonical Fusion Applications origin injected from the selected credential',
  },
} satisfies ToolConfig['params']

const listParams = {
  q: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'Oracle REST Framework q filter expression, up to 2,048 characters',
  },
  orderBy: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'Oracle attribute ordering expression, up to 1,024 characters',
  },
  limit: {
    type: 'number',
    required: false,
    visibility: 'user-or-llm',
    default: 50,
    description: 'Records in this page (integer from 1 to 100; default 50)',
  },
  offset: {
    type: 'number',
    required: false,
    visibility: 'user-or-llm',
    default: 0,
    description: 'Zero-based record offset (non-negative safe integer; default 0)',
  },
  totalResults: {
    type: 'boolean',
    required: false,
    visibility: 'user-or-llm',
    default: false,
    description: 'Ask Oracle to include its estimated total matching record count',
  },
} as const satisfies ToolConfig['params']

export const oracleFusionScmListParamFields = listParams

export const oracleFusionScmFinderListParamFields = {
  q: listParams.q,
  finder: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'Documented Oracle predefined finder expression, up to 2,048 characters',
  },
  orderBy: listParams.orderBy,
  limit: listParams.limit,
  offset: listParams.offset,
  totalResults: listParams.totalResults,
} satisfies ToolConfig['params']

export function oracleFusionScmOpaqueKeyParam(description: string) {
  return {
    type: 'string',
    required: true,
    visibility: 'user-or-llm',
    description,
  } as const
}

const nullable = (
  description: string,
  type: OutputProperty['type'] = 'string'
): OutputProperty => ({ type, description, optional: true, nullable: true })

const key = (description: string): OutputProperty => ({ type: 'string', description })

export const oracleFusionScmInventoryOrganizationOutputProperties = {
  organizationKey: key('Opaque Oracle inventory-organization resource key'),
  OrganizationId: nullable('Inventory organization identifier as a decimal string'),
  OrganizationCode: nullable('Inventory organization code'),
  OrganizationName: nullable('Inventory organization name'),
  Status: nullable('Inventory organization status'),
  LocationId: nullable('Location identifier as a decimal string'),
  LocationCode: nullable('Location code'),
  InventoryFlag: nullable('Whether inventory operations are enabled', 'boolean'),
  ManufacturingPlantFlag: nullable('Whether the organization is a manufacturing plant', 'boolean'),
  ContractManufacturingFlag: nullable('Whether contract manufacturing is enabled', 'boolean'),
  MaintenanceEnabledFlag: nullable('Whether maintenance is enabled', 'boolean'),
  ManagementBusinessUnitId: nullable('Management business unit identifier as a decimal string'),
  ManagementBusinessUnitName: nullable('Management business unit name'),
  LegalEntityId: nullable('Legal entity identifier as a decimal string'),
  LegalEntityName: nullable('Legal entity name'),
  ProfitCenterBusinessUnitId: nullable(
    'Profit-center business unit identifier as a decimal string'
  ),
  ProfitCenterBusinessUnitName: nullable('Profit-center business unit name'),
  MasterOrganizationId: nullable('Master organization identifier as a decimal string'),
  MasterOrganizationCode: nullable('Master organization code'),
  MasterOrganizationName: nullable('Master organization name'),
} satisfies Record<string, OutputProperty>

export const oracleFusionScmItemOutputProperties = {
  itemKey: key('Opaque Oracle item resource key'),
  ItemId: nullable('Item identifier as a decimal string'),
  OrganizationId: nullable('Organization identifier as a decimal string'),
  OrganizationCode: nullable('Organization code'),
  ItemNumber: nullable('Item number'),
  ItemDescription: nullable('Item description'),
  ItemClass: nullable('Item class'),
  ApprovalStatusValue: nullable('Item approval status'),
  ItemStatusValue: nullable('Item status'),
  LifecyclePhaseValue: nullable('Item lifecycle phase'),
  UserItemTypeValue: nullable('User item type'),
  PrimaryUOMValue: nullable('Primary unit of measure'),
  SecondaryUOMValue: nullable('Secondary unit of measure'),
  InventoryItemFlag: nullable('Whether the item is an inventory item', 'boolean'),
  StockEnabledFlag: nullable('Whether stocking is enabled', 'boolean'),
  ShippableFlag: nullable('Whether the item is shippable', 'boolean'),
  BuildInWIPFlag: nullable('Whether the item can be built in work in process', 'boolean'),
  AssetTrackedFlag: nullable('Whether the item is asset tracked', 'boolean'),
  LotControlValue: nullable('Lot-control setting'),
  SerialGenerationValue: nullable('Serial-number generation setting'),
} satisfies Record<string, OutputProperty>

export const oracleFusionScmOnHandQuantityOutputProperties = {
  onHandQuantityKey: key('Opaque Oracle on-hand-quantity resource key'),
  OrganizationId: nullable('Organization identifier as a decimal string'),
  OrganizationCode: nullable('Organization code'),
  InventoryItemId: nullable('Inventory item identifier as a decimal string'),
  ItemNumber: nullable('Item number'),
  SubinventoryCode: nullable('Subinventory code'),
  LocatorId: nullable('Locator identifier as a decimal string'),
  LotNumber: nullable('Lot number'),
  SerialNumber: nullable('Serial number'),
  PrimaryUOMCode: nullable('Primary unit-of-measure code'),
  SecondaryUOMCode: nullable('Secondary unit-of-measure code'),
  OnhandQuantity: nullable('Primary on-hand quantity', 'number'),
  SecondaryOnhandQuantity: nullable('Secondary on-hand quantity', 'number'),
  ReceivingQuantity: nullable('Primary receiving quantity', 'number'),
  SecondaryReceivingQuantity: nullable('Secondary receiving quantity', 'number'),
  ReservedQuantity: nullable('Primary reserved quantity', 'number'),
  SecondaryReservedQuantity: nullable('Secondary reserved quantity', 'number'),
  InboundQuantity: nullable('Primary inbound quantity', 'number'),
  SecondaryInboundQuantity: nullable('Secondary inbound quantity', 'number'),
  ConsignedQuantity: nullable('Primary consigned quantity', 'number'),
  SecondaryConsignedQuantity: nullable('Secondary consigned quantity', 'number'),
  OwningOrganizationId: nullable('Owning organization identifier as a decimal string'),
  OwningOrganization: nullable('Owning organization name'),
} satisfies Record<string, OutputProperty>

export const oracleFusionScmInventoryTransactionOutputProperties = {
  transactionKey: key('Opaque Oracle completed-inventory-transaction resource key'),
  TransactionId: nullable('Transaction identifier as a decimal string'),
  OrganizationId: nullable('Organization identifier as a decimal string'),
  Organization: nullable('Organization code'),
  InventoryItemId: nullable('Inventory item identifier as a decimal string'),
  Item: nullable('Item number or name'),
  ItemDescription: nullable('Item description'),
  Revision: nullable('Item revision'),
  SubinventoryId: nullable('Subinventory identifier as a decimal string'),
  SubinventoryCode: nullable('Subinventory code'),
  SubinventoryName: nullable('Subinventory name'),
  LocatorId: nullable('Locator identifier as a decimal string'),
  Locator: nullable('Locator'),
  TransactionDate: nullable('Transaction date'),
  TransactionType: nullable('Transaction type'),
  TransactionSourceType: nullable('Transaction source type'),
  SourceReference: nullable('Source reference'),
  Reason: nullable('Transaction reason'),
  Reference: nullable('Transaction reference'),
  TransactionQuantity: nullable('Transaction quantity', 'number'),
  Quantity: nullable('Quantity in the primary unit', 'number'),
  TransactionUOM: nullable('Transaction unit of measure'),
  TransactionUOMCode: nullable('Transaction unit-of-measure code'),
  PrimaryUOMCode: nullable('Primary unit-of-measure code'),
  SecondaryQuantity: nullable('Secondary quantity', 'number'),
  SecondaryUOMCode: nullable('Secondary unit-of-measure code'),
  TransferOrganizationId: nullable('Transfer organization identifier as a decimal string'),
  TransferOrganizationCode: nullable('Transfer organization code'),
  TransferOrganization: nullable('Transfer organization name'),
  TransferSubinventoryCode: nullable('Transfer subinventory code'),
} satisfies Record<string, OutputProperty>

export const oracleFusionScmSupplyRequestOutputProperties = {
  supplyRequestKey: key('Opaque Oracle supply-request resource key'),
  InterfaceBatchNumber: nullable('Interface batch number'),
  InterfaceSourceCode: nullable('Interface source code'),
  SupplyOrderReferenceId: nullable('Supply-order source reference identifier as a decimal string'),
  SupplyOrderReferenceNumber: nullable('Supply-order source reference number'),
  SupplyOrderSource: nullable('Supply-order source'),
  SupplyRequestDate: nullable('Supply request date'),
  SupplyRequestStatus: nullable('Supply request status'),
  SupplyOrderNumber: nullable('Supply order number'),
  SupplyOrderStatus: nullable('Supply order status'),
  AllowPartialRequestFlag: nullable('Whether partial fulfillment is allowed', 'boolean'),
  ProcessRequestFlag: nullable('Whether the request is marked for processing', 'boolean'),
  TrustedSource: nullable('Trusted source identifier as a decimal string'),
} satisfies Record<string, OutputProperty>

export const oracleFusionScmSupplyOrderLineOutputProperties = {
  supplyOrderLineKey: key('Opaque Oracle supply-order-line resource key'),
  SupplyLineId: nullable('Supply line identifier as a decimal string'),
  SupplyOrderHeaderId: nullable('Supply order header identifier as a decimal string'),
  SupplyLineNumber: nullable('Supply line number as a decimal string'),
  SupplyLineStatus: nullable('Supply line status'),
  SupplyType: nullable('Supply type'),
  ItemId: nullable('Item identifier as a decimal string'),
  ItemNumber: nullable('Item number'),
  ItemDescription: nullable('Item description'),
  ItemRevision: nullable('Item revision'),
  SupplyOrderReferenceLineId: nullable('Source reference line identifier as a decimal string'),
  SupplyOrderReferenceLineNumber: nullable('Source reference line number'),
  Quantity: nullable('Requested supply quantity', 'number'),
  UOMCode: nullable('Unit-of-measure code'),
  UOMName: nullable('Unit-of-measure name'),
  NeedByDate: nullable('Need-by date'),
  DestinationOrganizationId: nullable('Destination organization identifier as a decimal string'),
  DestinationOrganizationCode: nullable('Destination organization code'),
  DestinationOrganizationName: nullable('Destination organization name'),
} satisfies Record<string, OutputProperty>

export const oracleFusionScmShipmentOutputProperties = {
  shipmentKey: key('Opaque Oracle shipment resource key'),
  DeliveryId: nullable('Delivery identifier as a decimal string'),
  Shipment: nullable('Shipment number'),
  ShipmentDescription: nullable('Shipment description'),
  ShipmentStatus: nullable('Shipment status'),
  ShipmentStatusCode: nullable('Shipment status code'),
  OrganizationId: nullable('Organization identifier as a decimal string'),
  OrganizationCode: nullable('Organization code'),
  OrganizationName: nullable('Organization name'),
  InitialPickupDate: nullable('Initial pickup date'),
  ActualShipDate: nullable('Actual ship date'),
  ActualShipDateTime: nullable('Actual shipment timestamp'),
  ActualDeliveryDate: nullable('Actual delivery date'),
  Carrier: nullable('Carrier'),
  ShippingMethod: nullable('Shipping method'),
  ServiceLevel: nullable('Service level'),
  ModeOfTransport: nullable('Mode of transport'),
  BillOfLading: nullable('Bill of lading'),
  Waybill: nullable('Waybill'),
  GrossWeight: nullable('Gross weight', 'number'),
  NetWeight: nullable('Net weight', 'number'),
  WeightUOMCode: nullable('Weight unit-of-measure code'),
  Volume: nullable('Shipment volume', 'number'),
  VolumeUOMCode: nullable('Volume unit-of-measure code'),
  ShipToCustomer: nullable('Ship-to customer'),
  ShipToCustomerNumber: nullable('Ship-to customer number'),
  ShipToLocation: nullable('Ship-to location'),
  OpenExceptionSeverity: nullable('Highest open exception severity'),
  LastUpdateDate: nullable('Last update timestamp'),
} satisfies Record<string, OutputProperty>

export const oracleFusionScmShipmentLineOutputProperties = {
  shipmentLineKey: key('Opaque Oracle shipment-line resource key'),
  ShipmentLine: nullable('Shipment line identifier as a decimal string'),
  Shipment: nullable('Shipment number'),
  ShipmentId: nullable('Shipment identifier as a decimal string'),
  OrderTypeCode: nullable('Order type code'),
  OrderType: nullable('Order type'),
  Order: nullable('Order number'),
  OrderLine: nullable('Order line'),
  OrderSchedule: nullable('Order schedule'),
  SourceOrder: nullable('Source order'),
  SourceOrderLine: nullable('Source order line'),
  SourceOrderFulfillmentLine: nullable('Source order fulfillment line'),
  SourceOrderFulfillmentLineId: nullable('Fulfillment line identifier as a decimal string'),
  InventoryItemId: nullable('Inventory item identifier as a decimal string'),
  Item: nullable('Item number or name'),
  ItemDescription: nullable('Item description'),
  Revision: nullable('Item revision'),
  OrganizationId: nullable('Organization identifier as a decimal string'),
  OrganizationCode: nullable('Organization code'),
  OrganizationName: nullable('Organization name'),
  SourceSubinventory: nullable('Source subinventory'),
  DestinationOrganizationCode: nullable('Destination organization code'),
  DestinationSubinventory: nullable('Destination subinventory'),
  RequestedQuantity: nullable('Requested quantity', 'number'),
  RequestedQuantityUOMCode: nullable('Requested quantity unit-of-measure code'),
  PendingQuantity: nullable('Pending quantity', 'number'),
  PickedQuantity: nullable('Picked quantity', 'number'),
  StagedQuantity: nullable('Staged quantity', 'number'),
  ShippedQuantity: nullable('Shipped quantity', 'number'),
  DeliveredQuantity: nullable('Delivered quantity', 'number'),
  BackorderedQuantity: nullable('Backordered quantity', 'number'),
  CancelledQuantity: nullable('Cancelled quantity', 'number'),
  LineStatus: nullable('Shipment line status'),
  LineStatusCode: nullable('Shipment line status code'),
  ScheduledShipDate: nullable('Scheduled ship date'),
  IntegrationStatus: nullable('Integration status'),
  IntegrationStatusCode: nullable('Integration status code'),
  LastUpdateDate: nullable('Last update timestamp'),
} satisfies Record<string, OutputProperty>

export const oracleFusionScmManufacturingWorkOrderOutputProperties = {
  manufacturingWorkOrderKey: key('Opaque Oracle manufacturing-work-order resource key'),
  WorkOrderId: nullable('Work order identifier as a decimal string'),
  WorkOrderNumber: nullable('Work order number'),
  WorkOrderDescription: nullable('Work order description'),
  WorkOrderStatusId: nullable('Work order status identifier as a decimal string'),
  WorkOrderStatusName: nullable('Work order status name'),
  WorkOrderStatusCode: nullable('Work order status code'),
  WorkOrderSystemStatusCode: nullable('System status code'),
  WorkOrderType: nullable('Work order type'),
  WorkOrderTypeDescription: nullable('Work order type description'),
  WorkOrderSubType: nullable('Work order subtype'),
  WorkOrderSubTypeDescription: nullable('Work order subtype description'),
  OrganizationId: nullable('Organization identifier as a decimal string'),
  OrganizationCode: nullable('Organization code'),
  OrganizationName: nullable('Organization name'),
  InventoryItemId: nullable('Inventory item identifier as a decimal string'),
  ItemNumber: nullable('Item number'),
  Description: nullable('Item description'),
  PlannedStartQuantity: nullable('Planned start quantity', 'number'),
  CompletedQuantity: nullable('Completed quantity', 'number'),
  ScrappedQuantity: nullable('Scrapped quantity', 'number'),
  RejectedQuantity: nullable('Rejected quantity', 'number'),
  UOMCode: nullable('Unit-of-measure code'),
  UnitOfMeasure: nullable('Unit of measure'),
  PlannedStartDate: nullable('Planned start date'),
  PlannedCompletionDate: nullable('Planned completion date'),
  ActualStartDate: nullable('Actual start date'),
  ActualCompletionDate: nullable('Actual completion date'),
  WorkDefinitionId: nullable('Work definition identifier as a decimal string'),
  WorkDefinitionCode: nullable('Work definition code'),
  WorkDefinitionName: nullable('Work definition name'),
  SerialTrackingFlag: nullable('Whether serial tracking is enabled', 'boolean'),
  SupplyType: nullable('Supply type'),
  LastUpdateDate: nullable('Last update timestamp'),
} satisfies Record<string, OutputProperty>

export const oracleFusionScmMaintenanceWorkOrderOutputProperties = {
  maintenanceWorkOrderKey: key('Opaque Oracle maintenance-work-order resource key'),
  WorkOrderId: nullable('Work order identifier as a decimal string'),
  WorkOrderNumber: nullable('Work order number'),
  WorkOrderDescription: nullable('Work order description'),
  WorkOrderStatus: nullable('Work order status'),
  WorkOrderStatusCode: nullable('Work order status code'),
  WorkOrderStatusId: nullable('Work order status identifier as a decimal string'),
  WorkOrderType: nullable('Work order type'),
  WorkOrderTypeCode: nullable('Work order type code'),
  WorkOrderSubType: nullable('Work order subtype'),
  WorkOrderSubTypeCode: nullable('Work order subtype code'),
  WorkOrderPriority: nullable('Work order priority', 'number'),
  OrganizationId: nullable('Organization identifier as a decimal string'),
  OrganizationCode: nullable('Organization code'),
  AssetId: nullable('Asset identifier as a decimal string'),
  AssetNumber: nullable('Asset number'),
  AssetDescription: nullable('Asset description'),
  InventoryItemId: nullable('Inventory item identifier as a decimal string'),
  ItemNumber: nullable('Item number'),
  ItemDescription: nullable('Item description'),
  PlannedStartQuantity: nullable('Planned start quantity', 'number'),
  UOMCode: nullable('Unit-of-measure code'),
  UnitOfMeasure: nullable('Unit of measure'),
  PlannedStartDate: nullable('Planned start date'),
  PlannedCompletionDate: nullable('Planned completion date'),
  ActualStartDate: nullable('Actual start date'),
  ActualCompletionDate: nullable('Actual completion date'),
  MntWorkDefinitionCode: nullable('Maintenance work definition code'),
  MntWorkDefinitionName: nullable('Maintenance work definition name'),
  MaintenanceProgramId: nullable('Maintenance program identifier as a decimal string'),
  MaintenanceProgramCode: nullable('Maintenance program code'),
  MaintenanceProgramName: nullable('Maintenance program name'),
  WarrantyRepairFlag: nullable('Whether the work is a warranty repair', 'boolean'),
  ReleasedDate: nullable('Release date'),
} satisfies Record<string, OutputProperty>

export const oracleFusionScmTransferOrderOutputProperties = {
  transferOrderKey: key('Opaque Oracle transfer order resource key'),
  HeaderId: nullable('Header Id as a decimal string'),
  HeaderNumber: nullable('Header Number'),
  Description: nullable('Description'),
  Status: nullable('Status'),
  SourceTypeLookup: nullable('Source Type Lookup'),
  SourceOfTransferOrder: nullable('Source Of Transfer Order'),
  BusinessUnitName: nullable('Business Unit Name'),
  OrderedDate: nullable('Ordered Date'),
  InterfaceStatus: nullable('Interface Status'),
  MessageText: nullable('Message Text'),
  TotalPrice: nullable('Total Price', 'number'),
  TotalTax: nullable('Total Tax', 'number'),
  TotalTransferPrice: nullable('Total Transfer Price', 'number'),
  LastUpdateDate: nullable('Last Update Date'),
} satisfies Record<string, OutputProperty>

export const oracleFusionScmTransferOrderLineOutputProperties = {
  transferOrderLineKey: key('Opaque Oracle transfer order line resource key'),
  HeaderId: nullable('Header Id as a decimal string'),
  HeaderNumber: nullable('Header Number'),
  LineId: nullable('Line Id as a decimal string'),
  LineNumber: nullable('Line Number as a decimal string'),
  ItemNumber: nullable('Item Number'),
  ItemDescription: nullable('Item Description'),
  InventoryItemId: nullable('Inventory Item Id as a decimal string'),
  TransferOrderLineStatus: nullable('Transfer Order Line Status'),
  StatusLookup: nullable('Status Lookup'),
  RequestedQuantity: nullable('Requested Quantity', 'number'),
  ShippedQuantity: nullable('Shipped Quantity', 'number'),
  ReceivedQuantity: nullable('Received Quantity', 'number'),
  DeliveredQuantity: nullable('Delivered Quantity', 'number'),
  UnshippedQuantity: nullable('Unshipped Quantity', 'number'),
  QuantityUOMCode: nullable('Quantity UOMCode'),
  NeedByDate: nullable('Need By Date'),
  ScheduledShipDate: nullable('Scheduled Ship Date'),
  SourceOrganizationId: nullable('Source Organization Id as a decimal string'),
  SourceOrganizationCode: nullable('Source Organization Code'),
  SourceSubinventoryCode: nullable('Source Subinventory Code'),
  DestinationOrganizationId: nullable('Destination Organization Id as a decimal string'),
  DestinationOrganizationCode: nullable('Destination Organization Code'),
  DestinationSubinventoryCode: nullable('Destination Subinventory Code'),
  Comments: nullable('Comments'),
  InterfaceErrMsgCode: nullable('Interface Err Msg Code'),
  InterfaceErrMsgText: nullable('Interface Err Msg Text'),
} satisfies Record<string, OutputProperty>

export const oracleFusionScmSalesOrderOutputProperties = {
  salesOrderKey: key('Opaque Oracle sales order resource key'),
  OrderKey: nullable('Order Key'),
  HeaderId: nullable('Header Id as a decimal string'),
  OrderNumber: nullable('Order Number'),
  BusinessUnitId: nullable('Business Unit Id as a decimal string'),
  BusinessUnitName: nullable('Business Unit Name'),
  SourceTransactionId: nullable('Source Transaction Id'),
  SourceTransactionNumber: nullable('Source Transaction Number'),
  SourceTransactionSystem: nullable('Source Transaction System'),
  SourceTransactionRevisionNumber: nullable(
    'Source Transaction Revision Number as a decimal string'
  ),
  BuyingPartyId: nullable('Buying Party Id as a decimal string'),
  BuyingPartyName: nullable('Buying Party Name'),
  CustomerPONumber: nullable('Customer PONumber'),
  Status: nullable('Status'),
  StatusCode: nullable('Status Code'),
  SubmittedFlag: nullable('Submitted Flag', 'boolean'),
  SubmittedDate: nullable('Submitted Date'),
  CanceledFlag: nullable('Canceled Flag', 'boolean'),
  OpenFlag: nullable('Open Flag', 'boolean'),
  OnHoldFlag: nullable('On Hold Flag', 'boolean'),
  TransactionOn: nullable('Transaction On'),
  TransactionalCurrencyCode: nullable('Transactional Currency Code'),
  RequestedShipDate: nullable('Requested Ship Date'),
  RequestedArrivalDate: nullable('Requested Arrival Date'),
  Comments: nullable('Comments'),
  LastUpdateDate: nullable('Last Update Date'),
} satisfies Record<string, OutputProperty>

export const oracleFusionScmSalesOrderLineOutputProperties = {
  salesOrderLineKey: key('Opaque Oracle sales order line resource key'),
  FulfillLineId: nullable('Fulfill Line Id as a decimal string'),
  LineId: nullable('Line Id as a decimal string'),
  HeaderId: nullable('Header Id as a decimal string'),
  LineNumber: nullable('Line Number as a decimal string'),
  FulfillLineNumber: nullable('Fulfill Line Number'),
  SourceTransactionLineId: nullable('Source Transaction Line Id'),
  SourceTransactionLineNumber: nullable('Source Transaction Line Number'),
  SourceTransactionScheduleId: nullable('Source Transaction Schedule Id'),
  SourceScheduleNumber: nullable('Source Schedule Number'),
  ProductId: nullable('Product Id as a decimal string'),
  ProductNumber: nullable('Product Number'),
  ProductDescription: nullable('Product Description'),
  OrderedQuantity: nullable('Ordered Quantity', 'number'),
  OrderedUOMCode: nullable('Ordered UOMCode'),
  FulfilledQuantity: nullable('Fulfilled Quantity', 'number'),
  CanceledQuantity: nullable('Canceled Quantity', 'number'),
  ShippedQuantity: nullable('Shipped Quantity', 'number'),
  Status: nullable('Status'),
  StatusCode: nullable('Status Code'),
  ScheduleShipDate: nullable('Schedule Ship Date'),
  ScheduleArrivalDate: nullable('Schedule Arrival Date'),
  ActualShipDate: nullable('Actual Ship Date'),
  CanceledFlag: nullable('Canceled Flag', 'boolean'),
  OpenFlag: nullable('Open Flag', 'boolean'),
  OnHoldFlag: nullable('On Hold Flag', 'boolean'),
  LastUpdateDate: nullable('Last Update Date'),
} satisfies Record<string, OutputProperty>

export const oracleFusionScmFulfillmentLineDetailOutputProperties = {
  fulfillmentLineDetailKey: key('Opaque Oracle fulfillment line detail resource key'),
  FulfillLineDetailId: nullable('Fulfill Line Detail Id as a decimal string'),
  TaskType: nullable('Task Type'),
  Status: nullable('Status'),
  StatusCode: nullable('Status Code'),
  StatusAsOfDate: nullable('Status As Of Date'),
  Quantity: nullable('Quantity', 'number'),
  SecondaryQuantity: nullable('Secondary Quantity', 'number'),
  DeliveryName: nullable('Delivery Name'),
  ActualDeliveryDate: nullable('Actual Delivery Date'),
  TrackingNumber: nullable('Tracking Number'),
  WaybillNumber: nullable('Waybill Number'),
  BillOfLadingNumber: nullable('Bill Of Lading Number'),
  BillingTransactionNumber: nullable('Billing Transaction Number'),
  BillingTransactionDate: nullable('Billing Transaction Date'),
  BillingTransactionAmount: nullable('Billing Transaction Amount', 'number'),
  ExceptionFlag: nullable('Exception Flag', 'boolean'),
  TradeComplianceResultCode: nullable('Trade Compliance Result Code'),
} satisfies Record<string, OutputProperty>

export const oracleFusionScmResourceOutputProperties = {
  fulfillmentLineDetails: oracleFusionScmFulfillmentLineDetailOutputProperties,
  salesOrderLines: oracleFusionScmSalesOrderLineOutputProperties,
  salesOrders: oracleFusionScmSalesOrderOutputProperties,
  transferOrderLines: oracleFusionScmTransferOrderLineOutputProperties,
  transferOrders: oracleFusionScmTransferOrderOutputProperties,
  inventoryOrganizations: oracleFusionScmInventoryOrganizationOutputProperties,
  items: oracleFusionScmItemOutputProperties,
  onHandQuantities: oracleFusionScmOnHandQuantityOutputProperties,
  inventoryTransactions: oracleFusionScmInventoryTransactionOutputProperties,
  supplyRequests: oracleFusionScmSupplyRequestOutputProperties,
  supplyOrderLines: oracleFusionScmSupplyOrderLineOutputProperties,
  shipments: oracleFusionScmShipmentOutputProperties,
  shipmentLines: oracleFusionScmShipmentLineOutputProperties,
  manufacturingWorkOrders: oracleFusionScmManufacturingWorkOrderOutputProperties,
  maintenanceWorkOrders: oracleFusionScmMaintenanceWorkOrderOutputProperties,
} as const

export const oracleFusionScmPaginationOutputProperties = {
  count: { type: 'number', description: 'Number of records in this page' },
  hasMore: { type: 'boolean', description: 'Whether Oracle has another page' },
  limit: { type: 'number', description: 'Page size returned by Oracle' },
  offset: { type: 'number', description: 'Offset returned by Oracle' },
  totalResults: {
    type: 'number',
    description: 'Estimated total matching records when Oracle provides it',
    optional: true,
  },
  nextOffset: {
    type: 'number',
    description: 'Offset to use for the next page when one exists',
    optional: true,
  },
} satisfies Record<string, OutputProperty>
