/**
 * Telegram Polling Trigger
 * Generated by Universal Integrator v8
 */

import { TriggerConfig } from '@sim/workflow-types';

export const telegramPollingTrigger: TriggerConfig = {
  id: 'telegram_polling',
  name: 'Polling',
  type: 'polling',
  description: 'Poll for Telegram updates using getUpdates',

  outputs: {
    update_id: { type: 'number' },
    message_id: { type: 'number', optional: true },
    chat_id: { type: 'string', optional: true },
    text: { type: 'string', optional: true },
    from_id: { type: 'number', optional: true },
  },

  formatInput: (payload: any) => ({
    update_id: payload.update_id,
    message_id: payload.message?.message_id ?? null,
    chat_id: String(payload.message?.chat?.id) ?? null,
    text: payload.message?.text ?? null,
    from_id: payload.message?.from?.id ?? null,
  }),
};
