/**
 * Telegram Webhook Trigger
 * Generated by Universal Integrator v8
 */

import { TriggerConfig } from '@sim/workflow-types';

export const telegramWebhookTrigger: TriggerConfig = {
  id: 'telegram_webhook',
  name: 'Webhook',
  type: 'webhook',
  description: 'Receive Telegram updates via webhook',
  includeDropdown: true,
  method: 'POST',
  path: '/webhook/telegram/{botId}/{workspaceId}',

  outputs: {
    update_id: { type: 'number', description: 'Unique update ID' },
    message_id: { type: 'number', optional: true, description: 'Message ID' },
    chat_id: { type: 'string', optional: true, description: 'Chat ID' },
    from_id: { type: 'number', optional: true, description: 'Sender user ID' },
    text: { type: 'string', optional: true, description: 'Message text' },
    timestamp: { type: 'number', optional: true, description: 'Message timestamp' },
  },

  formatInput: (payload: any) => ({
    update_id: payload.update_id,
    message_id: payload.message?.message_id ?? null,
    chat_id: String(payload.message?.chat?.id) ?? null,
    from_id: payload.message?.from?.id ?? null,
    text: payload.message?.text ?? null,
    timestamp: payload.message?.date ?? null,
  }),
};

export const telegramMessageTrigger: TriggerConfig = {
  id: 'telegram_message',
  name: 'Message',
  type: 'webhook',
  description: 'When a message is received',
  method: 'POST',
  path: '/webhook/telegram/{botId}/{workspaceId}',

  outputs: {
    message_id: { type: 'number' },
    chat_id: { type: 'string' },
    text: { type: 'string' },
    from_id: { type: 'number' },
    from_name: { type: 'string', optional: true },
  },

  formatInput: (payload: any) => {
    const message = payload.message;
    if (!message) return null;
    
    return {
      message_id: message.message_id,
      chat_id: String(message.chat.id),
      text: message.text,
      from_id: message.from?.id,
      from_name: message.from?.first_name ?? null,
    };
  },
};

export const telegramCommandTrigger: TriggerConfig = {
  id: 'telegram_command',
  name: 'Command',
  type: 'webhook',
  description: 'When a /command is received',
  method: 'POST',
  path: '/webhook/telegram/{botId}/{workspaceId}',

  outputs: {
    command: { type: 'string', description: 'Command name (without /)' },
    chat_id: { type: 'string' },
    from_id: { type: 'number' },
    args: { type: 'string', optional: true, description: 'Command arguments' },
  },

  formatInput: (payload: any) => {
    const text = payload.message?.text;
    if (!text?.startsWith('/')) return null;
    
    const [command, ...args] = text.slice(1).split(' ');
    return {
      command,
      chat_id: String(payload.message.chat.id),
      from_id: payload.message.from?.id,
      args: args.join(' ') ?? null,
    };
  },
};
