{{- if .Values.app.enabled }}
---
# Service for main application
apiVersion: v1
kind: Service
metadata:
  name: {{ include "simstudio.fullname" . }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simstudio.app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "simstudio.app.selectorLabels" . | nindent 4 }}
{{- end }}

{{- if .Values.realtime.enabled }}
---
# Service for realtime server
apiVersion: v1
kind: Service
metadata:
  name: {{ include "simstudio.fullname" . }}-realtime
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simstudio.realtime.labels" . | nindent 4 }}
spec:
  type: {{ .Values.realtime.service.type }}
  ports:
    - port: {{ .Values.realtime.service.port }}
      targetPort: {{ .Values.realtime.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "simstudio.realtime.selectorLabels" . | nindent 4 }}
{{- end }}

{{- if .Values.postgresql.enabled }}
---
# Service for PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: {{ include "simstudio.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simstudio.postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.targetPort }}
      protocol: TCP
      name: postgresql
  selector:
    {{- include "simstudio.postgresql.selectorLabels" . | nindent 4 }}
{{- end }}

{{- if .Values.ollama.enabled }}
---
# Service for Ollama
apiVersion: v1
kind: Service
metadata:
  name: {{ include "simstudio.fullname" . }}-ollama
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simstudio.ollama.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ollama.service.type }}
  ports:
    - port: {{ .Values.ollama.service.port }}
      targetPort: {{ .Values.ollama.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "simstudio.ollama.selectorLabels" . | nindent 4 }}
{{- end }}