{{- if .Values.sharedStorage.enabled }}
{{- range .Values.sharedStorage.volumes }}
---
# Shared Storage PVC for {{ .name }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sim.fullname" $ }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "sim.labels" $ | nindent 4 }}
    sim.ai/volume-type: shared-storage
    sim.ai/volume-name: {{ .name }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .storageClass }}
  {{- if (eq "-" .storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .storageClass | quote }}
  {{- end }}
  {{- else if $.Values.sharedStorage.storageClass }}
  storageClassName: {{ $.Values.sharedStorage.storageClass | quote }}
  {{- else if $.Values.global.storageClass }}
  storageClassName: {{ $.Values.global.storageClass | quote }}
  {{- end }}
  accessModes:
    {{- if .accessModes }}
    {{- range .accessModes }}
    - {{ . | quote }}
    {{- end }}
    {{- else }}
    {{- range $.Values.sharedStorage.defaultAccessModes }}
    - {{ . | quote }}
    {{- end }}
    {{- end }}
  resources:
    requests:
      storage: {{ .size | quote }}
  {{- if .selector }}
  selector:
    {{- toYaml .selector | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}