export const ACCESS_REQUEST_LIST_PAGE_SIZE = 25
export const ACCESS_REQUEST_MAX_OFFSET = 1_000_000
export const ACCESS_REQUEST_MAX_SEARCH_LENGTH = 200
export const ACCESS_REQUEST_MAX_ID_LENGTH = 128
export const ACCESS_REQUEST_MAX_DAILY_SUBMISSIONS = 100
export const ACCESS_REQUEST_MAX_PENDING = 100
export const ACCESS_REQUEST_SUBMISSION_WINDOW_MS = 24 * 60 * 60 * 1000
