/**
 * Telegram Updates & Webhook Tools
 * Generated by Universal Integrator v8
 */

import { ToolConfig } from '@sim/workflow-types';

export const telegramGetUpdatesTool: ToolConfig = {
  id: 'telegram_get_updates',
  name: 'Get Updates',
  description: 'Receive incoming updates (polling)',
  version: '1.0.0',
  params: {
    botToken: {
      type: 'string',
      required: true,
      visibility: 'hidden',
    },
    offset: {
      type: 'number',
      required: false,
      visibility: 'user-or-llm',
      description: 'Update offset for pagination',
    },
    limit: {
      type: 'number',
      required: false,
      visibility: 'user-or-llm',
      description: 'Max updates to return (1-100)',
    },
    timeout: {
      type: 'number',
      required: false,
      visibility: 'user-or-llm',
      description: 'Long polling timeout in seconds',
    },
  },
  outputs: {
    success: { type: 'boolean' },
    updates: {
      type: 'array',
      optional: true,
      description: 'Array of updates',
    },
    error: { type: 'string', optional: true },
  },
  request: {
    url: () => 'https://api.telegram.org/bot{botToken}/getUpdates',
    method: () => 'POST',
    body: (params) => ({
      offset: params.offset ?? null,
      limit: params.limit ?? 100,
      timeout: params.timeout ?? 0,
    }),
  },
  transformResponse: (response) => ({
    success: response.ok === true,
    updates: response.result ?? null,
    error: response.ok === false ? response.description : null,
  }),
};

export const telegramSetWebhookTool: ToolConfig = {
  id: 'telegram_set_webhook',
  name: 'Set Webhook',
  description: 'Set webhook URL for receiving updates',
  version: '1.0.0',
  params: {
    botToken: {
      type: 'string',
      required: true,
      visibility: 'hidden',
    },
    url: {
      type: 'string',
      required: true,
      visibility: 'user-only',
      description: 'Webhook HTTPS URL',
    },
    max_connections: {
      type: 'number',
      required: false,
      visibility: 'user-or-llm',
      description: 'Max concurrent connections',
    },
  },
  outputs: {
    success: { type: 'boolean' },
    description: { type: 'string', optional: true },
    error: { type: 'string', optional: true },
  },
  request: {
    url: () => 'https://api.telegram.org/bot{botToken}/setWebhook',
    method: () => 'POST',
    body: (params) => ({
      url: params.url,
      max_connections: params.max_connections ?? 40,
    }),
  },
  transformResponse: (response) => ({
    success: response.ok === true,
    description: response.description ?? null,
    error: response.ok === false ? response.description : null,
  }),
};
