/**
 * Telegram Message Tools
 * Generated by Universal Integrator v8
 */

import { ToolConfig } from '@sim/workflow-types';

export const telegramSendMessageTool: ToolConfig = {
  id: 'telegram_send_message',
  name: 'Send Message',
  description: 'Send a text message to a Telegram chat',
  version: '1.0.0',
  params: {
    botToken: {
      type: 'string',
      required: true,
      visibility: 'hidden',
      description: 'Telegram Bot Token',
    },
    chat_id: {
      type: 'string',
      required: true,
      visibility: 'user-or-llm',
      description: 'Chat ID to send message to',
    },
    text: {
      type: 'string',
      required: true,
      visibility: 'user-or-llm',
      description: 'Message text',
    },
    parse_mode: {
      type: 'string',
      required: false,
      visibility: 'user-or-llm',
      description: 'HTML, Markdown, or MarkdownV2',
    },
  },
  outputs: {
    success: { type: 'boolean', description: 'Was message sent' },
    message_id: { type: 'number', optional: true, description: 'Sent message ID' },
    error: { type: 'string', optional: true, description: 'Error message if failed' },
  },
  request: {
    url: () => 'https://api.telegram.org/bot{botToken}/sendMessage',
    method: () => 'POST',
    body: (params) => ({
      chat_id: params.chat_id,
      text: params.text,
      parse_mode: params.parse_mode ?? null,
    }),
  },
  transformResponse: (response) => ({
    success: response.ok === true,
    message_id: response.result?.message_id ?? null,
    error: response.ok === false ? response.description : null,
  }),
};

export const telegramSendPhotoTool: ToolConfig = {
  id: 'telegram_send_photo',
  name: 'Send Photo',
  description: 'Send a photo to a Telegram chat',
  version: '1.0.0',
  params: {
    botToken: {
      type: 'string',
      required: true,
      visibility: 'hidden',
    },
    chat_id: {
      type: 'string',
      required: true,
      visibility: 'user-or-llm',
      description: 'Chat ID',
    },
    photo: {
      type: 'string',
      required: true,
      visibility: 'user-or-llm',
      description: 'Photo file ID or URL',
    },
    caption: {
      type: 'string',
      required: false,
      visibility: 'user-or-llm',
      description: 'Photo caption',
    },
  },
  outputs: {
    success: { type: 'boolean' },
    message_id: { type: 'number', optional: true },
    photo_id: { type: 'string', optional: true },
    error: { type: 'string', optional: true },
  },
  request: {
    url: () => 'https://api.telegram.org/bot{botToken}/sendPhoto',
    method: () => 'POST',
    body: (params) => ({
      chat_id: params.chat_id,
      photo: params.photo,
      caption: params.caption ?? null,
    }),
  },
  transformResponse: (response) => ({
    success: response.ok === true,
    message_id: response.result?.message_id ?? null,
    photo_id: response.result?.photo?.[0]?.file_id ?? null,
    error: response.ok === false ? response.description : null,
  }),
};
