/** Generated by scripts/generate-hero-artwork.ts. */
export const HERO_ARTWORK = {
  avifSrcSet:
    '/landing/hero-artwork/painting-1080-edb05d03330a.avif 1080w, /landing/hero-artwork/painting-1200-a6f578eae83e.avif 1200w, /landing/hero-artwork/painting-1920-35eadaf0cdee.avif 1920w, /landing/hero-artwork/painting-2048-8538288166d3.avif 2048w, /landing/hero-artwork/painting-3840-d6e7c3f5943d.avif 3840w',
  webpSrcSet:
    '/landing/hero-artwork/painting-1080-2ccdfef92b36.webp 1080w, /landing/hero-artwork/painting-1200-04e474a8546d.webp 1200w, /landing/hero-artwork/painting-1920-c7a1fa74f312.webp 1920w, /landing/hero-artwork/painting-2048-6a414066a1fd.webp 2048w, /landing/hero-artwork/painting-3840-55734e1694fb.webp 3840w',
  src: '/landing/hero-artwork/painting-3840-55734e1694fb.webp',
} as const
