import type { ToolConfig } from '@/tools/types'

export const ociResourceManagerParams = {
  oauthCredential: {
    type: 'string',
    required: false,
    visibility: 'user-only',
    description: 'Reusable OCI API-key service-account credential ID',
  },
  region: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'OCI region; omit to use the credential region',
  },
  compartmentId: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'Compartment OCID; destination compartment when moving a stack',
  },
  stackId: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'Stack OCID',
  },
  jobId: { type: 'string', required: false, visibility: 'user-or-llm', description: 'Job OCID' },
  workRequestId: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'Work-request OCID',
  },
  displayName: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'Display name; exact match for list operations',
  },
  description: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'Stack description, at most 400 characters',
  },
  id: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'Exact resource OCID filter',
  },
  lifecycleState: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'Documented stack or job lifecycle state filter',
  },
  limit: {
    type: 'number',
    required: false,
    visibility: 'user-or-llm',
    description: 'Page size, 1–1000; default 50. Returns one page only',
  },
  page: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'Opaque nextPage token, at most 512 characters',
  },
  sortBy: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'TIMECREATED or DISPLAYNAME',
  },
  sortOrder: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'ASC or DESC',
  },
  configSource: {
    type: 'json',
    required: false,
    visibility: 'user-or-llm',
    description:
      'Configuration source object: configSourceType plus workingDirectory and variant fields. ZIP_UPLOAD takes the separate file input; GIT_CONFIG_SOURCE takes configurationSourceProviderId, repositoryUrl, branchName; BITBUCKET_CLOUD_CONFIG_SOURCE also takes Bitbucket workspaceId; BITBUCKET_SERVER_CONFIG_SOURCE supports projectId/repositoryId; DEVOPS_CONFIG_SOURCE takes projectId/repositoryId; OBJECT_STORAGE_CONFIG_SOURCE takes region/namespace/bucketName; TEMPLATE_CONFIG_SOURCE takes templateId; COMPARTMENT_CONFIG_SOURCE takes compartmentId/region/servicesToDiscover. Template and compartment sources are create-only.',
  },
  file: {
    type: 'file',
    required: false,
    visibility: 'user-or-llm',
    description:
      'One authorized uploaded ZIP configuration or Terraform state file; no inline base64 or arbitrary URL',
  },
  variables: {
    type: 'json',
    required: false,
    visibility: 'user-or-llm',
    description:
      'Terraform variable string map; up to 250 entries and 8192 UTF-8 bytes per name plus value. Omit to leave variables unchanged; removal/merge semantics are not promised',
  },
  freeformTags: {
    type: 'json',
    required: false,
    visibility: 'user-or-llm',
    description: 'Free-form tag string map',
  },
  definedTags: {
    type: 'json',
    required: false,
    visibility: 'user-or-llm',
    description: 'Defined tags: namespace to string-valued tag map',
  },
  terraformVersion: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'Supported Terraform version returned by List Terraform Versions',
  },
  customTerraformProvider: {
    type: 'json',
    required: false,
    visibility: 'user-or-llm',
    description: 'Custom provider bucket coordinates: region, namespace, bucketName',
  },
  isThirdPartyProviderExperienceEnabled: {
    type: 'boolean',
    required: false,
    visibility: 'user-or-llm',
    description:
      'Set true to migrate an older stack to Terraform Registry sourcing; cannot be reverted',
  },
  ifMatch: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'Resource ETag for a conditional mutation',
  },
  retryToken: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description:
      'Optional stable token enabling at most two transport attempts. Reuse only for the identical logical request; Oracle tokens expire after 24 hours or earlier invalidation. Not a block-retry guarantee',
  },
  confirmDelete: {
    type: 'boolean',
    required: false,
    visibility: 'user-or-llm',
    description: 'Must be true: delete the stack and its state file; deployed resources persist',
  },
  confirmApply: {
    type: 'boolean',
    required: false,
    visibility: 'user-or-llm',
    description: 'Must be true to explicitly authorize applying infrastructure changes',
  },
  confirmDestroy: {
    type: 'boolean',
    required: false,
    visibility: 'user-or-llm',
    description:
      'Must be true to destroy the stack resources; Oracle does not support a reviewed destroy-plan strategy',
  },
  confirmStateReplacement: {
    type: 'boolean',
    required: false,
    visibility: 'user-or-llm',
    description: 'Must be true to explicitly authorize importing replacement Terraform state',
  },
  confirmForce: {
    type: 'boolean',
    required: false,
    visibility: 'user-or-llm',
    description: 'Must be true with forced cancellation; interruption can leave inconsistent state',
  },
  isForced: {
    type: 'boolean',
    required: false,
    visibility: 'user-or-llm',
    description: 'Request forced cancellation; default false. Requires confirmForce',
  },
  isProviderUpgradeRequired: {
    type: 'boolean',
    required: false,
    visibility: 'user-or-llm',
    description: 'Upgrade providers within configured version constraints; default false',
  },
  terraformAdvancedOptions: {
    type: 'json',
    required: false,
    visibility: 'user-or-llm',
    description:
      'Optional Terraform settings: isRefreshRequired, parallelism (1–1000), detailedLogLevel (ERROR/WARN/INFO/DEBUG/TRACE). Debug logs can contain sensitive material',
  },
  executionPlanStrategy: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'FROM_PLAN_JOB_ID for a reviewed plan, or explicitly selected AUTO_APPROVED',
  },
  executionPlanJobId: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'Successful PLAN job OCID from the same stack; required for FROM_PLAN_JOB_ID',
  },
  targetRollbackJobId: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'Successful APPLY job OCID from the same stack to plan rollback toward',
  },
  executionPlanRollbackJobId: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'Successful PLAN_ROLLBACK job OCID from the same stack',
  },
  includeVariables: {
    type: 'boolean',
    required: false,
    visibility: 'user-or-llm',
    description: 'Explicitly reveal only selected variableNames; values can contain secrets',
  },
  variableNames: {
    type: 'json',
    required: false,
    visibility: 'user-or-llm',
    description: 'Array of variable names to reveal; required when includeVariables is true',
  },
  includeSource: {
    type: 'boolean',
    required: false,
    visibility: 'user-or-llm',
    description: 'Include documented source metadata; excludes configuration file contents',
  },
  includeValues: {
    type: 'boolean',
    required: false,
    visibility: 'user-or-llm',
    description: 'Explicitly reveal selected outputNames; default metadata only',
  },
  outputNames: {
    type: 'json',
    required: false,
    visibility: 'user-or-llm',
    description: 'Array of output names to reveal',
  },
  includeSensitive: {
    type: 'boolean',
    required: false,
    visibility: 'user-or-llm',
    description:
      'Also reveal selected outputs marked sensitive or with unknown sensitivity. False is not a guarantee that other values contain no secrets',
  },
  includeMessages: {
    type: 'boolean',
    required: false,
    visibility: 'user-or-llm',
    description: 'Include bounded log/error messages; can contain secrets. Default metadata only',
  },
  includeAttributes: {
    type: 'boolean',
    required: false,
    visibility: 'user-or-llm',
    description: 'Include resource attributes; can contain secrets',
  },
  includeProperties: {
    type: 'boolean',
    required: false,
    visibility: 'user-or-llm',
    description: 'Include actual/expected drift property maps; can contain secrets',
  },
  scope: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'stack or job; supply only its matching ID',
  },
  kind: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description:
      'Log kind: console/detailed for job downloads, service/terraform for work-request logs',
  },
  outputMode: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description:
      'entries (default) or file; file is supported only for Terraform work-request logs',
  },
  tfPlanFormat: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'BINARY (default) or JSON; both returned as a stored file',
  },
  type: {
    type: 'json',
    required: false,
    visibility: 'user-or-llm',
    description: 'Array containing TERRAFORM_CONSOLE to filter log type',
  },
  levelGreaterThanOrEqualTo: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'Minimum log severity: TRACE, DEBUG, INFO, WARN, ERROR, FATAL',
  },
  timestampGreaterThanOrEqualTo: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'Inclusive RFC 3339 start timestamp',
  },
  timestampLessThanOrEqualTo: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'Inclusive RFC 3339 end timestamp',
  },
  resourceAddresses: {
    type: 'json',
    required: false,
    visibility: 'user-or-llm',
    description: 'Optional array of Terraform resource addresses to check for drift',
  },
  resourceDriftStatus: {
    type: 'json',
    required: false,
    visibility: 'user-or-llm',
    description: 'Array of NOT_CHECKED, IN_SYNC, MODIFIED, or DELETED filters',
  },
  resourceId: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'Resource OCID filter',
  },
  terraformResourceType: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'Terraform resource type filter',
  },
  configurationSourceProviderId: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'Existing configuration-source-provider OCID filter',
  },
  configSourceProviderType: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description:
      'GITHUB_ACCESS_TOKEN, GITLAB_ACCESS_TOKEN, BITBUCKET_CLOUD_ACCESS_TOKEN, or BITBUCKET_SERVER_ACCESS_TOKEN',
  },
  templateId: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'Existing template OCID filter',
  },
  templateCategoryId: {
    type: 'string',
    required: false,
    visibility: 'user-or-llm',
    description: 'Template category identifier filter',
  },
} satisfies ToolConfig['params']

export const OCI_RESOURCE_MANAGER_OPERATION_PARAMS = {
  list_stacks: [
    'compartmentId',
    'limit',
    'page',
    'sortBy',
    'sortOrder',
    'displayName',
    'id',
    'lifecycleState',
  ],
  get_stack: ['stackId', 'includeVariables', 'variableNames', 'includeSource'],
  create_stack: [
    'compartmentId',
    'configSource',
    'displayName',
    'description',
    'variables',
    'terraformVersion',
    'customTerraformProvider',
    'freeformTags',
    'definedTags',
    'file',
    'retryToken',
  ],
  update_stack: [
    'stackId',
    'displayName',
    'description',
    'variables',
    'terraformVersion',
    'customTerraformProvider',
    'freeformTags',
    'definedTags',
    'configSource',
    'file',
    'ifMatch',
    'isThirdPartyProviderExperienceEnabled',
  ],
  delete_stack: ['stackId', 'confirmDelete', 'ifMatch'],
  change_stack_compartment: ['stackId', 'compartmentId', 'ifMatch', 'retryToken'],
  list_jobs: [
    'stackId',
    'limit',
    'page',
    'sortBy',
    'sortOrder',
    'displayName',
    'id',
    'lifecycleState',
    'compartmentId',
  ],
  get_job: ['jobId', 'includeVariables', 'variableNames', 'includeSource'],
  update_job: ['jobId', 'displayName', 'freeformTags', 'definedTags', 'ifMatch'],
  plan: [
    'stackId',
    'displayName',
    'freeformTags',
    'definedTags',
    'retryToken',
    'isProviderUpgradeRequired',
    'terraformAdvancedOptions',
  ],
  apply: [
    'stackId',
    'executionPlanStrategy',
    'confirmApply',
    'displayName',
    'freeformTags',
    'definedTags',
    'retryToken',
    'isProviderUpgradeRequired',
    'terraformAdvancedOptions',
    'executionPlanJobId',
  ],
  destroy: [
    'stackId',
    'confirmDestroy',
    'displayName',
    'freeformTags',
    'definedTags',
    'retryToken',
    'isProviderUpgradeRequired',
    'terraformAdvancedOptions',
  ],
  import_state: [
    'stackId',
    'file',
    'confirmStateReplacement',
    'displayName',
    'freeformTags',
    'definedTags',
    'retryToken',
    'isProviderUpgradeRequired',
  ],
  plan_rollback: [
    'stackId',
    'targetRollbackJobId',
    'displayName',
    'freeformTags',
    'definedTags',
    'retryToken',
    'isProviderUpgradeRequired',
    'terraformAdvancedOptions',
  ],
  apply_rollback: [
    'stackId',
    'executionPlanRollbackJobId',
    'confirmApply',
    'displayName',
    'freeformTags',
    'definedTags',
    'retryToken',
    'isProviderUpgradeRequired',
    'terraformAdvancedOptions',
  ],
  cancel_job: ['jobId', 'ifMatch', 'isForced', 'confirmForce'],
  get_job_logs: [
    'jobId',
    'limit',
    'page',
    'type',
    'levelGreaterThanOrEqualTo',
    'sortOrder',
    'timestampGreaterThanOrEqualTo',
    'timestampLessThanOrEqualTo',
    'includeMessages',
  ],
  download_job_logs: ['jobId', 'kind'],
  download_configuration: ['scope', 'stackId', 'jobId'],
  download_state: ['scope', 'stackId', 'jobId'],
  download_plan: ['jobId', 'tfPlanFormat'],
  list_job_outputs: [
    'jobId',
    'limit',
    'page',
    'compartmentId',
    'includeValues',
    'outputNames',
    'includeSensitive',
  ],
  list_associated_resources: [
    'scope',
    'stackId',
    'jobId',
    'compartmentId',
    'terraformResourceType',
    'limit',
    'page',
    'includeAttributes',
  ],
  detect_drift: [
    'stackId',
    'ifMatch',
    'retryToken',
    'resourceAddresses',
    'isProviderUpgradeRequired',
  ],
  list_drift_details: [
    'stackId',
    'limit',
    'page',
    'workRequestId',
    'resourceDriftStatus',
    'includeProperties',
  ],
  list_work_requests: ['compartmentId', 'limit', 'page', 'resourceId'],
  get_work_request: ['workRequestId'],
  list_work_request_errors: [
    'workRequestId',
    'limit',
    'page',
    'compartmentId',
    'sortOrder',
    'includeMessages',
  ],
  get_work_request_logs: [
    'workRequestId',
    'kind',
    'limit',
    'page',
    'type',
    'levelGreaterThanOrEqualTo',
    'sortOrder',
    'timestampGreaterThanOrEqualTo',
    'timestampLessThanOrEqualTo',
    'compartmentId',
    'includeMessages',
    'outputMode',
  ],
  list_terraform_versions: ['compartmentId'],
  list_configuration_source_providers: [
    'compartmentId',
    'limit',
    'page',
    'sortBy',
    'sortOrder',
    'displayName',
    'configurationSourceProviderId',
    'configSourceProviderType',
  ],
  list_templates: [
    'limit',
    'page',
    'sortBy',
    'sortOrder',
    'compartmentId',
    'displayName',
    'templateCategoryId',
    'templateId',
  ],
  list_resource_discovery_services: ['compartmentId'],
} as const
