import { functionExecuteTool } from '@/tools/function'
import {
  gmailAddLabelV2Tool,
  gmailArchiveV2Tool,
  gmailCreateLabelV2Tool,
  gmailDeleteDraftV2Tool,
  gmailDeleteLabelV2Tool,
  gmailDeleteV2Tool,
  gmailDraftV2Tool,
  gmailEditDraftV2Tool,
  gmailGetDraftV2Tool,
  gmailGetThreadV2Tool,
  gmailListDraftsV2Tool,
  gmailListLabelsV2Tool,
  gmailListThreadsV2Tool,
  gmailMarkReadV2Tool,
  gmailMarkUnreadV2Tool,
  gmailMoveV2Tool,
  gmailReadV2Tool,
  gmailRemoveLabelV2Tool,
  gmailSearchV2Tool,
  gmailSendV2Tool,
  gmailTrashThreadV2Tool,
  gmailUnarchiveV2Tool,
  gmailUntrashThreadV2Tool,
  gmailUpdateLabelV2Tool,
} from '@/tools/gmail'
import { guardrailsValidateTool } from '@/tools/guardrails'
import { httpRequestTool } from '@/tools/http'
import {
  slackAddReactionTool,
  slackArchiveConversationTool,
  slackCanvasTool,
  slackCreateChannelCanvasTool,
  slackCreateConversationTool,
  slackDeleteCanvasTool,
  slackDeleteMessageTool,
  slackDeleteScheduledMessageTool,
  slackDownloadTool,
  slackEditCanvasTool,
  slackEphemeralMessageTool,
  slackGetCanvasTool,
  slackGetChannelHistoryTool,
  slackGetChannelInfoTool,
  slackGetMessageTool,
  slackGetPermalinkTool,
  slackGetThreadRepliesTool,
  slackGetThreadTool,
  slackGetUserPresenceTool,
  slackGetUserTool,
  slackInviteToConversationTool,
  slackListCanvasesTool,
  slackListChannelsTool,
  slackListMembersTool,
  slackListScheduledMessagesTool,
  slackListUsersTool,
  slackLookupCanvasSectionsTool,
  slackMessageReaderTool,
  slackMessageTool,
  slackOpenViewTool,
  slackPublishViewTool,
  slackPushViewTool,
  slackRemoveReactionTool,
  slackRenameConversationTool,
  slackScheduleMessageTool,
  slackSetConversationPurposeTool,
  slackSetConversationTopicTool,
  slackSetStatusTool,
  slackSetSuggestedPromptsTool,
  slackSetTitleTool,
  slackUpdateMessageTool,
  slackUpdateViewTool,
} from '@/tools/slack'
import type { ToolConfig } from '@/tools/types'

/**
 * Dev-only minimal tool registry. Swapped in for `@/tools/registry` via a
 * Turbopack/webpack resolve-alias when `SIM_DEV_MINIMAL_REGISTRY=1` (see
 * next.config.ts) so the local dev server never compiles the full ~247-tool
 * graph (~2,074 modules) that the shared workspace layout otherwise drags into
 * every route. Only these tools execute in minimal mode; unset the flag for the
 * full set. The slack and gmail v2 sets back the `slack`/`slack_v2` and
 * `gmail_v2` blocks kept in `blocks/registry-maps.minimal.ts`. NEVER aliased in
 * production.
 */
export const tools: Record<string, ToolConfig> = {
  http_request: httpRequestTool,
  function_execute: functionExecuteTool,
  guardrails_validate: guardrailsValidateTool,
  gmail_send_v2: gmailSendV2Tool,
  gmail_read_v2: gmailReadV2Tool,
  gmail_search_v2: gmailSearchV2Tool,
  gmail_draft_v2: gmailDraftV2Tool,
  gmail_move_v2: gmailMoveV2Tool,
  gmail_mark_read_v2: gmailMarkReadV2Tool,
  gmail_mark_unread_v2: gmailMarkUnreadV2Tool,
  gmail_archive_v2: gmailArchiveV2Tool,
  gmail_unarchive_v2: gmailUnarchiveV2Tool,
  gmail_delete_v2: gmailDeleteV2Tool,
  gmail_add_label_v2: gmailAddLabelV2Tool,
  gmail_remove_label_v2: gmailRemoveLabelV2Tool,
  gmail_create_label_v2: gmailCreateLabelV2Tool,
  gmail_delete_draft_v2: gmailDeleteDraftV2Tool,
  gmail_delete_label_v2: gmailDeleteLabelV2Tool,
  gmail_edit_draft_v2: gmailEditDraftV2Tool,
  gmail_get_draft_v2: gmailGetDraftV2Tool,
  gmail_get_thread_v2: gmailGetThreadV2Tool,
  gmail_list_drafts_v2: gmailListDraftsV2Tool,
  gmail_list_labels_v2: gmailListLabelsV2Tool,
  gmail_list_threads_v2: gmailListThreadsV2Tool,
  gmail_trash_thread_v2: gmailTrashThreadV2Tool,
  gmail_untrash_thread_v2: gmailUntrashThreadV2Tool,
  gmail_update_label_v2: gmailUpdateLabelV2Tool,
  slack_add_reaction: slackAddReactionTool,
  slack_archive_conversation: slackArchiveConversationTool,
  slack_canvas: slackCanvasTool,
  slack_create_channel_canvas: slackCreateChannelCanvasTool,
  slack_create_conversation: slackCreateConversationTool,
  slack_delete_canvas: slackDeleteCanvasTool,
  slack_delete_message: slackDeleteMessageTool,
  slack_delete_scheduled_message: slackDeleteScheduledMessageTool,
  slack_download: slackDownloadTool,
  slack_edit_canvas: slackEditCanvasTool,
  slack_ephemeral_message: slackEphemeralMessageTool,
  slack_get_canvas: slackGetCanvasTool,
  slack_get_channel_history: slackGetChannelHistoryTool,
  slack_get_channel_info: slackGetChannelInfoTool,
  slack_get_message: slackGetMessageTool,
  slack_get_permalink: slackGetPermalinkTool,
  slack_get_thread_replies: slackGetThreadRepliesTool,
  slack_get_thread: slackGetThreadTool,
  slack_get_user_presence: slackGetUserPresenceTool,
  slack_get_user: slackGetUserTool,
  slack_invite_to_conversation: slackInviteToConversationTool,
  slack_list_canvases: slackListCanvasesTool,
  slack_list_channels: slackListChannelsTool,
  slack_list_members: slackListMembersTool,
  slack_list_scheduled_messages: slackListScheduledMessagesTool,
  slack_list_users: slackListUsersTool,
  slack_lookup_canvas_sections: slackLookupCanvasSectionsTool,
  slack_message_reader: slackMessageReaderTool,
  slack_message: slackMessageTool,
  slack_open_view: slackOpenViewTool,
  slack_publish_view: slackPublishViewTool,
  slack_push_view: slackPushViewTool,
  slack_remove_reaction: slackRemoveReactionTool,
  slack_rename_conversation: slackRenameConversationTool,
  slack_schedule_message: slackScheduleMessageTool,
  slack_set_conversation_purpose: slackSetConversationPurposeTool,
  slack_set_conversation_topic: slackSetConversationTopicTool,
  slack_set_status: slackSetStatusTool,
  slack_set_suggested_prompts: slackSetSuggestedPromptsTool,
  slack_set_title: slackSetTitleTool,
  slack_update_message: slackUpdateMessageTool,
  slack_update_view: slackUpdateViewTool,
}
