import {
  documentedSchema,
  RATE_LIMIT_HEADERS,
  RESOURCE_ERRORS,
  WORKSPACE_API_KEY_DENIED,
} from '@/lib/api/contracts/v2/openapi/shared'
import {
  v2GetProjectFileShareContract,
  v2UpdateProjectFileShareContract,
} from '@/lib/api/contracts/v2/project-file-shares'
import { defineOpenApiRoute } from '@/lib/api/openapi/types'
import { projectFileOperations } from '@/lib/projects/files/application/operations'

export const projectFileShareOpenApiRoutes = [
  defineOpenApiRoute(
    v2GetProjectFileShareContract,
    {
      applicationOperation: projectFileOperations.readShare,
      operationId: 'getProjectFileShare',
      summary: 'Get Project File Share',
      description: `Get a Project file's public-share configuration. An unshared file returns data: null; a disabled share retains its configuration with isActive: false. ${WORKSPACE_API_KEY_DENIED}`,
      tags: ['Files'],
      errors: RESOURCE_ERRORS,
      success: { description: 'Current nullable file-share state.', headers: RATE_LIMIT_HEADERS },
    },
    {
      params: documentedSchema(
        v2GetProjectFileShareContract.params,
        'ProjectFileParams',
        'Project file identity',
        'The owning Project and the file identifier.'
      ),
      query: v2GetProjectFileShareContract.query,
      response: documentedSchema(
        v2GetProjectFileShareContract.response.schema,
        'V2GetProjectFileShareResponse',
        'Get Project file share response',
        'Current public-share state for a Project file.'
      ),
    }
  ),
  defineOpenApiRoute(
    v2UpdateProjectFileShareContract,
    {
      applicationOperation: projectFileOperations.updateShare,
      operationId: 'updateProjectFileShare',
      summary: 'Update Project File Share',
      description: `Create or update a Project file's public share. isActive is required; omitted settings retain their current values. Disabling retains the token and access configuration. Publication requires Project edit access and the current sharing policy across accessible active environments. ${WORKSPACE_API_KEY_DENIED}`,
      tags: ['Files'],
      errors: RESOURCE_ERRORS,
      success: { description: 'The updated Project file share.', headers: RATE_LIMIT_HEADERS },
    },
    {
      params: documentedSchema(
        v2UpdateProjectFileShareContract.params,
        'ProjectFileParams',
        'Project file identity',
        'The owning Project and the file identifier.'
      ),
      query: v2UpdateProjectFileShareContract.query,
      body: documentedSchema(
        v2UpdateProjectFileShareContract.body,
        'UpdateProjectFileShareRequest',
        'Update Project file share request',
        'Desired public-share state and access policy. Share tokens are generated by the server.'
      ),
      response: documentedSchema(
        v2UpdateProjectFileShareContract.response.schema,
        'V2UpdateProjectFileShareResponse',
        'Update Project file share response',
        'Updated public-share state for a Project file.'
      ),
    }
  ),
] as const
