-- Generated by drizzle-kit, then converted to CONCURRENTLY per scripts/migrate.ts (plain
-- DROP INDEX takes ACCESS EXCLUSIVE for the whole op, write-locking the table).
--
-- DROP date tag-slot indexes on embedding and document. Tag filters compare `col::date`, which a
-- plain timestamp btree can never match, so these are maintained on every chunk insert and
-- document update without ever serving a query. The number and boolean slot indexes are kept:
-- selective filters on those slots rely on them.
--
-- DROP redundant indexes, each a left-prefix of an existing non-partial superset, so the
-- superset still serves equality lookups and foreign-key cascades on the leading column:
--   emb_kb_id_idx                  ⊂ emb_kb_enabled_idx, emb_kb_model_idx
--   emb_doc_id_idx                 ⊂ emb_doc_chunk_idx, emb_doc_enabled_idx
--   usage_log_workspace_id_idx     ⊂ usage_log_workspace_created_at_idx
--   copilot_runs_execution_id_idx  ⊂ copilot_runs_execution_started_at_idx
--
-- The embedded COMMIT drops out of drizzle's batch transaction; everything below runs in
-- autocommit (CONCURRENTLY cannot run in a transaction) and is idempotent for safe replay.
COMMIT;--> statement-breakpoint
SET lock_timeout = 0;--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "emb_date1_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "emb_date2_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "doc_date1_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "doc_date2_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "emb_kb_id_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "emb_doc_id_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "usage_log_workspace_id_idx";--> statement-breakpoint
DROP INDEX CONCURRENTLY IF EXISTS "copilot_runs_execution_id_idx";--> statement-breakpoint
SET lock_timeout = '5s';
