-- Generated by drizzle-kit, then converted to CONCURRENTLY per scripts/migrate.ts (a plain
-- CREATE INDEX write-locks workspace_files for the whole build).
--
-- A workspace has at most one live dashboard. Dashboards have not shipped, so no workspace
-- holds two and the build cannot fail on existing rows. Lifting the limit drops this index.
--
-- The embedded COMMIT drops out of drizzle's batch transaction; everything below runs in
-- autocommit (CONCURRENTLY cannot run in a transaction) and is idempotent for safe replay.
COMMIT;--> statement-breakpoint
SET lock_timeout = 0;--> statement-breakpoint
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS "workspace_files_workspace_dashboard_unique" ON "workspace_files" USING btree ("workspace_id") WHERE "workspace_files"."content_type" = 'text/x-sim-dashboard' AND "workspace_files"."deleted_at" IS NULL;--> statement-breakpoint
SET lock_timeout = '5s';
