/**
 * Display titles for CLI-backed copilot tools, keyed by the synthetic tool
 * name the copilot worker derives from the sim CLI command path
 * (`cli_<command path with spaces/dashes as underscores>`).
 *
 * Generated from the sim CLI command inventory; present-participle titles so
 * the standard completed/failed tense projection in `tool-display.ts` applies.
 * Regenerate when the CLI command surface changes.
 */
export const CLI_TOOL_TITLES: Record<string, string> = {
  cli_audit_logs_get: 'Reading audit log',
  cli_audit_logs_list: 'Listing audit logs',
  cli_billing_logs: 'Reading billing logs',
  cli_billing_status: 'Checking billing status',
  cli_blocks_get: 'Inspecting block',
  cli_blocks_list: 'Browsing blocks',
  cli_chat_deployments_list: 'Listing chat deployments',
  cli_connector_types_list: 'Listing connector types',
  cli_credentials_connect: 'Creating connection link',
  cli_credentials_create: 'Creating credential',
  cli_credentials_delete: 'Deleting credential',
  cli_credentials_list: 'Listing credentials',
  cli_credentials_providers_list: 'Listing credential providers',
  cli_credentials_reconnect: 'Creating reconnection link',
  cli_credentials_update: 'Updating credential',
  cli_custom_tools_create: 'Creating custom tool',
  cli_custom_tools_delete: 'Deleting custom tool',
  cli_custom_tools_get: 'Reading custom tool',
  cli_custom_tools_list: 'Listing custom tools',
  cli_custom_tools_update: 'Updating custom tool',
  cli_files_batch_delete: 'Deleting files',
  cli_files_create: 'Creating file',
  cli_files_delete: 'Deleting file',
  cli_files_describe: 'Inspecting file',
  cli_files_folders_create: 'Creating file folder',
  cli_files_folders_delete: 'Deleting file folder',
  cli_files_folders_list: 'Listing file folders',
  cli_files_folders_move: 'Moving file folder',
  cli_files_folders_restore: 'Restoring file folder',
  cli_files_get: 'Reading file',
  cli_files_list: 'Listing files',
  cli_files_ls: 'Listing files',
  cli_files_mkdir: 'Creating file',
  cli_files_move: 'Moving file',
  cli_files_read: 'Reading file',
  cli_files_rename: 'Renaming file',
  cli_files_restore: 'Restoring file',
  cli_files_set_content: 'Writing file',
  cli_files_share_get: 'Checking file sharing',
  cli_files_share_set: 'Updating file sharing',
  cli_files_unzip: 'Unzipping file',
  cli_files_upload: 'Uploading file',
  cli_knowledge_chunks_batch_update: 'Updating knowledge chunks',
  cli_knowledge_chunks_create: 'Creating knowledge chunk',
  cli_knowledge_chunks_delete: 'Deleting knowledge chunk',
  cli_knowledge_chunks_get: 'Reading knowledge chunk',
  cli_knowledge_chunks_list: 'Listing knowledge chunks',
  cli_knowledge_chunks_update: 'Updating knowledge chunk',
  cli_knowledge_connectors_create: 'Creating knowledge connector',
  cli_knowledge_connectors_delete: 'Deleting knowledge connector',
  cli_knowledge_connectors_documents_list: 'Listing connector documents',
  cli_knowledge_connectors_documents_update: 'Updating connector documents',
  cli_knowledge_connectors_get: 'Reading knowledge connector',
  cli_knowledge_connectors_list: 'Listing knowledge connectors',
  cli_knowledge_connectors_sync: 'Syncing knowledge connector',
  cli_knowledge_connectors_update: 'Updating knowledge connector',
  cli_knowledge_create: 'Creating knowledge base',
  cli_knowledge_delete: 'Deleting knowledge base',
  cli_knowledge_documents_batch_update: 'Updating documents',
  cli_knowledge_documents_delete: 'Deleting document',
  cli_knowledge_documents_get: 'Reading document',
  cli_knowledge_documents_list: 'Listing documents',
  cli_knowledge_documents_update: 'Updating document',
  cli_knowledge_documents_upload: 'Uploading document',
  cli_knowledge_folders_create: 'Creating knowledge folder',
  cli_knowledge_folders_delete: 'Deleting knowledge folder',
  cli_knowledge_folders_list: 'Listing knowledge folders',
  cli_knowledge_folders_move: 'Moving knowledge folder',
  cli_knowledge_from_workspace_files_create: 'Creating knowledge base',
  cli_knowledge_get: 'Reading knowledge base',
  cli_knowledge_list: 'Listing knowledge bases',
  cli_knowledge_ls: 'Listing knowledge bases',
  cli_knowledge_mkdir: 'Creating knowledge base',
  cli_knowledge_mv: 'Moving knowledge base',
  cli_knowledge_restore: 'Restoring knowledge base',
  cli_knowledge_search: 'Searching knowledge base',
  cli_knowledge_tags_cleanup: 'Cleaning up knowledge tags',
  cli_knowledge_tags_create: 'Creating knowledge tag',
  cli_knowledge_tags_delete: 'Deleting knowledge tag',
  cli_knowledge_tags_list: 'Listing knowledge tags',
  cli_knowledge_tags_next_slot: 'Checking knowledge tag slots',
  cli_knowledge_tags_save: 'Saving knowledge tags',
  cli_knowledge_tags_update: 'Updating knowledge tag',
  cli_knowledge_tags_usage: 'Summarizing knowledge tag usage',
  cli_knowledge_update: 'Updating knowledge base',
  cli_logs_follow: 'Following run logs',
  cli_logs_get: 'Reading run log',
  cli_logs_list: 'Listing run logs',
  cli_logs_stats: 'Summarizing run logs',
  cli_mcp_servers_create: 'Creating MCP server',
  cli_mcp_servers_delete: 'Deleting MCP server',
  cli_mcp_servers_get: 'Reading MCP server',
  cli_mcp_servers_list: 'Listing MCP servers',
  cli_mcp_servers_tools_list: 'Listing MCP server tools',
  cli_mcp_servers_update: 'Updating MCP server',
  cli_meta_status: 'Checking platform status',
  cli_secrets_delete: 'Deleting secret',
  cli_secrets_list: 'Listing secrets',
  cli_secrets_set: 'Saving secret',
  cli_skills_create: 'Creating skill',
  cli_skills_delete: 'Deleting skill',
  cli_skills_editors_create: 'Granting skill editor',
  cli_skills_editors_delete: 'Revoking skill editor',
  cli_skills_editors_list: 'Listing skill editors',
  cli_skills_get: 'Reading skill',
  cli_skills_list: 'Listing skills',
  cli_skills_update: 'Updating skill',
  cli_tables_batch_delete: 'Deleting tables',
  cli_tables_cancel_runs: 'Cancelling table runs',
  cli_tables_columns_create: 'Creating table column',
  cli_tables_columns_delete: 'Deleting table column',
  cli_tables_columns_update: 'Updating table column',
  cli_tables_create: 'Creating table',
  cli_tables_delete: 'Deleting table',
  cli_tables_dispatches_cancel: 'Cancelling table run',
  cli_tables_dispatches_create: 'Starting table run',
  cli_tables_dispatches_get: 'Reading table run',
  cli_tables_dispatches_list: 'Listing table runs',
  cli_tables_enrichment_get: 'Reading enrichment run',
  cli_tables_exports_cancel: 'Cancelling table export',
  cli_tables_exports_create: 'Creating table export',
  cli_tables_exports_download: 'Downloading table export',
  cli_tables_exports_get: 'Reading table export',
  cli_tables_folders_create: 'Creating table folder',
  cli_tables_folders_delete: 'Deleting table folder',
  cli_tables_folders_list: 'Listing table folders',
  cli_tables_folders_move: 'Moving table folder',
  cli_tables_folders_restore: 'Restoring table folder',
  cli_tables_get: 'Reading table',
  cli_tables_groups_create: 'Creating workflow group',
  cli_tables_groups_delete: 'Deleting workflow group',
  cli_tables_groups_list: 'Listing workflow groups',
  cli_tables_groups_update: 'Updating workflow group',
  cli_tables_import: 'Importing table',
  cli_tables_imports_cancel: 'Cancelling table import',
  cli_tables_imports_get: 'Reading table import',
  cli_tables_list: 'Listing tables',
  cli_tables_ls: 'Listing tables',
  cli_tables_mkdir: 'Creating table',
  cli_tables_move: 'Moving table',
  cli_tables_mv: 'Moving table',
  cli_tables_restore: 'Restoring table',
  cli_tables_rows_batch_delete: 'Deleting table rows',
  cli_tables_rows_batch_update: 'Updating table rows',
  cli_tables_rows_count: 'Counting table rows',
  cli_tables_rows_create: 'Creating table row',
  cli_tables_rows_delete: 'Deleting table row',
  cli_tables_rows_enrich: 'Enriching table row',
  cli_tables_rows_get: 'Reading table row',
  cli_tables_rows_list: 'Listing table rows',
  cli_tables_rows_query: 'Querying table rows',
  cli_tables_rows_search: 'Searching table rows',
  cli_tables_rows_update: 'Updating table row',
  cli_tables_rows_update_each: 'Updating table rows',
  cli_tables_update: 'Updating table',
  cli_tables_upsert: 'Updating table',
  cli_tables_views_create: 'Creating table view',
  cli_tables_views_delete: 'Deleting table view',
  cli_tables_views_get: 'Reading table view',
  cli_tables_views_list: 'Listing table views',
  cli_tables_views_update: 'Updating table view',
  cli_tools_get: 'Inspecting tool',
  cli_tools_list: 'Browsing tools',
  cli_workflow_mcp_servers_create: 'Creating workflow MCP server',
  cli_workflow_mcp_servers_delete: 'Deleting workflow MCP server',
  cli_workflow_mcp_servers_get: 'Reading workflow MCP server',
  cli_workflow_mcp_servers_list: 'Listing workflow MCP servers',
  cli_workflow_mcp_servers_tools_create: 'Publishing workflow as MCP tool',
  cli_workflow_mcp_servers_tools_delete: 'Unpublishing workflow MCP tool',
  cli_workflow_mcp_servers_tools_list: 'Listing workflow MCP tools',
  cli_workflow_mcp_servers_update: 'Updating workflow MCP server',
  cli_workflows_activate_create: 'Activating workflow version',
  cli_workflows_chat_publish: 'Publishing chat deployment',
  cli_workflows_chat_status: 'Checking chat deployment',
  cli_workflows_chat_unpublish: 'Unpublishing chat deployment',
  cli_workflows_create: 'Creating workflow',
  cli_workflows_delete: 'Deleting workflow',
  cli_workflows_deploy: 'Deploying workflow',
  cli_workflows_deployment_status: 'Checking deployment status',
  cli_workflows_deployment_update: 'Updating API access',
  cli_workflows_duplicate_create: 'Duplicating workflow',
  cli_workflows_export: 'Exporting workflow',
  cli_workflows_folders_create: 'Creating workflow folder',
  cli_workflows_folders_delete: 'Deleting workflow folder',
  cli_workflows_folders_list: 'Listing workflow folders',
  cli_workflows_folders_move: 'Moving workflow folder',
  cli_workflows_get: 'Reading workflow',
  cli_workflows_import: 'Importing workflow',
  cli_workflows_list: 'Listing workflows',
  cli_workflows_ls: 'Listing workflows',
  cli_workflows_mkdir: 'Creating workflow',
  cli_workflows_move: 'Moving workflow',
  cli_workflows_mv: 'Moving workflow',
  cli_workflows_operations_apply: 'Editing workflow',
  cli_workflows_restore: 'Restoring workflow',
  cli_workflows_revert_create: 'Reverting workflow',
  cli_workflows_rollback: 'Rolling back workflow',
  cli_workflows_run: 'Running workflow',
  cli_workflows_runs_cancel: 'Cancelling workflow run',
  cli_workflows_runs_get: 'Checking workflow run',
  cli_workflows_runs_list: 'Listing workflow runs',
  cli_workflows_runs_resume: 'Resuming workflow run',
  cli_workflows_runs_wait: 'Waiting for workflow run',
  cli_workflows_state_get: 'Reading workflow',
  cli_workflows_state_replace: 'Rewriting workflow',
  cli_workflows_undeploy: 'Undeploying workflow',
  cli_workflows_update: 'Updating workflow',
  cli_workflows_variables_update: 'Updating workflow variables',
  cli_workflows_versions_get: 'Reading workflow version',
  cli_workflows_versions_list: 'Listing workflow versions',
  cli_workflows_versions_update: 'Updating workflow version',
  cli_workspaces_get: 'Reading workspace',
  cli_workspaces_list: 'Listing workspaces',
  cli_workspaces_members: 'Listing workspace members',
  // Agent-only CLI augmentations
  cli_files_grep: 'Searching file contents',
  cli_grep: 'Searching the workspace',
  cli_logs_query: 'Querying run history',
  cli_workflow_blocks: 'Listing workflow blocks',
  cli_workflow_deps: 'Tracing block inputs',
  cli_workflow_edges: 'Reading workflow wiring',
  cli_workflow_grep: 'Searching workflow',
  cli_workflow_lint: 'Validating workflow',
  cli_workflow_trace: 'Analyzing run trace',
  cli_workflows_grep: 'Searching workflows',
  // Non-CLI copilot worker tools
  cli_help: 'Checking CLI reference',
  sim_cli: 'Running CLI command',
  run_code: 'Running code',
  load_skill: 'Loading skill',
  read_output: 'Reading full output',
  remember: 'Updating memory',
  task: 'Delegating task',
}
