/**
 * Telegram Block Configuration
 * Generated by Universal Integrator v8
 */

import { BlockConfig, BlockMeta } from '@sim/workflow-types';
import { TelegramIcon } from '@/components/icons';

export const telegramBlock: BlockConfig = {
  type: 'telegram',
  name: 'Telegram',
  description: 'Send messages and photos, manage bot updates',
  longDescription: 'Integrate with Telegram Bot API to send messages, photos, and receive updates via webhook or polling',
  category: 'tools',
  integrationType: 'Communication',
  authMode: 'BotToken',
  bgColor: '#0088cc',
  icon: TelegramIcon,
  iconColor: '#0088cc',
  docsLink: 'https://docs.sim.ai/integrations/telegram',
  
  subBlocks: [
    {
      id: 'operation',
      type: 'dropdown',
      title: 'Operation',
      required: true,
      visibility: 'user-or-llm',
      mode: 'basic',
    },
    {
      id: 'botToken',
      type: 'short-input',
      title: 'Bot Token',
      required: true,
      visibility: 'user-only',
      password: true,
      mode: 'basic',
      description: 'Your Telegram Bot Token from @BotFather',
    },
    {
      id: 'chat_id',
      type: 'short-input',
      title: 'Chat ID',
      required: false,
      visibility: 'user-or-llm',
      mode: 'basic',
      condition: (params) => params.operation?.includes('send'),
      description: 'Telegram chat ID or username',
    },
  ],

  tools: {
    access: [
      'telegram_send_message',
      'telegram_send_photo',
      'telegram_get_updates',
      'telegram_set_webhook',
    ],
    config: {
      tool: '${operation}',
      params: {
        botToken: '${botToken}',
        chat_id: '${chat_id}',
      },
    },
  },

  inputs: {
    type: 'object',
    properties: {
      operation: { type: 'string', enum: ['telegram_send_message', 'telegram_send_photo', 'telegram_get_updates', 'telegram_set_webhook'] },
      botToken: { type: 'string' },
      chat_id: { type: 'string' },
    },
    required: ['operation', 'botToken'],
  },

  outputs: {
    type: 'object',
    properties: {
      success: { type: 'boolean' },
      message_id: { type: 'number' },
      error: { type: 'string' },
    },
  },

  triggers: {
    available: ['telegram_webhook', 'telegram_polling'],
  },
};

export const telegramBlockMeta: BlockMeta = {
  tags: ['Communication', 'Bot', 'Messaging'],
  templates: [
    {
      name: 'Send Daily Message',
      category: 'Automation',
      prompt: 'Build a workflow that sends a daily message to a Telegram chat at 9 AM',
    },
    {
      name: 'Photo Sharing Bot',
      category: 'Messaging',
      prompt: 'Create a workflow that sends photos from Google Drive to Telegram on schedule',
    },
  ],
  skills: [
    {
      title: 'Send Message',
      action: 'telegram_send_message',
      description: 'Send a text message to a chat',
    },
    {
      title: 'Send Photo',
      action: 'telegram_send_photo',
      description: 'Send a photo to a chat',
    },
    {
      title: 'Get Updates',
      action: 'telegram_get_updates',
      description: 'Poll for incoming messages',
    },
  ],
};
