import { BrightDataIcon } from '@/components/icons'
import type { BlockConfig } from '@/blocks/types'
import { AuthMode } from '@/blocks/types'
import type { BrightDataResponse } from '@/tools/brightdata/types'

const DATASET_TOOL_MAP: Record<string, string> = {
  dataset_amazon_product: 'brightdata_dataset_amazon_product',
  dataset_amazon_product_reviews: 'brightdata_dataset_amazon_product_reviews',
  dataset_amazon_product_search: 'brightdata_dataset_amazon_product_search',
  dataset_walmart_product: 'brightdata_dataset_walmart_product',
  dataset_walmart_seller: 'brightdata_dataset_walmart_seller',
  dataset_ebay_product: 'brightdata_dataset_ebay_product',
  dataset_homedepot_products: 'brightdata_dataset_homedepot_products',
  dataset_zara_products: 'brightdata_dataset_zara_products',
  dataset_etsy_products: 'brightdata_dataset_etsy_products',
  dataset_bestbuy_products: 'brightdata_dataset_bestbuy_products',
  dataset_linkedin_person_profile: 'brightdata_dataset_linkedin_person_profile',
  dataset_linkedin_company_profile: 'brightdata_dataset_linkedin_company_profile',
  dataset_linkedin_job_listings: 'brightdata_dataset_linkedin_job_listings',
  dataset_linkedin_posts: 'brightdata_dataset_linkedin_posts',
  dataset_linkedin_people_search: 'brightdata_dataset_linkedin_people_search',
  dataset_crunchbase_company: 'brightdata_dataset_crunchbase_company',
  dataset_zoominfo_company_profile: 'brightdata_dataset_zoominfo_company_profile',
  dataset_instagram_profiles: 'brightdata_dataset_instagram_profiles',
  dataset_instagram_posts: 'brightdata_dataset_instagram_posts',
  dataset_instagram_reels: 'brightdata_dataset_instagram_reels',
  dataset_instagram_comments: 'brightdata_dataset_instagram_comments',
  dataset_facebook_posts: 'brightdata_dataset_facebook_posts',
  dataset_facebook_marketplace_listings: 'brightdata_dataset_facebook_marketplace_listings',
  dataset_facebook_company_reviews: 'brightdata_dataset_facebook_company_reviews',
  dataset_facebook_events: 'brightdata_dataset_facebook_events',
  dataset_tiktok_profiles: 'brightdata_dataset_tiktok_profiles',
  dataset_tiktok_posts: 'brightdata_dataset_tiktok_posts',
  dataset_tiktok_shop: 'brightdata_dataset_tiktok_shop',
  dataset_tiktok_comments: 'brightdata_dataset_tiktok_comments',
  dataset_google_maps_reviews: 'brightdata_dataset_google_maps_reviews',
  dataset_google_shopping: 'brightdata_dataset_google_shopping',
  dataset_google_play_store: 'brightdata_dataset_google_play_store',
  dataset_apple_app_store: 'brightdata_dataset_apple_app_store',
  dataset_reuter_news: 'brightdata_dataset_reuter_news',
  dataset_github_repository_file: 'brightdata_dataset_github_repository_file',
  dataset_yahoo_finance_business: 'brightdata_dataset_yahoo_finance_business',
  dataset_x_posts: 'brightdata_dataset_x_posts',
  dataset_zillow_properties_listing: 'brightdata_dataset_zillow_properties_listing',
  dataset_booking_hotel_listings: 'brightdata_dataset_booking_hotel_listings',
  dataset_youtube_profiles: 'brightdata_dataset_youtube_profiles',
  dataset_youtube_comments: 'brightdata_dataset_youtube_comments',
  dataset_reddit_posts: 'brightdata_dataset_reddit_posts',
  dataset_youtube_videos: 'brightdata_dataset_youtube_videos',
  dataset_npm_package: 'brightdata_dataset_npm_package',
  dataset_pypi_package: 'brightdata_dataset_pypi_package',
}

export const BrightDataBlock: BlockConfig<BrightDataResponse> = {
  type: 'brightdata',
  name: 'Bright Data',
  description: 'Web scraping, search, and dataset access',
  authMode: AuthMode.ApiKey,
  longDescription:
    "Access Bright Data's web data collection tools including web scraping, search, and datasets.",
  docsLink: 'https://docs.sim.ai/tools/brightdata',
  category: 'tools',
  bgColor: '#3D7FFC',
  icon: BrightDataIcon,

  subBlocks: [
    {
      id: 'operation',
      title: 'Operation',
      type: 'dropdown',
      required: true,
      options: [
        { label: 'Scrape as Markdown', id: 'scrape_markdown' },
        { label: 'Search Engine', id: 'search_engine' },
        { label: 'Amazon Product Dataset', id: 'dataset_amazon_product' },
        { label: 'Amazon Product Reviews Dataset', id: 'dataset_amazon_product_reviews' },
        { label: 'Amazon Product Search Dataset', id: 'dataset_amazon_product_search' },
        { label: 'Walmart Product Dataset', id: 'dataset_walmart_product' },
        { label: 'Walmart Seller Dataset', id: 'dataset_walmart_seller' },
        { label: 'Ebay Product Dataset', id: 'dataset_ebay_product' },
        { label: 'Homedepot Products Dataset', id: 'dataset_homedepot_products' },
        { label: 'Zara Products Dataset', id: 'dataset_zara_products' },
        { label: 'Etsy Products Dataset', id: 'dataset_etsy_products' },
        { label: 'Bestbuy Products Dataset', id: 'dataset_bestbuy_products' },
        { label: 'Linkedin Person Profile Dataset', id: 'dataset_linkedin_person_profile' },
        { label: 'Linkedin Company Profile Dataset', id: 'dataset_linkedin_company_profile' },
        { label: 'Linkedin Job Listings Dataset', id: 'dataset_linkedin_job_listings' },
        { label: 'Linkedin Posts Dataset', id: 'dataset_linkedin_posts' },
        { label: 'Linkedin People Search Dataset', id: 'dataset_linkedin_people_search' },
        { label: 'Crunchbase Company Dataset', id: 'dataset_crunchbase_company' },
        { label: 'Zoominfo Company Profile Dataset', id: 'dataset_zoominfo_company_profile' },
        { label: 'Instagram Profiles Dataset', id: 'dataset_instagram_profiles' },
        { label: 'Instagram Posts Dataset', id: 'dataset_instagram_posts' },
        { label: 'Instagram Reels Dataset', id: 'dataset_instagram_reels' },
        { label: 'Instagram Comments Dataset', id: 'dataset_instagram_comments' },
        { label: 'Facebook Posts Dataset', id: 'dataset_facebook_posts' },
        { label: 'Facebook Marketplace Listings Dataset', id: 'dataset_facebook_marketplace_listings' },
        { label: 'Facebook Company Reviews Dataset', id: 'dataset_facebook_company_reviews' },
        { label: 'Facebook Events Dataset', id: 'dataset_facebook_events' },
        { label: 'Tiktok Profiles Dataset', id: 'dataset_tiktok_profiles' },
        { label: 'Tiktok Posts Dataset', id: 'dataset_tiktok_posts' },
        { label: 'Tiktok Shop Dataset', id: 'dataset_tiktok_shop' },
        { label: 'Tiktok Comments Dataset', id: 'dataset_tiktok_comments' },
        { label: 'Google Maps Reviews Dataset', id: 'dataset_google_maps_reviews' },
        { label: 'Google Shopping Dataset', id: 'dataset_google_shopping' },
        { label: 'Google Play Store Dataset', id: 'dataset_google_play_store' },
        { label: 'Apple App Store Dataset', id: 'dataset_apple_app_store' },
        { label: 'Reuter News Dataset', id: 'dataset_reuter_news' },
        { label: 'Github Repository File Dataset', id: 'dataset_github_repository_file' },
        { label: 'Yahoo Finance Business Dataset', id: 'dataset_yahoo_finance_business' },
        { label: 'X Posts Dataset', id: 'dataset_x_posts' },
        { label: 'Zillow Properties Listing Dataset', id: 'dataset_zillow_properties_listing' },
        { label: 'Booking Hotel Listings Dataset', id: 'dataset_booking_hotel_listings' },
        { label: 'Youtube Profiles Dataset', id: 'dataset_youtube_profiles' },
        { label: 'Youtube Comments Dataset', id: 'dataset_youtube_comments' },
        { label: 'Reddit Posts Dataset', id: 'dataset_reddit_posts' },
        { label: 'Youtube Videos Dataset', id: 'dataset_youtube_videos' },
        { label: 'Npm Package Dataset', id: 'dataset_npm_package' },
        { label: 'Pypi Package Dataset', id: 'dataset_pypi_package' },
      ],
      value: () => 'scrape_markdown',
    },
    {
      id: 'url',
      title: 'URL',
      type: 'short-input',
      placeholder: 'https://example.com',
      condition: { field: 'operation', value: 'scrape_markdown' },
      required: true,
    },
    {
      id: 'query',
      title: 'Search Query',
      type: 'short-input',
      placeholder: 'Enter search query',
      condition: { field: 'operation', value: 'search_engine' },
      required: true,
    },
    {
      id: 'maxResults',
      title: 'Max Results',
      type: 'short-input',
      placeholder: '10',
      condition: { field: 'operation', value: 'search_engine' },
    },
    {
      id: 'url',
      title: 'Dataset URL',
      type: 'short-input',
      placeholder: 'https://example.com',
      condition: { field: 'operation', value: ['dataset_amazon_product', 'dataset_amazon_product_reviews', 'dataset_amazon_product_search', 'dataset_walmart_product', 'dataset_walmart_seller', 'dataset_ebay_product', 'dataset_homedepot_products', 'dataset_zara_products', 'dataset_etsy_products', 'dataset_bestbuy_products', 'dataset_linkedin_person_profile', 'dataset_linkedin_company_profile', 'dataset_linkedin_job_listings', 'dataset_linkedin_posts', 'dataset_linkedin_people_search', 'dataset_crunchbase_company', 'dataset_zoominfo_company_profile', 'dataset_instagram_profiles', 'dataset_instagram_posts', 'dataset_instagram_reels', 'dataset_instagram_comments', 'dataset_facebook_posts', 'dataset_facebook_marketplace_listings', 'dataset_facebook_company_reviews', 'dataset_facebook_events', 'dataset_tiktok_profiles', 'dataset_tiktok_posts', 'dataset_tiktok_shop', 'dataset_tiktok_comments', 'dataset_google_maps_reviews', 'dataset_google_shopping', 'dataset_google_play_store', 'dataset_apple_app_store', 'dataset_reuter_news', 'dataset_github_repository_file', 'dataset_yahoo_finance_business', 'dataset_x_posts', 'dataset_zillow_properties_listing', 'dataset_booking_hotel_listings', 'dataset_youtube_profiles', 'dataset_youtube_comments', 'dataset_reddit_posts', 'dataset_youtube_videos'] },
      required: true,
    },
    {
      id: 'keyword',
      title: 'Keyword',
      type: 'short-input',
      placeholder: 'Enter keyword',
      condition: { field: 'operation', value: ['dataset_amazon_product_search'] },
      required: true,
    },
    {
      id: 'first_name',
      title: 'First Name',
      type: 'short-input',
      placeholder: 'First name',
      condition: { field: 'operation', value: ['dataset_linkedin_people_search'] },
      required: true,
    },
    {
      id: 'last_name',
      title: 'Last Name',
      type: 'short-input',
      placeholder: 'Last name',
      condition: { field: 'operation', value: ['dataset_linkedin_people_search'] },
      required: true,
    },
    {
      id: 'num_of_reviews',
      title: 'Number of Reviews',
      type: 'short-input',
      placeholder: '10',
      condition: { field: 'operation', value: ['dataset_facebook_company_reviews'] },
      required: true,
    },
    {
      id: 'days_limit',
      title: 'Days Limit',
      type: 'short-input',
      placeholder: '3',
      condition: { field: 'operation', value: ['dataset_google_maps_reviews'] },
    },
    {
      id: 'num_of_comments',
      title: 'Number of Comments',
      type: 'short-input',
      placeholder: '10',
      condition: { field: 'operation', value: ['dataset_youtube_comments'] },
    },
    {
      id: 'package_name',
      title: 'Package Name',
      type: 'short-input',
      placeholder: '@brightdata/sdk',
      condition: { field: 'operation', value: ['dataset_npm_package', 'dataset_pypi_package'] },
      required: true,
    },
    {
      id: 'apiToken',
      title: 'API Token',
      type: 'short-input',
      placeholder: 'Your Bright Data API token',
      password: true,
      required: true,
    },
    {
      id: 'unlockerZone',
      title: 'Unlocker Zone',
      type: 'short-input',
      placeholder: 'mcp_unlocker',
      mode: 'advanced',
    },
  ],

  tools: {
    access: [
      'brightdata_scrape_markdown',
      'brightdata_search_engine',
      'brightdata_dataset_amazon_product',
      'brightdata_dataset_amazon_product_reviews',
      'brightdata_dataset_amazon_product_search',
      'brightdata_dataset_walmart_product',
      'brightdata_dataset_walmart_seller',
      'brightdata_dataset_ebay_product',
      'brightdata_dataset_homedepot_products',
      'brightdata_dataset_zara_products',
      'brightdata_dataset_etsy_products',
      'brightdata_dataset_bestbuy_products',
      'brightdata_dataset_linkedin_person_profile',
      'brightdata_dataset_linkedin_company_profile',
      'brightdata_dataset_linkedin_job_listings',
      'brightdata_dataset_linkedin_posts',
      'brightdata_dataset_linkedin_people_search',
      'brightdata_dataset_crunchbase_company',
      'brightdata_dataset_zoominfo_company_profile',
      'brightdata_dataset_instagram_profiles',
      'brightdata_dataset_instagram_posts',
      'brightdata_dataset_instagram_reels',
      'brightdata_dataset_instagram_comments',
      'brightdata_dataset_facebook_posts',
      'brightdata_dataset_facebook_marketplace_listings',
      'brightdata_dataset_facebook_company_reviews',
      'brightdata_dataset_facebook_events',
      'brightdata_dataset_tiktok_profiles',
      'brightdata_dataset_tiktok_posts',
      'brightdata_dataset_tiktok_shop',
      'brightdata_dataset_tiktok_comments',
      'brightdata_dataset_google_maps_reviews',
      'brightdata_dataset_google_shopping',
      'brightdata_dataset_google_play_store',
      'brightdata_dataset_apple_app_store',
      'brightdata_dataset_reuter_news',
      'brightdata_dataset_github_repository_file',
      'brightdata_dataset_yahoo_finance_business',
      'brightdata_dataset_x_posts',
      'brightdata_dataset_zillow_properties_listing',
      'brightdata_dataset_booking_hotel_listings',
      'brightdata_dataset_youtube_profiles',
      'brightdata_dataset_youtube_comments',
      'brightdata_dataset_reddit_posts',
      'brightdata_dataset_youtube_videos',
      'brightdata_dataset_npm_package',
      'brightdata_dataset_pypi_package',
    ],
    config: {
      tool: (params: Record<string, unknown>) => {
        const datasetTool = DATASET_TOOL_MAP[String(params.operation)]
        if (datasetTool) return datasetTool
        switch (params.operation) {
          case 'scrape_markdown':
            return 'brightdata_scrape_markdown'
          case 'search_engine':
            return 'brightdata_search_engine'
          default:
            throw new Error('Invalid operation selected')
        }
      },
    },
  },

  inputs: {
    operation: { type: 'string', description: 'Operation to perform' },
    url: { type: 'string', description: 'URL to scrape or dataset input' },
    query: { type: 'string', description: 'Search query' },
    maxResults: { type: 'number', description: 'Maximum search results' },
    keyword: { type: 'string', description: 'Dataset keyword input' },
    first_name: { type: 'string', description: 'Dataset first name input' },
    last_name: { type: 'string', description: 'Dataset last name input' },
    num_of_reviews: { type: 'string', description: 'Dataset number of reviews input' },
    days_limit: { type: 'string', description: 'Dataset days limit input' },
    num_of_comments: { type: 'string', description: 'Dataset number of comments input' },
    package_name: { type: 'string', description: 'Dataset package name input' },
    apiToken: { type: 'string', description: 'Bright Data API token' },
    unlockerZone: { type: 'string', description: 'Unlocker zone name' },
  },

  outputs: {
    markdown: { type: 'string', description: 'Scraped markdown content' },
    results: { type: 'array', description: 'Search results' },
    data: { type: 'json', description: 'Dataset response' },
    url: { type: 'string', description: 'Current or scraped URL' },
    title: { type: 'string', description: 'Page title' },
    success: { type: 'boolean', description: 'Operation success status' },
    snapshot_at: { type: 'string', description: 'Dataset snapshot timestamp' },
  },
}
