import { CodaIcon } from '@/components/icons'
import { AuthMode, type BlockConfig, type BlockMeta, IntegrationType } from '@/blocks/types'
import type { CodaResponse } from '@/tools/coda/types'

/** Canonical credential pair: the credential picker in basic mode, a raw credential id in advanced. */
const CREDENTIAL_FIELD = ['credential', 'manualCredential']
const DOC_FIELD = ['docSelector', 'manualDocId']
const PAGE_FIELD = ['pageSelector', 'manualPageId']
const TABLE_FIELD = ['tableSelector', 'manualTableId']
const ROW_FIELD = ['rowSelector', 'manualRowId']
const COLUMN_FIELD = ['columnSelector', 'manualColumnId']
const FORMULA_FIELD = ['formulaSelector', 'manualFormulaId']
const CONTROL_FIELD = ['controlSelector', 'manualControlId']
const FOLDER_FIELD = ['folderSelector', 'manualFolderId']
const PERMISSION_FIELD = ['permissionSelector', 'manualPermissionId']

const PAGE_OPERATIONS = [
  'get_page',
  'update_page',
  'delete_page',
  'get_page_content',
  'delete_page_content',
  'export_page',
  'get_page_export_status',
]

const ROW_OPERATIONS = ['get_row', 'update_row', 'delete_row', 'push_button']

const TABLE_OPERATIONS = [
  'get_table',
  'list_columns',
  'get_column',
  'list_rows',
  'upsert_rows',
  'delete_rows',
  ...ROW_OPERATIONS,
]

const DOC_OPERATIONS = [
  'get_doc',
  'update_doc',
  'delete_doc',
  'publish_doc',
  'unpublish_doc',
  'list_custom_domains',
  'add_custom_domain',
  'delete_custom_domain',
  'list_permissions',
  'add_permission',
  'delete_permission',
  'search_principals',
  'get_sharing_metadata',
  'get_acl_settings',
  'update_acl_settings',
  'list_pages',
  'create_page',
  ...PAGE_OPERATIONS,
  'list_tables',
  ...TABLE_OPERATIONS,
  'list_formulas',
  'get_formula',
  'list_controls',
  'get_control',
  'trigger_automation',
  'list_page_analytics',
]

const FOLDER_REQUIRED_OPERATIONS = [
  'get_folder',
  'update_folder',
  'delete_folder',
  'list_folder_children',
]
const FOLDER_OPERATIONS = ['list_docs', 'create_doc', ...FOLDER_REQUIRED_OPERATIONS]

const WORKSPACE_REQUIRED_OPERATIONS = [
  'create_folder',
  'list_workspace_members',
  'change_user_role',
  'list_workspace_roles',
]
const WORKSPACE_FILTER_OPERATIONS = [
  'list_docs',
  'list_folders',
  'list_doc_analytics',
  'get_doc_analytics_summary',
]

const PAGE_CREATE_OPERATIONS = ['create_doc', 'create_page']
const PAGE_WRITE_OPERATIONS = [...PAGE_CREATE_OPERATIONS, 'update_page']
const ANALYTICS_DATE_OPERATIONS = [
  'list_doc_analytics',
  'list_page_analytics',
  'get_doc_analytics_summary',
]

const LIMIT_OPERATIONS = [
  'list_docs',
  'list_pages',
  'get_page_content',
  'list_tables',
  'list_columns',
  'list_rows',
  'list_formulas',
  'list_controls',
  'list_folders',
  'list_folder_children',
  'list_permissions',
  'list_doc_analytics',
  'list_page_analytics',
]
const PAGE_TOKEN_OPERATIONS = [...LIMIT_OPERATIONS, 'list_workspace_members']

const LIST_SORT_OPERATIONS = ['list_tables', 'list_formulas', 'list_controls']

/** Switches only send `true`; an off switch leaves the Coda filter unset. */
function trueOrUndefined(value: unknown): true | undefined {
  return value === true || value === 'true' ? true : undefined
}

/** Maps a three-state dropdown (unchanged / true / false) to an optional boolean. */
function triState(value: unknown): boolean | undefined {
  if (value === 'true' || value === true) return true
  if (value === 'false' || value === false) return false
  return undefined
}

function optionalNumber(value: unknown): number | undefined {
  if (value === undefined || value === null || value === '') return undefined
  const parsed = Number(value)
  return Number.isFinite(parsed) ? parsed : undefined
}

function unlessDefault(value: unknown, defaultValue: string): string | undefined {
  return typeof value === 'string' && value !== '' && value !== defaultValue ? value : undefined
}

/** Content fields apply to every page update, but only to canvas pages when creating. */
function canvasContentCondition(values?: Record<string, unknown>) {
  return values?.operation === 'update_page'
    ? { field: 'operation', value: 'update_page' }
    : {
        field: 'operation',
        value: PAGE_CREATE_OPERATIONS,
        and: { field: 'pageType', value: 'canvas' },
      }
}

const TRI_STATE_OPTIONS = [
  { label: 'Unchanged', id: 'unchanged' },
  { label: 'Yes', id: 'true' },
  { label: 'No', id: 'false' },
]

const DATE_WAND = {
  enabled: true,
  prompt:
    'Generate a date in YYYY-MM-DD format based on the user description. Return ONLY the date string.',
  placeholder: 'Describe the date (e.g., "30 days ago")...',
  generationType: 'timestamp',
} as const

export const CodaBlock: BlockConfig<CodaResponse> = {
  type: 'coda',
  name: 'Coda',
  description: 'Read and write Coda docs, pages, tables, and rows',
  authMode: AuthMode.ApiKey,
  longDescription:
    'Integrate Coda (Superhuman Docs) into your workflow with a reusable API-token credential. Create, copy, publish, and share docs; create, update, read, export, and clear pages; read table schemas; list, insert, upsert, update, and delete rows and push row buttons; read formulas and controls; trigger webhook automations; manage folders, custom domains, and workspace roles; and read doc and page analytics. Pick docs, pages, tables, rows, and more from dropdowns populated by your account.',
  docsLink: 'https://docs.sim.ai/integrations/coda',
  category: 'tools',
  integrationType: IntegrationType.Documents,
  bgColor: '#FFFFFF',
  icon: CodaIcon,
  canvasPresentation: {
    defaultTitle: 'Coda',
    sentences: {
      byOperation: {
        list_docs: ['List docs', { text: 'matching', field: 'docSearch' }],
        get_doc: [{ text: 'Read doc', field: DOC_FIELD, core: true }],
        create_doc: ['Create doc', { text: 'titled', field: 'docTitle' }],
        update_doc: [
          { text: 'Update doc', field: DOC_FIELD, core: true },
          { text: 'to', field: 'docTitle' },
        ],
        delete_doc: [{ text: 'Delete doc', field: DOC_FIELD, core: true }],
        publish_doc: [{ text: 'Publish', field: DOC_FIELD, core: true }],
        unpublish_doc: [{ text: 'Unpublish', field: DOC_FIELD, core: true }],
        list_categories: ['List doc categories'],
        list_custom_domains: [{ text: 'List custom domains of', field: DOC_FIELD, core: true }],
        add_custom_domain: [
          { text: 'Add domain', field: 'customDocDomain', core: true },
          { text: 'to', field: DOC_FIELD, core: true },
        ],
        delete_custom_domain: [
          { text: 'Remove domain', field: 'customDocDomain', core: true },
          { text: 'from', field: DOC_FIELD, core: true },
        ],
        get_custom_domain_provider: [
          { text: 'Look up DNS provider of', field: 'customDocDomain', core: true },
        ],
        list_permissions: [{ text: 'List permissions on', field: DOC_FIELD, core: true }],
        add_permission: [
          { text: 'Share', field: DOC_FIELD, core: true },
          { text: 'with', field: 'principal' },
          { text: 'as', field: 'access' },
        ],
        delete_permission: [
          { text: 'Remove permission', field: PERMISSION_FIELD, core: true },
          { text: 'from', field: DOC_FIELD },
        ],
        search_principals: [
          { text: 'Search users and groups for', field: DOC_FIELD, core: true },
          { text: 'matching', field: 'principalQuery' },
        ],
        get_sharing_metadata: [{ text: 'Check sharing rights on', field: DOC_FIELD, core: true }],
        get_acl_settings: [{ text: 'Read sharing settings of', field: DOC_FIELD, core: true }],
        update_acl_settings: [{ text: 'Update sharing settings of', field: DOC_FIELD, core: true }],
        list_pages: [{ text: 'List pages in', field: DOC_FIELD, core: true }],
        get_page: [
          { text: 'Read page', field: PAGE_FIELD, core: true },
          { text: 'in', field: DOC_FIELD },
        ],
        create_page: [
          'Create page',
          { text: 'named', field: 'pageName' },
          { text: 'in', field: DOC_FIELD, core: true },
        ],
        update_page: [
          { text: 'Update page', field: PAGE_FIELD, core: true },
          { text: 'in', field: DOC_FIELD },
        ],
        delete_page: [
          { text: 'Delete page', field: PAGE_FIELD, core: true },
          { text: 'from', field: DOC_FIELD },
        ],
        get_page_content: [{ text: 'Read content of', field: PAGE_FIELD, core: true }],
        delete_page_content: [{ text: 'Delete content from', field: PAGE_FIELD, core: true }],
        export_page: [
          { text: 'Export', field: PAGE_FIELD, core: true },
          { text: 'as', field: 'outputFormat' },
        ],
        get_page_export_status: [{ text: 'Check export', field: 'exportId', core: true }],
        list_tables: [{ text: 'List tables in', field: DOC_FIELD, core: true }],
        get_table: [{ text: 'Read table', field: TABLE_FIELD, core: true }],
        list_columns: [{ text: 'List columns of', field: TABLE_FIELD, core: true }],
        get_column: [
          { text: 'Read column', field: COLUMN_FIELD, core: true },
          { text: 'of', field: TABLE_FIELD },
        ],
        list_rows: [
          { text: 'List rows in', field: TABLE_FIELD, core: true },
          { text: 'where', field: 'rowFilter' },
        ],
        get_row: [
          { text: 'Read row', field: ROW_FIELD, core: true },
          { text: 'from', field: TABLE_FIELD },
        ],
        upsert_rows: [{ text: 'Insert or update rows in', field: TABLE_FIELD, core: true }],
        update_row: [
          { text: 'Update row', field: ROW_FIELD, core: true },
          { text: 'in', field: TABLE_FIELD },
        ],
        delete_row: [
          { text: 'Delete row', field: ROW_FIELD, core: true },
          { text: 'from', field: TABLE_FIELD },
        ],
        delete_rows: [
          { text: 'Delete rows', field: 'rowIds', core: true },
          { text: 'from', field: TABLE_FIELD },
        ],
        push_button: [
          { text: 'Push button', field: COLUMN_FIELD, core: true },
          { text: 'on row', field: ROW_FIELD },
        ],
        list_formulas: [{ text: 'List formulas in', field: DOC_FIELD, core: true }],
        get_formula: [{ text: 'Read formula', field: FORMULA_FIELD, core: true }],
        list_controls: [{ text: 'List controls in', field: DOC_FIELD, core: true }],
        get_control: [{ text: 'Read control', field: CONTROL_FIELD, core: true }],
        trigger_automation: [
          { text: 'Trigger automation', field: 'ruleId', core: true },
          { text: 'in', field: DOC_FIELD },
        ],
        list_folders: ['List folders'],
        get_folder: [{ text: 'Read folder', field: FOLDER_FIELD, core: true }],
        create_folder: [
          { text: 'Create folder', field: 'folderName', core: true },
          { text: 'in', field: 'workspaceId' },
        ],
        update_folder: [{ text: 'Update folder', field: FOLDER_FIELD, core: true }],
        delete_folder: [{ text: 'Delete folder', field: FOLDER_FIELD, core: true }],
        list_folder_children: [{ text: 'List subfolders of', field: FOLDER_FIELD, core: true }],
        list_workspace_members: [{ text: 'List members of', field: 'workspaceId', core: true }],
        change_user_role: [
          { text: 'Set role of', field: 'memberEmail', core: true },
          { text: 'to', field: 'newRole' },
        ],
        list_workspace_roles: [{ text: 'Read role activity of', field: 'workspaceId', core: true }],
        list_doc_analytics: ['Read doc analytics', { text: 'since', field: 'sinceDate' }],
        list_page_analytics: [{ text: 'Read page analytics of', field: DOC_FIELD, core: true }],
        get_doc_analytics_summary: [
          'Read total doc sessions',
          { text: 'since', field: 'sinceDate' },
        ],
        get_analytics_last_updated: ['Check when analytics last updated'],
        resolve_browser_link: [{ text: 'Resolve', field: 'browserUrl', core: true }],
        get_mutation_status: [{ text: 'Check status of', field: 'mutationRequestId', core: true }],
        whoami: ['Read current user'],
      },
    },
  },
  subBlocks: [
    {
      id: 'operation',
      title: 'Operation',
      type: 'dropdown',
      options: [
        { label: 'List Docs', id: 'list_docs' },
        { label: 'Get Doc', id: 'get_doc' },
        { label: 'Create Doc', id: 'create_doc' },
        { label: 'Update Doc', id: 'update_doc' },
        { label: 'Delete Doc', id: 'delete_doc' },
        { label: 'Publish Doc', id: 'publish_doc' },
        { label: 'Unpublish Doc', id: 'unpublish_doc' },
        { label: 'List Doc Categories', id: 'list_categories' },
        { label: 'List Custom Domains', id: 'list_custom_domains' },
        { label: 'Add Custom Domain', id: 'add_custom_domain' },
        { label: 'Delete Custom Domain', id: 'delete_custom_domain' },
        { label: 'Get Custom Domain Provider', id: 'get_custom_domain_provider' },
        { label: 'List Permissions', id: 'list_permissions' },
        { label: 'Share Doc', id: 'add_permission' },
        { label: 'Remove Permission', id: 'delete_permission' },
        { label: 'Search Users and Groups', id: 'search_principals' },
        { label: 'Get Sharing Metadata', id: 'get_sharing_metadata' },
        { label: 'Get Sharing Settings', id: 'get_acl_settings' },
        { label: 'Update Sharing Settings', id: 'update_acl_settings' },
        { label: 'List Pages', id: 'list_pages' },
        { label: 'Get Page', id: 'get_page' },
        { label: 'Create Page', id: 'create_page' },
        { label: 'Update Page', id: 'update_page' },
        { label: 'Delete Page', id: 'delete_page' },
        { label: 'Get Page Content', id: 'get_page_content' },
        { label: 'Delete Page Content', id: 'delete_page_content' },
        { label: 'Export Page', id: 'export_page' },
        { label: 'Get Page Export Status', id: 'get_page_export_status' },
        { label: 'List Tables', id: 'list_tables' },
        { label: 'Get Table', id: 'get_table' },
        { label: 'List Columns', id: 'list_columns' },
        { label: 'Get Column', id: 'get_column' },
        { label: 'List Rows', id: 'list_rows' },
        { label: 'Get Row', id: 'get_row' },
        { label: 'Insert or Upsert Rows', id: 'upsert_rows' },
        { label: 'Update Row', id: 'update_row' },
        { label: 'Delete Row', id: 'delete_row' },
        { label: 'Delete Rows', id: 'delete_rows' },
        { label: 'Push Button', id: 'push_button' },
        { label: 'List Formulas', id: 'list_formulas' },
        { label: 'Get Formula', id: 'get_formula' },
        { label: 'List Controls', id: 'list_controls' },
        { label: 'Get Control', id: 'get_control' },
        { label: 'Trigger Automation', id: 'trigger_automation' },
        { label: 'List Folders', id: 'list_folders' },
        { label: 'Get Folder', id: 'get_folder' },
        { label: 'Create Folder', id: 'create_folder' },
        { label: 'Update Folder', id: 'update_folder' },
        { label: 'Delete Folder', id: 'delete_folder' },
        { label: 'List Subfolders', id: 'list_folder_children' },
        { label: 'List Workspace Members', id: 'list_workspace_members' },
        { label: 'Change User Role', id: 'change_user_role' },
        { label: 'List Workspace Role Activity', id: 'list_workspace_roles' },
        { label: 'List Doc Analytics', id: 'list_doc_analytics' },
        { label: 'List Page Analytics', id: 'list_page_analytics' },
        { label: 'Get Doc Analytics Summary', id: 'get_doc_analytics_summary' },
        { label: 'Get Analytics Last Updated', id: 'get_analytics_last_updated' },
        { label: 'Resolve Browser Link', id: 'resolve_browser_link' },
        { label: 'Get Mutation Status', id: 'get_mutation_status' },
        { label: 'Get Current User', id: 'whoami' },
      ],
      value: () => 'list_rows',
    },
    {
      id: 'credential',
      title: 'Coda Account',
      type: 'oauth-input',
      serviceId: 'coda',
      credentialKind: 'service-account',
      canonicalParamId: 'oauthCredential',
      mode: 'basic',
      placeholder: 'Select Coda credential',
      required: true,
    },
    {
      id: 'manualCredential',
      title: 'Coda Account',
      type: 'short-input',
      canonicalParamId: 'oauthCredential',
      mode: 'advanced',
      placeholder: 'Enter credential ID',
      required: true,
    },
    {
      id: 'docSelector',
      title: 'Doc',
      canvasNoun: 'a doc',
      type: 'project-selector',
      serviceId: 'coda',
      selectorKey: 'coda.docs',
      canonicalParamId: 'docId',
      placeholder: 'Select a doc',
      dependsOn: ['credential'],
      mode: 'basic',
      condition: { field: 'operation', value: DOC_OPERATIONS },
      required: { field: 'operation', value: DOC_OPERATIONS },
    },
    {
      id: 'manualDocId',
      title: 'Doc ID',
      canvasNoun: 'a doc',
      type: 'short-input',
      canonicalParamId: 'docId',
      placeholder: 'e.g., AbCDeFGH (from the doc URL after _d)',
      mode: 'advanced',
      condition: { field: 'operation', value: DOC_OPERATIONS },
      required: { field: 'operation', value: DOC_OPERATIONS },
    },
    {
      id: 'pageSelector',
      title: 'Page',
      canvasNoun: 'a page',
      type: 'project-selector',
      serviceId: 'coda',
      selectorKey: 'coda.pages',
      canonicalParamId: 'pageId',
      placeholder: 'Select a page',
      dependsOn: ['credential', 'docSelector'],
      mode: 'basic',
      condition: { field: 'operation', value: PAGE_OPERATIONS },
      required: { field: 'operation', value: PAGE_OPERATIONS },
    },
    {
      id: 'manualPageId',
      title: 'Page ID or Name',
      canvasNoun: 'a page',
      type: 'short-input',
      canonicalParamId: 'pageId',
      placeholder: 'e.g., canvas-IjkLmnO',
      mode: 'advanced',
      condition: { field: 'operation', value: PAGE_OPERATIONS },
      required: { field: 'operation', value: PAGE_OPERATIONS },
    },
    {
      id: 'tableSelector',
      title: 'Table',
      canvasNoun: 'a table',
      type: 'project-selector',
      serviceId: 'coda',
      selectorKey: 'coda.tables',
      canonicalParamId: 'tableId',
      placeholder: 'Select a table (inserts need a base table, not a view)',
      dependsOn: ['credential', 'docSelector'],
      mode: 'basic',
      condition: { field: 'operation', value: TABLE_OPERATIONS },
      required: { field: 'operation', value: TABLE_OPERATIONS },
    },
    {
      id: 'manualTableId',
      title: 'Table ID or Name',
      canvasNoun: 'a table',
      type: 'short-input',
      canonicalParamId: 'tableId',
      placeholder: 'e.g., grid-pqRst-U',
      mode: 'advanced',
      condition: { field: 'operation', value: TABLE_OPERATIONS },
      required: { field: 'operation', value: TABLE_OPERATIONS },
    },
    {
      id: 'rowSelector',
      title: 'Row',
      canvasNoun: 'a row',
      type: 'project-selector',
      serviceId: 'coda',
      selectorKey: 'coda.rows',
      canonicalParamId: 'rowId',
      placeholder: 'Select a row',
      dependsOn: ['credential', 'docSelector', 'tableSelector'],
      mode: 'basic',
      condition: { field: 'operation', value: ROW_OPERATIONS },
      required: { field: 'operation', value: ROW_OPERATIONS },
    },
    {
      id: 'manualRowId',
      title: 'Row ID or Name',
      canvasNoun: 'a row',
      type: 'short-input',
      canonicalParamId: 'rowId',
      placeholder: 'e.g., i-tuVwxYz',
      mode: 'advanced',
      condition: { field: 'operation', value: ROW_OPERATIONS },
      required: { field: 'operation', value: ROW_OPERATIONS },
    },
    {
      id: 'columnSelector',
      title: 'Column',
      canvasNoun: 'a column',
      type: 'project-selector',
      serviceId: 'coda',
      selectorKey: 'coda.columns',
      canonicalParamId: 'columnId',
      placeholder: 'Select a column',
      dependsOn: ['credential', 'docSelector', 'tableSelector'],
      mode: 'basic',
      condition: { field: 'operation', value: ['get_column', 'push_button'] },
      required: { field: 'operation', value: ['get_column', 'push_button'] },
    },
    {
      id: 'manualColumnId',
      title: 'Column ID or Name',
      canvasNoun: 'a column',
      type: 'short-input',
      canonicalParamId: 'columnId',
      placeholder: 'e.g., c-tuVwxYz',
      mode: 'advanced',
      condition: { field: 'operation', value: ['get_column', 'push_button'] },
      required: { field: 'operation', value: ['get_column', 'push_button'] },
    },
    {
      id: 'formulaSelector',
      title: 'Formula',
      canvasNoun: 'a formula',
      type: 'project-selector',
      serviceId: 'coda',
      selectorKey: 'coda.formulas',
      canonicalParamId: 'formulaId',
      placeholder: 'Select a named formula',
      dependsOn: ['credential', 'docSelector'],
      mode: 'basic',
      condition: { field: 'operation', value: 'get_formula' },
      required: { field: 'operation', value: 'get_formula' },
    },
    {
      id: 'manualFormulaId',
      title: 'Formula ID or Name',
      canvasNoun: 'a formula',
      type: 'short-input',
      canonicalParamId: 'formulaId',
      placeholder: 'e.g., f-fgHijkLm',
      mode: 'advanced',
      condition: { field: 'operation', value: 'get_formula' },
      required: { field: 'operation', value: 'get_formula' },
    },
    {
      id: 'controlSelector',
      title: 'Control',
      canvasNoun: 'a control',
      type: 'project-selector',
      serviceId: 'coda',
      selectorKey: 'coda.controls',
      canonicalParamId: 'controlId',
      placeholder: 'Select a control',
      dependsOn: ['credential', 'docSelector'],
      mode: 'basic',
      condition: { field: 'operation', value: 'get_control' },
      required: { field: 'operation', value: 'get_control' },
    },
    {
      id: 'manualControlId',
      title: 'Control ID or Name',
      canvasNoun: 'a control',
      type: 'short-input',
      canonicalParamId: 'controlId',
      placeholder: 'e.g., ctrl-cDefGhij',
      mode: 'advanced',
      condition: { field: 'operation', value: 'get_control' },
      required: { field: 'operation', value: 'get_control' },
    },
    {
      id: 'permissionSelector',
      title: 'Permission',
      canvasNoun: 'a permission',
      type: 'project-selector',
      serviceId: 'coda',
      selectorKey: 'coda.permissions',
      canonicalParamId: 'permissionId',
      placeholder: 'Select who to remove',
      dependsOn: ['credential', 'docSelector'],
      mode: 'basic',
      condition: { field: 'operation', value: 'delete_permission' },
      required: { field: 'operation', value: 'delete_permission' },
    },
    {
      id: 'manualPermissionId',
      title: 'Permission ID',
      canvasNoun: 'a permission',
      type: 'short-input',
      canonicalParamId: 'permissionId',
      placeholder: 'Permission ID from List Permissions',
      mode: 'advanced',
      condition: { field: 'operation', value: 'delete_permission' },
      required: { field: 'operation', value: 'delete_permission' },
    },
    {
      id: 'folderSelector',
      title: 'Folder',
      canvasNoun: 'a folder',
      type: 'project-selector',
      serviceId: 'coda',
      selectorKey: 'coda.folders',
      canonicalParamId: 'folderId',
      placeholder: 'Select a folder',
      dependsOn: ['credential'],
      mode: 'basic',
      condition: { field: 'operation', value: FOLDER_OPERATIONS },
      required: { field: 'operation', value: FOLDER_REQUIRED_OPERATIONS },
    },
    {
      id: 'manualFolderId',
      title: 'Folder ID',
      canvasNoun: 'a folder',
      type: 'short-input',
      canonicalParamId: 'folderId',
      placeholder: 'e.g., fl-1Ab234',
      mode: 'advanced',
      condition: { field: 'operation', value: FOLDER_OPERATIONS },
      required: { field: 'operation', value: FOLDER_REQUIRED_OPERATIONS },
    },
    {
      id: 'workspaceId',
      title: 'Workspace ID',
      canvasNoun: 'a workspace',
      type: 'short-input',
      placeholder: 'e.g., ws-1Ab234 (see Get Current User)',
      condition: { field: 'operation', value: WORKSPACE_REQUIRED_OPERATIONS },
      required: { field: 'operation', value: WORKSPACE_REQUIRED_OPERATIONS },
    },
    {
      id: 'docSearch',
      title: 'Search',
      type: 'short-input',
      placeholder: 'Filter docs by name',
      condition: { field: 'operation', value: ['list_docs', 'list_doc_analytics'] },
    },
    {
      id: 'docTitle',
      title: 'Doc Title',
      type: 'short-input',
      placeholder: 'e.g., Project Tracker',
      condition: { field: 'operation', value: ['create_doc', 'update_doc'] },
    },
    {
      id: 'sourceDocSelector',
      title: 'Copy From Doc',
      type: 'project-selector',
      serviceId: 'coda',
      selectorKey: 'coda.docs',
      canonicalParamId: 'sourceDoc',
      placeholder: 'Select a doc to copy',
      dependsOn: ['credential'],
      mode: 'basic',
      condition: { field: 'operation', value: ['create_doc', 'list_docs'] },
    },
    {
      id: 'manualSourceDoc',
      title: 'Copy From Doc ID',
      type: 'short-input',
      canonicalParamId: 'sourceDoc',
      placeholder: 'ID of the source doc',
      mode: 'advanced',
      condition: { field: 'operation', value: ['create_doc', 'list_docs'] },
    },
    {
      id: 'pageName',
      title: 'Page Name',
      type: 'short-input',
      placeholder: 'e.g., Launch Status',
      condition: { field: 'operation', value: PAGE_WRITE_OPERATIONS },
    },
    {
      id: 'parentPageSelector',
      title: 'Parent Page',
      type: 'project-selector',
      serviceId: 'coda',
      selectorKey: 'coda.pages',
      canonicalParamId: 'parentPageId',
      placeholder: 'Create as a subpage of…',
      dependsOn: ['credential', 'docSelector'],
      mode: 'basic',
      condition: { field: 'operation', value: 'create_page' },
    },
    {
      id: 'manualParentPageId',
      title: 'Parent Page ID',
      type: 'short-input',
      canonicalParamId: 'parentPageId',
      placeholder: 'e.g., canvas-tuVwxYz',
      mode: 'advanced',
      condition: { field: 'operation', value: 'create_page' },
    },
    {
      id: 'pageType',
      title: 'Page Type',
      type: 'dropdown',
      options: [
        { label: 'Content (Markdown or HTML)', id: 'canvas' },
        { label: 'Full-page Embed', id: 'embed' },
        { label: 'Sync Page', id: 'syncPage' },
      ],
      value: () => 'canvas',
      condition: { field: 'operation', value: PAGE_CREATE_OPERATIONS },
    },
    {
      id: 'insertionMode',
      title: 'Content Mode',
      type: 'dropdown',
      options: [
        { label: 'Append', id: 'append' },
        { label: 'Prepend', id: 'prepend' },
        { label: 'Replace', id: 'replace' },
      ],
      value: () => 'append',
      condition: { field: 'operation', value: 'update_page' },
    },
    {
      id: 'contentFormat',
      title: 'Content Format',
      type: 'dropdown',
      options: [
        { label: 'Markdown', id: 'markdown' },
        { label: 'HTML', id: 'html' },
      ],
      value: () => 'markdown',
      condition: canvasContentCondition,
    },
    {
      id: 'pageContent',
      title: 'Content',
      type: 'long-input',
      placeholder: '# Heading\n\nPage content in the selected format',
      rows: 8,
      condition: canvasContentCondition,
      wandConfig: {
        enabled: true,
        prompt:
          'Write Coda page content in Markdown based on the user request. Use headings, lists, and short paragraphs. Return ONLY the Markdown content.',
        placeholder: 'Describe the page content...',
      },
    },
    {
      id: 'embedUrl',
      title: 'Embed URL',
      type: 'short-input',
      placeholder: 'https://example.com',
      condition: {
        field: 'operation',
        value: PAGE_CREATE_OPERATIONS,
        and: { field: 'pageType', value: 'embed' },
      },
      required: {
        field: 'operation',
        value: PAGE_CREATE_OPERATIONS,
        and: { field: 'pageType', value: 'embed' },
      },
    },
    {
      id: 'renderMethod',
      title: 'Embed Render Method',
      type: 'dropdown',
      options: [
        { label: 'Standard', id: 'standard' },
        { label: 'Compatibility', id: 'compatibility' },
      ],
      value: () => 'standard',
      condition: {
        field: 'operation',
        value: PAGE_CREATE_OPERATIONS,
        and: { field: 'pageType', value: 'embed' },
      },
      mode: 'advanced',
    },
    {
      id: 'syncSourceDocId',
      title: 'Sync From Doc ID',
      type: 'short-input',
      placeholder: 'ID of the doc to sync from',
      condition: {
        field: 'operation',
        value: PAGE_CREATE_OPERATIONS,
        and: { field: 'pageType', value: 'syncPage' },
      },
      required: {
        field: 'operation',
        value: PAGE_CREATE_OPERATIONS,
        and: { field: 'pageType', value: 'syncPage' },
      },
    },
    {
      id: 'syncMode',
      title: 'Sync',
      type: 'dropdown',
      options: [
        { label: 'A Single Page', id: 'page' },
        { label: 'The Whole Doc', id: 'document' },
      ],
      value: () => 'page',
      condition: {
        field: 'operation',
        value: PAGE_CREATE_OPERATIONS,
        and: { field: 'pageType', value: 'syncPage' },
      },
    },
    {
      id: 'syncSourcePageId',
      title: 'Sync Page ID',
      type: 'short-input',
      placeholder: 'ID of the page to sync',
      required: true,
      condition: (values) =>
        values?.syncMode === 'document'
          ? { field: 'syncMode', value: 'page' }
          : {
              field: 'operation',
              value: PAGE_CREATE_OPERATIONS,
              and: { field: 'pageType', value: 'syncPage' },
            },
    },
    {
      id: 'includeSubpages',
      title: 'Include Subpages',
      type: 'switch',
      condition: {
        field: 'operation',
        value: PAGE_CREATE_OPERATIONS,
        and: { field: 'pageType', value: 'syncPage' },
      },
      mode: 'advanced',
    },
    {
      id: 'elementIds',
      title: 'Element IDs',
      type: 'short-input',
      placeholder: 'Comma-separated element IDs from Get Page Content',
      condition: { field: 'operation', value: 'delete_page_content' },
      wandConfig: {
        enabled: true,
        prompt:
          'Generate a comma-separated list of Coda page element IDs (like cl-lzqh0Q0poT) from the user description. Return ONLY the comma-separated list.',
        placeholder: 'Describe which elements to delete...',
      },
    },
    {
      id: 'deleteAllContent',
      title: 'Delete All Page Content',
      type: 'switch',
      condition: { field: 'operation', value: 'delete_page_content' },
    },
    {
      id: 'outputFormat',
      title: 'Export Format',
      type: 'dropdown',
      options: [
        { label: 'Markdown', id: 'markdown' },
        { label: 'HTML', id: 'html' },
      ],
      required: true,
      value: () => 'markdown',
      condition: { field: 'operation', value: 'export_page' },
    },
    {
      id: 'exportId',
      title: 'Export ID',
      canvasNoun: 'an export',
      type: 'short-input',
      placeholder: 'exportId from Export Page',
      condition: { field: 'operation', value: 'get_page_export_status' },
      required: { field: 'operation', value: 'get_page_export_status' },
    },
    {
      id: 'rowFilter',
      title: 'Filter',
      type: 'short-input',
      placeholder: 'e.g., c-tuVwxYz:"Done" or "Status":"Done"',
      condition: { field: 'operation', value: 'list_rows' },
      wandConfig: {
        enabled: true,
        prompt: `Generate a Coda row filter from the user's description.
The format is <column_id_or_name>:<JSON value>. Column names must be quoted, and string values must be quoted JSON strings.
Examples: c-tuVwxYz:"Apple"  "Status":"Done"  "Priority":3  "Done":true
Return ONLY the filter.`,
        placeholder: 'Describe which rows to return...',
      },
    },
    {
      id: 'useColumnNames',
      title: 'Use Column Names',
      type: 'switch',
      condition: { field: 'operation', value: ['list_rows', 'get_row'] },
    },
    {
      id: 'rows',
      title: 'Rows',
      type: 'code',
      language: 'json',
      placeholder: '[{ "Name": "Apple", "Price": 1.25 }]',
      condition: { field: 'operation', value: 'upsert_rows' },
      required: { field: 'operation', value: 'upsert_rows' },
      wandConfig: {
        enabled: true,
        prompt: `Generate a JSON array of rows for a Coda table based on the user's description.
Each row is an object mapping column IDs (like "c-tuVwxYz") or column names to cell values.
Example: [{"Name": "Apple", "Price": 1.25}, {"Name": "Pear", "Price": 2}]
Return ONLY the JSON array.`,
        placeholder: 'Describe the rows to add...',
        generationType: 'json-object',
      },
    },
    {
      id: 'keyColumns',
      title: 'Upsert Key Columns',
      type: 'short-input',
      placeholder: 'Comma-separated column IDs or names, e.g., c-tuVwxYz',
      condition: { field: 'operation', value: 'upsert_rows' },
      wandConfig: {
        enabled: true,
        prompt:
          'Generate a comma-separated list of Coda column IDs (like c-tuVwxYz) or column names to match existing rows on, from the user description. Return ONLY the comma-separated list.',
        placeholder: 'Describe the columns that identify a row...',
      },
    },
    {
      id: 'cells',
      title: 'Cell Values',
      type: 'code',
      language: 'json',
      placeholder: '{ "Status": "Done" }',
      condition: { field: 'operation', value: 'update_row' },
      required: { field: 'operation', value: 'update_row' },
      wandConfig: {
        enabled: true,
        prompt: `Generate a JSON object of Coda cell updates based on the user's description.
Keys are column IDs (like "c-tuVwxYz") or column names; values are the new cell values.
Example: {"Status": "Done", "Owner": "alex@example.com"}
Return ONLY the JSON object.`,
        placeholder: 'Describe the changes...',
        generationType: 'json-object',
      },
    },
    {
      id: 'rowIds',
      title: 'Row IDs',
      canvasNoun: 'rows',
      type: 'short-input',
      placeholder: 'Comma-separated row IDs, e.g., i-bCdeFgh, i-CdEfgHi',
      condition: { field: 'operation', value: 'delete_rows' },
      required: { field: 'operation', value: 'delete_rows' },
      wandConfig: {
        enabled: true,
        prompt:
          'Generate a comma-separated list of Coda row IDs (like i-bCdeFgh) from the user description. Return ONLY the comma-separated list.',
        placeholder: 'Describe the rows to delete...',
      },
    },
    {
      id: 'ruleId',
      title: 'Automation Rule ID',
      canvasNoun: 'an automation',
      type: 'short-input',
      placeholder: 'e.g., grid-auto-b3Jmey6jBS',
      condition: { field: 'operation', value: 'trigger_automation' },
      required: { field: 'operation', value: 'trigger_automation' },
    },
    {
      id: 'payload',
      title: 'Payload',
      type: 'code',
      language: 'json',
      placeholder: '{ "message": "Hello from Sim" }',
      condition: { field: 'operation', value: 'trigger_automation' },
      wandConfig: {
        enabled: true,
        prompt:
          'Generate a JSON object payload for a Coda webhook automation based on the user description. Return ONLY the JSON object.',
        placeholder: 'Describe the payload...',
        generationType: 'json-object',
      },
    },
    {
      id: 'access',
      title: 'Access',
      type: 'dropdown',
      options: [
        { label: 'Can View', id: 'readonly' },
        { label: 'Can Comment', id: 'comment' },
        { label: 'Can Edit', id: 'write' },
      ],
      required: true,
      value: () => 'readonly',
      condition: { field: 'operation', value: 'add_permission' },
    },
    {
      id: 'principalType',
      title: 'Share With',
      type: 'dropdown',
      options: [
        { label: 'Email', id: 'email' },
        { label: 'Group', id: 'group' },
        { label: 'Domain', id: 'domain' },
        { label: 'Workspace', id: 'workspace' },
        { label: 'Anyone With the Link', id: 'anyone' },
      ],
      required: true,
      value: () => 'email',
      condition: { field: 'operation', value: 'add_permission' },
    },
    {
      id: 'principal',
      title: 'Email, Group ID, Domain, or Workspace ID',
      canvasNoun: 'someone',
      type: 'short-input',
      placeholder: 'e.g., teammate@example.com',
      condition: {
        field: 'operation',
        value: 'add_permission',
        and: { field: 'principalType', value: 'anyone', not: true },
      },
      required: {
        field: 'operation',
        value: 'add_permission',
        and: { field: 'principalType', value: 'anyone', not: true },
      },
    },
    {
      id: 'principalQuery',
      title: 'Search',
      type: 'short-input',
      placeholder: 'Name or email',
      condition: { field: 'operation', value: 'search_principals' },
    },
    {
      id: 'slug',
      title: 'URL Slug',
      type: 'short-input',
      placeholder: 'e.g., my-doc',
      condition: { field: 'operation', value: 'publish_doc' },
    },
    {
      id: 'publishMode',
      title: 'Viewer Mode',
      type: 'dropdown',
      options: [
        { label: 'Unchanged', id: 'unchanged' },
        { label: 'View Only', id: 'view' },
        { label: 'Play (Interact Without Saving)', id: 'play' },
        { label: 'Edit', id: 'edit' },
      ],
      value: () => 'unchanged',
      condition: { field: 'operation', value: 'publish_doc' },
    },
    {
      id: 'discoverable',
      title: 'Discoverable',
      type: 'dropdown',
      options: TRI_STATE_OPTIONS,
      value: () => 'unchanged',
      condition: { field: 'operation', value: 'publish_doc' },
      mode: 'advanced',
    },
    {
      id: 'categoryNames',
      title: 'Categories',
      type: 'short-input',
      placeholder: 'Comma-separated names from List Doc Categories',
      condition: { field: 'operation', value: 'publish_doc' },
      mode: 'advanced',
      wandConfig: {
        enabled: true,
        prompt:
          'Generate a comma-separated list of Coda doc category names (like Project management) from the user description. Return ONLY the comma-separated list.',
        placeholder: 'Describe the categories...',
      },
    },
    {
      id: 'allowEditorsToChangePermissions',
      title: 'Editors Can Change Permissions',
      type: 'dropdown',
      options: TRI_STATE_OPTIONS,
      value: () => 'unchanged',
      condition: { field: 'operation', value: 'update_acl_settings' },
    },
    {
      id: 'allowCopying',
      title: 'Viewers Can Copy',
      type: 'dropdown',
      options: TRI_STATE_OPTIONS,
      value: () => 'unchanged',
      condition: { field: 'operation', value: 'update_acl_settings' },
    },
    {
      id: 'allowViewersToRequestEditing',
      title: 'Viewers Can Request Editing',
      type: 'dropdown',
      options: TRI_STATE_OPTIONS,
      value: () => 'unchanged',
      condition: { field: 'operation', value: 'update_acl_settings' },
    },
    {
      id: 'customDocDomain',
      title: 'Custom Domain',
      canvasNoun: 'a domain',
      type: 'short-input',
      placeholder: 'e.g., docs.example.com',
      condition: {
        field: 'operation',
        value: ['add_custom_domain', 'delete_custom_domain', 'get_custom_domain_provider'],
      },
      required: {
        field: 'operation',
        value: ['add_custom_domain', 'delete_custom_domain', 'get_custom_domain_provider'],
      },
    },
    {
      id: 'folderName',
      title: 'Folder Name',
      canvasNoun: 'a folder',
      type: 'short-input',
      placeholder: 'e.g., Projects',
      condition: { field: 'operation', value: ['create_folder', 'update_folder'] },
      required: { field: 'operation', value: 'create_folder' },
    },
    {
      id: 'folderDescription',
      title: 'Folder Description',
      type: 'long-input',
      placeholder: 'What the folder contains',
      condition: { field: 'operation', value: ['create_folder', 'update_folder'] },
    },
    {
      id: 'memberEmail',
      title: 'Member Email',
      canvasNoun: 'a member',
      type: 'short-input',
      placeholder: 'teammate@example.com',
      condition: { field: 'operation', value: 'change_user_role' },
      required: { field: 'operation', value: 'change_user_role' },
    },
    {
      id: 'newRole',
      title: 'New Role',
      type: 'dropdown',
      options: [
        { label: 'Doc Maker', id: 'DocMaker' },
        { label: 'Editor', id: 'Editor' },
        { label: 'Admin', id: 'Admin' },
      ],
      required: true,
      value: () => 'DocMaker',
      condition: { field: 'operation', value: 'change_user_role' },
    },
    {
      id: 'browserUrl',
      title: 'Coda URL',
      canvasNoun: 'a link',
      type: 'short-input',
      placeholder: 'https://coda.io/d/_dAbCDeFGH/Launch-Status_sumnO',
      condition: { field: 'operation', value: 'resolve_browser_link' },
      required: { field: 'operation', value: 'resolve_browser_link' },
    },
    {
      id: 'mutationRequestId',
      title: 'Request ID',
      canvasNoun: 'a change',
      type: 'short-input',
      placeholder: 'requestId returned by a write operation',
      condition: { field: 'operation', value: 'get_mutation_status' },
      required: { field: 'operation', value: 'get_mutation_status' },
    },
    {
      id: 'workspaceFilter',
      title: 'Workspace ID',
      type: 'short-input',
      placeholder: 'Only include this workspace, e.g., ws-1Ab234',
      condition: { field: 'operation', value: WORKSPACE_FILTER_OPERATIONS },
      mode: 'advanced',
    },
    {
      id: 'isOwner',
      title: 'Only Docs I Own',
      type: 'switch',
      condition: { field: 'operation', value: 'list_docs' },
      mode: 'advanced',
    },
    {
      id: 'isPublished',
      title: 'Only Published Docs',
      type: 'switch',
      condition: {
        field: 'operation',
        value: ['list_docs', 'list_doc_analytics', 'get_doc_analytics_summary'],
      },
      mode: 'advanced',
    },
    {
      id: 'starred',
      title: 'Starred',
      type: 'dropdown',
      options: [
        { label: 'Any', id: 'any' },
        { label: 'Starred Only', id: 'true' },
        { label: 'Not Starred', id: 'false' },
      ],
      value: () => 'any',
      condition: { field: 'operation', value: ['list_docs', 'list_folders'] },
      mode: 'advanced',
    },
    {
      id: 'inGallery',
      title: 'Only Gallery Docs',
      type: 'switch',
      condition: { field: 'operation', value: 'list_docs' },
      mode: 'advanced',
    },
    {
      id: 'timezone',
      title: 'Timezone',
      type: 'short-input',
      placeholder: 'e.g., America/Los_Angeles',
      condition: { field: 'operation', value: 'create_doc' },
      mode: 'advanced',
    },
    {
      id: 'pageSubtitle',
      title: 'Page Subtitle',
      type: 'short-input',
      condition: { field: 'operation', value: PAGE_WRITE_OPERATIONS },
      mode: 'advanced',
    },
    {
      id: 'iconName',
      title: 'Icon Name',
      type: 'short-input',
      placeholder: 'e.g., rocket',
      condition: { field: 'operation', value: ['update_doc', ...PAGE_WRITE_OPERATIONS] },
      mode: 'advanced',
    },
    {
      id: 'imageUrl',
      title: 'Cover Image URL',
      type: 'short-input',
      placeholder: 'https://example.com/image.jpg',
      condition: { field: 'operation', value: PAGE_WRITE_OPERATIONS },
      mode: 'advanced',
    },
    {
      id: 'elementId',
      title: 'Anchor Element ID',
      type: 'short-input',
      placeholder: 'e.g., cl-lzqh0Q0poT (from Get Page Content)',
      condition: { field: 'operation', value: 'update_page' },
      mode: 'advanced',
    },
    {
      id: 'pageVisibility',
      title: 'Page Visibility',
      type: 'dropdown',
      options: [
        { label: 'Unchanged', id: 'unchanged' },
        { label: 'Visible', id: 'visible' },
        { label: 'Hidden', id: 'hidden' },
      ],
      value: () => 'unchanged',
      condition: { field: 'operation', value: 'update_page' },
      mode: 'advanced',
    },
    {
      id: 'tableTypes',
      title: 'Table Types',
      type: 'dropdown',
      options: [
        { label: 'All', id: 'all' },
        { label: 'Tables Only', id: 'table' },
        { label: 'Views Only', id: 'view' },
        { label: 'Databases Only', id: 'database' },
      ],
      value: () => 'all',
      condition: { field: 'operation', value: 'list_tables' },
      mode: 'advanced',
    },
    {
      id: 'listSortBy',
      title: 'Sort By',
      type: 'dropdown',
      options: [
        { label: 'Default', id: 'default' },
        { label: 'Name', id: 'name' },
      ],
      value: () => 'default',
      condition: { field: 'operation', value: LIST_SORT_OPERATIONS },
      mode: 'advanced',
    },
    {
      id: 'useUpdatedTableLayouts',
      title: 'Distinguish Detail and Form Layouts',
      type: 'switch',
      condition: { field: 'operation', value: 'get_table' },
      mode: 'advanced',
    },
    {
      id: 'rowSortBy',
      title: 'Sort By',
      type: 'dropdown',
      options: [
        { label: 'Created At', id: 'createdAt' },
        { label: 'Updated At', id: 'updatedAt' },
        { label: 'View Order', id: 'natural' },
      ],
      value: () => 'createdAt',
      condition: { field: 'operation', value: 'list_rows' },
      mode: 'advanced',
    },
    {
      id: 'valueFormat',
      title: 'Value Format',
      type: 'dropdown',
      options: [
        { label: 'Simple', id: 'simple' },
        { label: 'Simple With Arrays', id: 'simpleWithArrays' },
        { label: 'Rich', id: 'rich' },
      ],
      value: () => 'simple',
      condition: { field: 'operation', value: ['list_rows', 'get_row'] },
      mode: 'advanced',
    },
    {
      id: 'visibleOnly',
      title: 'Visible Only',
      type: 'switch',
      condition: { field: 'operation', value: ['list_rows', 'list_columns'] },
      mode: 'advanced',
    },
    {
      id: 'syncToken',
      title: 'Sync Token',
      type: 'short-input',
      placeholder: 'nextSyncToken from a previous List Rows',
      condition: { field: 'operation', value: 'list_rows' },
      mode: 'advanced',
    },
    {
      id: 'disableParsing',
      title: 'Disable Value Parsing',
      type: 'switch',
      condition: { field: 'operation', value: ['upsert_rows', 'update_row'] },
      mode: 'advanced',
    },
    {
      id: 'suppressEmail',
      title: 'Skip Notification Email',
      type: 'switch',
      condition: { field: 'operation', value: 'add_permission' },
      mode: 'advanced',
    },
    {
      id: 'degradeGracefully',
      title: 'Resolve Nearest Parent If Deleted',
      type: 'switch',
      condition: { field: 'operation', value: 'resolve_browser_link' },
      mode: 'advanced',
    },
    {
      id: 'includedRoles',
      title: 'Roles',
      type: 'short-input',
      placeholder: 'Comma-separated: Admin, DocMaker, Editor',
      condition: { field: 'operation', value: 'list_workspace_members' },
      mode: 'advanced',
      wandConfig: {
        enabled: true,
        prompt:
          'Generate a comma-separated list of Coda workspace roles using only Admin, DocMaker, and Editor, from the user description. Return ONLY the comma-separated list.',
        placeholder: 'Describe which roles to include...',
      },
    },
    {
      id: 'docIds',
      title: 'Doc IDs',
      type: 'short-input',
      placeholder: 'Comma-separated doc IDs',
      condition: { field: 'operation', value: 'list_doc_analytics' },
      mode: 'advanced',
      wandConfig: {
        enabled: true,
        prompt:
          'Generate a comma-separated list of Coda doc IDs (like AbCDeFGH) from the user description. Return ONLY the comma-separated list.',
        placeholder: 'Describe the docs...',
      },
    },
    {
      id: 'sinceDate',
      title: 'Since Date',
      type: 'short-input',
      placeholder: 'YYYY-MM-DD',
      condition: { field: 'operation', value: ANALYTICS_DATE_OPERATIONS },
      mode: 'advanced',
      wandConfig: DATE_WAND,
    },
    {
      id: 'untilDate',
      title: 'Until Date',
      type: 'short-input',
      placeholder: 'YYYY-MM-DD',
      condition: { field: 'operation', value: ANALYTICS_DATE_OPERATIONS },
      mode: 'advanced',
      wandConfig: DATE_WAND,
    },
    {
      id: 'analyticsScale',
      title: 'Scale',
      type: 'dropdown',
      options: [
        { label: 'Daily', id: 'daily' },
        { label: 'Cumulative', id: 'cumulative' },
      ],
      value: () => 'daily',
      condition: { field: 'operation', value: 'list_doc_analytics' },
      mode: 'advanced',
    },
    {
      id: 'analyticsOrderBy',
      title: 'Order By',
      type: 'dropdown',
      options: [
        { label: 'Default', id: 'default' },
        { label: 'Date', id: 'date' },
        { label: 'Title', id: 'title' },
        { label: 'Views', id: 'views' },
        { label: 'Total Sessions', id: 'totalSessions' },
        { label: 'Copies', id: 'copies' },
        { label: 'Likes', id: 'likes' },
        { label: 'AI Credits', id: 'aiCredits' },
        { label: 'Created At', id: 'createdAt' },
        { label: 'Published At', id: 'publishedAt' },
      ],
      value: () => 'default',
      condition: { field: 'operation', value: 'list_doc_analytics' },
      mode: 'advanced',
    },
    {
      id: 'analyticsDirection',
      title: 'Direction',
      type: 'dropdown',
      options: [
        { label: 'Default', id: 'default' },
        { label: 'Descending', id: 'descending' },
        { label: 'Ascending', id: 'ascending' },
      ],
      value: () => 'default',
      condition: { field: 'operation', value: 'list_doc_analytics' },
      mode: 'advanced',
    },
    {
      id: 'limit',
      title: 'Limit',
      type: 'short-input',
      placeholder: 'Maximum results per page',
      condition: { field: 'operation', value: LIMIT_OPERATIONS },
      mode: 'advanced',
    },
    {
      id: 'pageToken',
      title: 'Page Token',
      type: 'short-input',
      placeholder: 'nextPageToken from a previous call',
      condition: { field: 'operation', value: PAGE_TOKEN_OPERATIONS },
      mode: 'advanced',
    },
  ],
  tools: {
    access: [
      'coda_add_custom_domain',
      'coda_add_permission',
      'coda_change_user_role',
      'coda_create_doc',
      'coda_create_folder',
      'coda_create_page',
      'coda_delete_custom_domain',
      'coda_delete_doc',
      'coda_delete_folder',
      'coda_delete_page',
      'coda_delete_page_content',
      'coda_delete_permission',
      'coda_delete_row',
      'coda_delete_rows',
      'coda_export_page',
      'coda_get_acl_settings',
      'coda_get_analytics_last_updated',
      'coda_get_column',
      'coda_get_control',
      'coda_get_custom_domain_provider',
      'coda_get_doc',
      'coda_get_doc_analytics_summary',
      'coda_get_folder',
      'coda_get_formula',
      'coda_get_mutation_status',
      'coda_get_page',
      'coda_get_page_content',
      'coda_get_page_export_status',
      'coda_get_row',
      'coda_get_sharing_metadata',
      'coda_get_table',
      'coda_list_categories',
      'coda_list_columns',
      'coda_list_controls',
      'coda_list_custom_domains',
      'coda_list_doc_analytics',
      'coda_list_docs',
      'coda_list_folder_children',
      'coda_list_folders',
      'coda_list_formulas',
      'coda_list_page_analytics',
      'coda_list_pages',
      'coda_list_permissions',
      'coda_list_rows',
      'coda_list_tables',
      'coda_list_workspace_members',
      'coda_list_workspace_roles',
      'coda_publish_doc',
      'coda_push_button',
      'coda_resolve_browser_link',
      'coda_search_principals',
      'coda_trigger_automation',
      'coda_unpublish_doc',
      'coda_update_acl_settings',
      'coda_update_doc',
      'coda_update_folder',
      'coda_update_page',
      'coda_update_row',
      'coda_upsert_rows',
      'coda_whoami',
    ],
    config: {
      tool: (params) => `coda_${params.operation || 'list_rows'}`,
      params: (params) => {
        const operation = params.operation
        const isFolderWrite = operation === 'create_folder' || operation === 'update_folder'
        const pageVisibility = params.pageVisibility
        return {
          query:
            operation === 'list_rows'
              ? params.rowFilter
              : operation === 'search_principals'
                ? params.principalQuery
                : params.docSearch,
          title: params.docTitle,
          name: isFolderWrite
            ? params.folderName
            : operation === 'create_doc'
              ? undefined
              : params.pageName,
          description: isFolderWrite ? params.folderDescription : undefined,
          subtitle: operation === 'create_doc' ? undefined : params.pageSubtitle,
          content: params.pageContent,
          sourceDocId: params.syncSourceDocId,
          sourcePageId: params.syncSourcePageId,
          includeSubpages: trueOrUndefined(params.includeSubpages),
          isHidden:
            pageVisibility === 'hidden' ? true : pageVisibility === 'visible' ? false : undefined,
          workspaceId: WORKSPACE_REQUIRED_OPERATIONS.includes(operation)
            ? params.workspaceId
            : params.workspaceFilter,
          email: params.memberEmail,
          requestId: params.mutationRequestId,
          url: params.browserUrl,
          sortBy:
            operation === 'list_rows'
              ? params.rowSortBy
              : params.listSortBy === 'name'
                ? 'name'
                : undefined,
          tableTypes: unlessDefault(params.tableTypes, 'all'),
          mode: unlessDefault(params.publishMode, 'unchanged'),
          discoverable: triState(params.discoverable),
          allowEditorsToChangePermissions: triState(params.allowEditorsToChangePermissions),
          allowCopying: triState(params.allowCopying),
          allowViewersToRequestEditing: triState(params.allowViewersToRequestEditing),
          isStarred: triState(params.starred),
          scale: unlessDefault(params.analyticsScale, 'daily'),
          orderBy: unlessDefault(params.analyticsOrderBy, 'default'),
          direction: unlessDefault(params.analyticsDirection, 'default'),
          limit: optionalNumber(params.limit),
          deleteAll: trueOrUndefined(params.deleteAllContent),
          isOwner: trueOrUndefined(params.isOwner),
          isPublished: trueOrUndefined(params.isPublished),
          inGallery: trueOrUndefined(params.inGallery),
          useColumnNames: trueOrUndefined(params.useColumnNames),
          useUpdatedTableLayouts: trueOrUndefined(params.useUpdatedTableLayouts),
          visibleOnly: trueOrUndefined(params.visibleOnly),
          disableParsing: trueOrUndefined(params.disableParsing),
          suppressEmail: trueOrUndefined(params.suppressEmail),
          degradeGracefully: trueOrUndefined(params.degradeGracefully),
        }
      },
    },
  },
  inputs: {
    operation: { type: 'string', description: 'Operation to perform' },
    oauthCredential: { type: 'string', description: 'Coda API-token credential' },
    docId: { type: 'string', description: 'Doc ID' },
    pageId: { type: 'string', description: 'Page ID or name' },
    tableId: { type: 'string', description: 'Table or view ID or name' },
    rowId: { type: 'string', description: 'Row ID or name' },
    columnId: { type: 'string', description: 'Column ID or name' },
    formulaId: { type: 'string', description: 'Formula ID or name' },
    controlId: { type: 'string', description: 'Control ID or name' },
    permissionId: { type: 'string', description: 'Permission ID' },
    folderId: { type: 'string', description: 'Folder ID' },
    workspaceId: { type: 'string', description: 'Workspace ID' },
    docSearch: { type: 'string', description: 'Search term to filter docs' },
    docTitle: { type: 'string', description: 'Doc title' },
    sourceDoc: { type: 'string', description: 'Doc ID to copy, or to filter copies of' },
    pageName: { type: 'string', description: 'Page name' },
    parentPageId: { type: 'string', description: 'Parent page ID for a subpage' },
    pageType: { type: 'string', description: 'canvas, embed, or syncPage' },
    insertionMode: { type: 'string', description: 'append, prepend, or replace' },
    contentFormat: { type: 'string', description: 'markdown or html' },
    pageContent: { type: 'string', description: 'Page content' },
    embedUrl: { type: 'string', description: 'URL to embed as a page' },
    renderMethod: { type: 'string', description: 'standard or compatibility embed rendering' },
    syncSourceDocId: { type: 'string', description: 'Doc to sync a page from' },
    syncMode: { type: 'string', description: 'page or document sync' },
    syncSourcePageId: { type: 'string', description: 'Page to sync' },
    includeSubpages: { type: 'boolean', description: 'Include subpages in a sync page' },
    elementIds: { type: 'string', description: 'Page element IDs to delete' },
    deleteAllContent: { type: 'boolean', description: 'Delete all content from the page' },
    outputFormat: { type: 'string', description: 'Export format (markdown or html)' },
    exportId: { type: 'string', description: 'Page export ID' },
    rowFilter: { type: 'string', description: 'Row filter as column:value' },
    useColumnNames: { type: 'boolean', description: 'Key values by column name' },
    rows: { type: 'json', description: 'Rows to insert or upsert' },
    keyColumns: { type: 'string', description: 'Upsert key columns' },
    cells: { type: 'json', description: 'Cell values to update' },
    rowIds: { type: 'string', description: 'Row IDs to delete' },
    ruleId: { type: 'string', description: 'Automation rule ID' },
    payload: { type: 'json', description: 'Automation payload' },
    access: { type: 'string', description: 'Access level to grant' },
    principalType: { type: 'string', description: 'Type of principal to share with' },
    principal: { type: 'string', description: 'Email, group ID, domain, or workspace ID' },
    principalQuery: { type: 'string', description: 'User or group search term' },
    slug: { type: 'string', description: 'Published doc URL slug' },
    publishMode: { type: 'string', description: 'Published doc viewer mode' },
    discoverable: { type: 'string', description: 'Published doc discoverability' },
    categoryNames: { type: 'string', description: 'Published doc categories' },
    allowEditorsToChangePermissions: {
      type: 'string',
      description: 'Whether editors can change permissions',
    },
    allowCopying: { type: 'string', description: 'Whether viewers can copy' },
    allowViewersToRequestEditing: {
      type: 'string',
      description: 'Whether viewers can request editing',
    },
    customDocDomain: { type: 'string', description: 'Custom domain' },
    folderName: { type: 'string', description: 'Folder name' },
    folderDescription: { type: 'string', description: 'Folder description' },
    memberEmail: { type: 'string', description: 'Workspace member email' },
    newRole: { type: 'string', description: 'New workspace role' },
    browserUrl: { type: 'string', description: 'Coda browser link to resolve' },
    mutationRequestId: { type: 'string', description: 'Request ID of a write operation' },
    workspaceFilter: { type: 'string', description: 'Workspace ID filter' },
    isOwner: { type: 'boolean', description: 'Only docs owned by the user' },
    isPublished: { type: 'boolean', description: 'Only published docs' },
    starred: { type: 'string', description: 'Starred filter' },
    inGallery: { type: 'boolean', description: 'Only gallery docs' },
    timezone: { type: 'string', description: 'Timezone for a new doc' },
    pageSubtitle: { type: 'string', description: 'Page subtitle' },
    iconName: { type: 'string', description: 'Icon name' },
    imageUrl: { type: 'string', description: 'Cover image URL' },
    elementId: { type: 'string', description: 'Page element to insert relative to' },
    pageVisibility: { type: 'string', description: 'unchanged, visible, or hidden' },
    tableTypes: { type: 'string', description: 'Table types to list' },
    listSortBy: { type: 'string', description: 'Sort order for tables, formulas, controls' },
    useUpdatedTableLayouts: { type: 'boolean', description: 'Report detail and form layouts' },
    rowSortBy: { type: 'string', description: 'Row sort order' },
    valueFormat: { type: 'string', description: 'Cell value format' },
    visibleOnly: { type: 'boolean', description: 'Only visible rows or columns' },
    syncToken: { type: 'string', description: 'Sync token for incremental row reads' },
    disableParsing: { type: 'boolean', description: 'Store values without parsing' },
    suppressEmail: { type: 'boolean', description: 'Skip the sharing notification email' },
    degradeGracefully: { type: 'boolean', description: 'Resolve nearest parent if deleted' },
    includedRoles: { type: 'string', description: 'Workspace roles to include' },
    docIds: { type: 'string', description: 'Doc IDs for analytics' },
    sinceDate: { type: 'string', description: 'Analytics start date' },
    untilDate: { type: 'string', description: 'Analytics end date' },
    analyticsScale: { type: 'string', description: 'daily or cumulative analytics' },
    analyticsOrderBy: { type: 'string', description: 'Analytics sort field' },
    analyticsDirection: { type: 'string', description: 'Analytics sort direction' },
    limit: { type: 'number', description: 'Maximum results per page' },
    pageToken: { type: 'string', description: 'Pagination token' },
  },
  outputs: {
    docs: {
      type: 'json',
      description:
        'Docs (id, name, href, browserLink, icon, owner, ownerName, createdAt, updatedAt, workspace, folder, sourceDoc, docSize, published)',
    },
    doc: {
      type: 'json',
      description:
        'Doc (id, name, href, browserLink, icon, owner, ownerName, createdAt, updatedAt, workspace {id, name, organizationId}, folder {id, name}, sourceDoc, docSize {totalRowCount, tableAndViewCount, baseTableCount, pageCount, overApiSizeLimit}, published {description, browserLink, discoverable, mode, categories})',
    },
    docId: { type: 'string', description: 'ID of the affected doc' },
    categories: { type: 'json', description: 'Doc category names' },
    requestId: {
      type: 'string',
      description: 'Request ID of a queued change, for Get Mutation Status',
    },
    customDomains: {
      type: 'json',
      description:
        'Custom domains (customDocDomain, hasCertificate, hasDnsDocId, setupStatus, domainStatus, lastVerifiedTimestamp)',
    },
    customDocDomain: { type: 'string', description: 'Custom domain' },
    provider: { type: 'string', description: 'DNS provider of a custom domain' },
    permissions: {
      type: 'json',
      description:
        'Permissions (id, access, principal {type, email, groupId, groupName, domain, workspaceId})',
    },
    access: { type: 'string', description: 'Access level granted' },
    principalType: { type: 'string', description: 'Type of principal the doc was shared with' },
    permissionId: { type: 'string', description: 'ID of the removed permission' },
    users: { type: 'json', description: 'Matching users (name, loginId, pictureLink)' },
    groups: { type: 'json', description: 'Matching groups (groupId, groupName)' },
    canShare: { type: 'boolean', description: 'Whether the user can share the doc' },
    canShareWithWorkspace: {
      type: 'boolean',
      description: 'Whether the user can share with the workspace',
    },
    canShareWithOrg: { type: 'boolean', description: 'Whether the user can share with the org' },
    canCopy: { type: 'boolean', description: 'Whether the user can copy the doc' },
    allowEditorsToChangePermissions: {
      type: 'boolean',
      description: 'Whether editors can change permissions',
    },
    allowCopying: { type: 'boolean', description: 'Whether viewers can copy the doc' },
    allowViewersToRequestEditing: {
      type: 'boolean',
      description: 'Whether viewers can request editing',
    },
    pages: {
      type: 'json',
      description:
        'Pages (id, name, subtitle, browserLink, contentType, isHidden, icon, image, parent, children, authors, createdAt, updatedAt)',
    },
    page: {
      type: 'json',
      description:
        'Page (id, name, subtitle, href, browserLink, contentType, isHidden, isEffectivelyHidden, icon, image, parent, children, authors, createdAt, createdBy, updatedAt, updatedBy)',
    },
    pageId: { type: 'string', description: 'ID of the created, updated, or deleted page' },
    items: {
      type: 'json',
      description:
        'Page content lines (id, type, style, format, content, lineLevel), or analytics items (doc or page plus daily metrics)',
    },
    exportId: { type: 'string', description: 'Page export ID' },
    status: { type: 'string', description: 'Page export status (inProgress, failed, complete)' },
    href: { type: 'string', description: 'API link reporting the page export status' },
    downloadLink: { type: 'string', description: 'Download link of a completed page export' },
    exportError: { type: 'string', description: 'Error message of a failed page export' },
    tables: {
      type: 'json',
      description: 'Tables and views (id, name, tableType, href, browserLink, parent)',
    },
    table: {
      type: 'json',
      description:
        'Table (id, name, tableType, browserLink, parent, parentTable, displayColumnId, rowCount, sorts, layout, filter, createdAt, updatedAt)',
    },
    columns: {
      type: 'json',
      description: 'Columns (id, name, display, calculated, formula, defaultValue, format)',
    },
    column: {
      type: 'json',
      description:
        'Column (id, name, display, calculated, formula, defaultValue, format, parentTable)',
    },
    rows: {
      type: 'json',
      description: 'Rows (id, name, index, browserLink, createdAt, updatedAt, values)',
    },
    row: {
      type: 'json',
      description: 'Row (id, name, index, browserLink, createdAt, updatedAt, values, parentTable)',
    },
    nextSyncToken: { type: 'string', description: 'Token for reading only rows changed later' },
    addedRowIds: { type: 'json', description: 'IDs of rows that will be added' },
    rowId: { type: 'string', description: 'ID of the affected row' },
    rowIds: { type: 'json', description: 'IDs of rows queued for deletion' },
    columnId: { type: 'string', description: 'ID of the pushed button column' },
    formulas: { type: 'json', description: 'Named formulas (id, name, href, parent)' },
    formula: { type: 'json', description: 'Formula (id, name, href, parent, value)' },
    controls: { type: 'json', description: 'Controls (id, name, href, parent)' },
    control: {
      type: 'json',
      description: 'Control (id, name, href, parent, controlType, value)',
    },
    folders: {
      type: 'json',
      description:
        'Folders (id, name, browserLink, description, icon, iconColor, createdAt, canEdit, workspace)',
    },
    folder: {
      type: 'json',
      description:
        'Folder (id, name, browserLink, description, icon, iconColor, createdAt, canEdit, workspace)',
    },
    folderId: { type: 'string', description: 'ID of the deleted folder' },
    children: {
      type: 'json',
      description: 'Subfolders (id, name, browserLink, visibility, workspace, ...)',
    },
    members: {
      type: 'json',
      description:
        'Workspace members (email, name, role, registeredAt, roleChangedAt, lastActiveAt, ownedDocs, totalDocs, ...)',
    },
    email: { type: 'string', description: 'Email of the member whose role changed' },
    newRole: { type: 'string', description: 'Role assigned' },
    roleChangedAt: { type: 'string', description: 'When the role change took effect' },
    roleActivity: {
      type: 'json',
      description:
        'Monthly role counts (month, activeAdminCount, activeDocMakerCount, activeEditorCount, inactive counts)',
    },
    totalSessions: { type: 'number', description: 'Total sessions across matching docs' },
    docAnalyticsLastUpdated: { type: 'string', description: 'Date doc analytics last updated' },
    packAnalyticsLastUpdated: {
      type: 'string',
      description: 'Date Pack analytics last updated',
    },
    packFormulaAnalyticsLastUpdated: {
      type: 'string',
      description: 'Date Pack formula analytics last updated',
    },
    browserLink: { type: 'string', description: 'Canonical browser link of a resolved resource' },
    resource: { type: 'json', description: 'Resolved resource (type, id, name, href)' },
    completed: { type: 'boolean', description: 'Whether a queued change was applied' },
    warning: { type: 'string', description: 'Warning for a change that completed with caveats' },
    name: { type: 'string', description: 'Name of the token owner' },
    loginId: { type: 'string', description: 'Email of the token owner' },
    pictureLink: { type: 'string', description: 'Avatar link of the token owner' },
    scoped: { type: 'boolean', description: 'Whether the token is restricted' },
    tokenName: { type: 'string', description: 'Name of the API token' },
    workspace: {
      type: 'json',
      description: 'Default workspace of the token owner (id, name, organizationId, browserLink)',
    },
    nextPageToken: { type: 'string', description: 'Token for fetching the next page of results' },
  },
}

export const CodaBlockMeta = {
  tags: ['note-taking', 'knowledge-base', 'spreadsheet', 'project-management', 'automation'],
  url: 'https://coda.io',
  templates: [
    {
      icon: CodaIcon,
      title: 'Coda meeting notes publisher',
      prompt:
        'Build a workflow that takes a meeting transcript, has an agent write a summary with decisions and action items, creates a Coda page for the meeting in the team doc, and inserts each action item as a row in the Coda tasks table with owner and due date.',
      modules: ['agent', 'workflows'],
      category: 'productivity',
      tags: ['meetings', 'automation'],
      featured: true,
    },
    {
      icon: CodaIcon,
      title: 'Coda OKR progress report',
      prompt:
        'Create a scheduled workflow that reads the OKR table in a Coda doc every Friday, computes progress per objective from the key result rows, and appends a weekly progress summary to the OKR review page in Markdown.',
      modules: ['scheduled', 'agent', 'workflows'],
      category: 'operations',
      tags: ['reporting', 'planning'],
    },
    {
      icon: CodaIcon,
      title: 'Coda CRM lead upsert',
      prompt:
        'Build a workflow that receives new leads from a form webhook, has an agent normalize company and contact fields, and upserts each lead into a Coda CRM table keyed on email so repeat submissions update the existing row.',
      modules: ['agent', 'workflows'],
      category: 'sales',
      tags: ['crm', 'sync'],
    },
    {
      icon: CodaIcon,
      title: 'Coda bug tracker triage',
      prompt:
        'Create a workflow that lists new rows in a Coda bug tracker table, has an agent classify severity and suggest an owner for each bug, updates the rows with the triage fields, and posts the high-severity bugs to Slack.',
      modules: ['agent', 'workflows'],
      category: 'engineering',
      tags: ['triage', 'automation'],
      alsoIntegrations: ['slack'],
    },
    {
      icon: CodaIcon,
      title: 'Coda wiki to knowledge base',
      prompt:
        'Build a scheduled workflow that lists the pages of a Coda team wiki doc, reads each page as text, and syncs the content into a Sim knowledge base so agents can answer questions from the wiki.',
      modules: ['scheduled', 'knowledge-base', 'workflows'],
      category: 'productivity',
      tags: ['knowledge', 'sync'],
    },
    {
      icon: CodaIcon,
      title: 'Coda table to Sim table mirror',
      prompt:
        'Create a scheduled workflow that reads rows changed since the last run from a Coda table using its sync token and mirrors them into a Sim table for reporting and downstream agent runs.',
      modules: ['scheduled', 'tables', 'workflows'],
      category: 'operations',
      tags: ['sync', 'data'],
    },
    {
      icon: CodaIcon,
      title: 'Coda project status digest',
      prompt:
        'Build a scheduled workflow that reads the project tracker table in a Coda doc each morning, has an agent flag overdue and blocked projects, and emails a status digest to project leads with links to each row.',
      modules: ['scheduled', 'agent', 'workflows'],
      category: 'operations',
      tags: ['reporting', 'project-management'],
      alsoIntegrations: ['gmail'],
    },
    {
      icon: CodaIcon,
      title: 'Coda doc access audit',
      prompt:
        'Create a scheduled workflow that lists the Coda docs in a workspace, reads the sharing permissions and sharing settings on each, and writes any docs shared with anyone or outside domains to an audit table for review.',
      modules: ['scheduled', 'tables', 'agent', 'workflows'],
      category: 'operations',
      tags: ['security', 'audit'],
    },
    {
      icon: CodaIcon,
      title: 'Coda doc engagement report',
      prompt:
        'Build a scheduled workflow that pulls last week of Coda doc analytics, ranks docs by sessions and views, and posts the most and least used team docs to Slack so owners can archive stale docs.',
      modules: ['scheduled', 'agent', 'workflows'],
      category: 'operations',
      tags: ['analytics', 'reporting'],
      alsoIntegrations: ['slack'],
    },
  ],
  skills: [
    {
      name: 'log-action-items-to-coda',
      description:
        'Turn meeting notes or a conversation into action items and add them as rows in a Coda tasks table.',
      content:
        '# Log Action Items to Coda\n\nCapture follow-ups from a meeting or thread in a Coda tasks table.\n\n## Steps\n1. Extract each action item with its owner, due date, and a one-line description.\n2. List the columns of the target Coda table to get the exact column IDs or names.\n3. Insert one row per action item, mapping each field to its column. Use the task name as an upsert key when re-running on the same notes.\n4. Keep the returned request ID and check the mutation status if you need to confirm the rows were written.\n\n## Output\nThe number of rows added and the list of action items with their owners.',
    },
    {
      name: 'answer-from-coda-table',
      description:
        'Answer a question using the rows of a Coda table, filtering by a column value when possible.',
      content:
        '# Answer From Coda Table\n\nUse a Coda table as the source of truth for a question.\n\n## Steps\n1. If only a Coda link is given, resolve the browser link to get the doc and table IDs.\n2. List the table columns to find the columns relevant to the question.\n3. List rows with column names enabled, filtering on a single column value when the question names one.\n4. Page through results with the page token until you have the rows you need.\n5. Answer only from the returned values.\n\n## Output\nA concise answer citing the row names and links used. Say so if no matching rows exist.',
    },
    {
      name: 'write-status-update-page',
      description:
        'Draft a status update and prepend it to a Coda page as Markdown, keeping earlier updates below.',
      content:
        '# Write Status Update Page\n\nPublish a dated status update into an existing Coda page.\n\n## Steps\n1. Gather the facts for the update (progress, risks, next steps) from the provided sources.\n2. Write the update in Markdown with a dated heading and short bullet lists.\n3. Update the Coda page with content mode set to prepend so the newest update is at the top.\n4. Confirm the change with the returned request ID if needed.\n\n## Output\nThe Markdown that was added and the page link.',
    },
    {
      name: 'triage-coda-tracker-rows',
      description:
        'Review new rows in a Coda tracker table and update their status, priority, or owner columns.',
      content:
        '# Triage Coda Tracker Rows\n\nTriage incoming items (bugs, requests, tickets) stored in a Coda table.\n\n## Steps\n1. List rows filtered to the untriaged status value.\n2. For each row, decide priority and owner from its description.\n3. Update each row with the triage fields using column names or IDs.\n4. Push the row button column if the table uses a button to notify the owner.\n\n## Output\nA table of triaged rows with the priority and owner assigned to each.',
    },
    {
      name: 'audit-coda-doc-sharing',
      description:
        'Review who a Coda doc is shared with and flag public links or access outside the company domain.',
      content:
        '# Audit Coda Doc Sharing\n\nCheck a Coda doc for overly broad access.\n\n## Steps\n1. List the permissions on the doc.\n2. Flag any permission shared with anyone with the link, or with an email or domain outside the company domain.\n3. Read the sharing settings to see whether editors can change permissions or viewers can copy the doc.\n4. Remove a permission only when the user confirms it should be revoked.\n\n## Output\nA list of risky permissions with the principal and access level, plus the current sharing settings.',
    },
    {
      name: 'export-coda-page-markdown',
      description:
        'Export a Coda page as Markdown so its content can be summarized, archived, or synced elsewhere.',
      content:
        '# Export Coda Page as Markdown\n\nGet the full content of a Coda page as a Markdown file.\n\n## Steps\n1. Start a page export with Markdown as the output format.\n2. Check the export status with the returned export ID until the status is complete.\n3. Use the download link right away; it expires shortly after it is issued.\n4. If the export fails, read the page content directly as plain-text lines instead.\n\n## Output\nThe download link or the page text, plus the page name.',
    },
  ],
} as const satisfies BlockMeta
