import { NetSuiteIcon } from '@/components/icons'
import { getScopesForService } from '@/lib/oauth/utils'
import { AuthMode, type BlockConfig, type BlockMeta, IntegrationType } from '@/blocks/types'
import { normalizeFileInput } from '@/blocks/utils'
import type { OraclePcmResponse } from '@/tools/oracle_epm_profitability/types'
import { parseOraclePcmBoolean } from '@/tools/oracle_epm_profitability/utils'

export const OraclePcmBlock: BlockConfig<OraclePcmResponse> = {
  type: 'oracle_epm_profitability',
  name: 'Oracle EPM Profitability and Cost Management (PCM)',
  description: 'Calculate allocations and manage PCM data, POVs, reports, and tasks',
  longDescription:
    'Automate Cloud PCM Management Ledger applications using the epm/rest/v1 API family. This is distinct from Enterprise Profitability and Cost Management (EPCM). Use a provisioned PCM environment under an eligible EPM Enterprise or legacy PCM subscription. Most operations require Service Administrator or Power User; creating an application requires Service Administrator. Report and query-export submissions accept all application roles, but task polling requires Service Administrator or Power User. File operations and file selectors require Service Administrator or an application role with Migrations - Administer. Upload inputs to profitinbox and download reports from profitoutbox. Downloads require repository paths of at most 255 UTF-8 bytes; use short output filenames. Submission and waiting are separate; retain processName and inspect the Job Library after ambiguous failures. Application, POV, model view, rule, and query names are manual inputs. Template export and undocumented nested rule-balancing fields are not exposed.',
  docsLink: 'https://docs.sim.ai/integrations/oracle_epm_profitability',
  category: 'tools',
  integrationType: IntegrationType.Analytics,
  authMode: AuthMode.ApiKey,
  bgColor: '#FFFFFF',
  icon: NetSuiteIcon,
  canvasPresentation: {
    defaultTitle: 'Oracle PCM',
    sentences: {
      byOperation: {
        oracle_epm_profitability_create_application: ['Create application'],
        oracle_epm_profitability_enable_application: ['Enable application'],
        oracle_epm_profitability_deploy_cube: ['Deploy cube'],
        oracle_epm_profitability_update_dimensions: ['Update dimensions'],
        oracle_epm_profitability_load_data: ['Load data'],
        oracle_epm_profitability_run_calculation: ['Run calculation'],
        oracle_epm_profitability_copy_pov: ['Copy POV'],
        oracle_epm_profitability_clear_pov: ['Clear POV'],
        oracle_epm_profitability_get_rule_balancing: ['Get rule balancing'],
        oracle_epm_profitability_generate_program_documentation: ['Generate program documentation'],
        oracle_epm_profitability_export_query_results: ['Export query results'],
        oracle_epm_profitability_import_template: ['Import template'],
        oracle_epm_profitability_apply_data_grants: ['Apply data grants'],
        oracle_epm_profitability_merge_slices: ['Merge slices'],
        oracle_epm_profitability_optimize_cube: ['Optimize cube'],
        oracle_epm_profitability_get_task_status: ['Get task status'],
        oracle_epm_profitability_wait_for_task: ['Wait for task'],
        oracle_epm_profitability_upload_file: ['Upload file'],
        oracle_epm_profitability_list_files: ['List files'],
        oracle_epm_profitability_download_file: ['Download file'],
      },
    },
  },
  subBlocks: [
    {
      id: 'operation',
      title: 'Operation',
      type: 'dropdown',
      options: [
        { label: 'Create Application', id: 'oracle_epm_profitability_create_application' },
        { label: 'Enable Application', id: 'oracle_epm_profitability_enable_application' },
        { label: 'Deploy Cube', id: 'oracle_epm_profitability_deploy_cube' },
        { label: 'Update Dimensions', id: 'oracle_epm_profitability_update_dimensions' },
        { label: 'Load Data', id: 'oracle_epm_profitability_load_data' },
        { label: 'Run Calculation', id: 'oracle_epm_profitability_run_calculation' },
        { label: 'Copy POV', id: 'oracle_epm_profitability_copy_pov' },
        { label: 'Clear POV', id: 'oracle_epm_profitability_clear_pov' },
        { label: 'Get Rule Balancing', id: 'oracle_epm_profitability_get_rule_balancing' },
        {
          label: 'Generate Program Documentation',
          id: 'oracle_epm_profitability_generate_program_documentation',
        },
        { label: 'Export Query Results', id: 'oracle_epm_profitability_export_query_results' },
        { label: 'Import Template', id: 'oracle_epm_profitability_import_template' },
        { label: 'Apply Data Grants', id: 'oracle_epm_profitability_apply_data_grants' },
        { label: 'Merge Slices', id: 'oracle_epm_profitability_merge_slices' },
        { label: 'Optimize Cube', id: 'oracle_epm_profitability_optimize_cube' },
        { label: 'Get Task Status', id: 'oracle_epm_profitability_get_task_status' },
        { label: 'Wait for Task', id: 'oracle_epm_profitability_wait_for_task' },
        { label: 'Upload File', id: 'oracle_epm_profitability_upload_file' },
        { label: 'List Files', id: 'oracle_epm_profitability_list_files' },
        { label: 'Download File', id: 'oracle_epm_profitability_download_file' },
      ],
      value: () => 'oracle_epm_profitability_list_files',
    },
    {
      id: 'oauthCredential',
      title: 'Oracle EPM Account',
      type: 'oauth-input',
      serviceId: 'oracle-epm-profitability',
      credentialKind: 'service-account',
      requiredScopes: getScopesForService('oracle-epm-profitability'),
      required: true,
      placeholder: 'Select an Oracle EPM service account',
    },
    {
      id: 'applicationName',
      title: 'Application name',
      type: 'short-input',
      condition: {
        field: 'operation',
        value: [
          'oracle_epm_profitability_create_application',
          'oracle_epm_profitability_enable_application',
          'oracle_epm_profitability_deploy_cube',
          'oracle_epm_profitability_update_dimensions',
          'oracle_epm_profitability_load_data',
          'oracle_epm_profitability_run_calculation',
          'oracle_epm_profitability_copy_pov',
          'oracle_epm_profitability_clear_pov',
          'oracle_epm_profitability_get_rule_balancing',
          'oracle_epm_profitability_generate_program_documentation',
          'oracle_epm_profitability_export_query_results',
          'oracle_epm_profitability_import_template',
          'oracle_epm_profitability_apply_data_grants',
          'oracle_epm_profitability_merge_slices',
          'oracle_epm_profitability_optimize_cube',
        ],
      },
      required: {
        field: 'operation',
        value: [
          'oracle_epm_profitability_create_application',
          'oracle_epm_profitability_enable_application',
          'oracle_epm_profitability_deploy_cube',
          'oracle_epm_profitability_update_dimensions',
          'oracle_epm_profitability_load_data',
          'oracle_epm_profitability_run_calculation',
          'oracle_epm_profitability_copy_pov',
          'oracle_epm_profitability_clear_pov',
          'oracle_epm_profitability_get_rule_balancing',
          'oracle_epm_profitability_generate_program_documentation',
          'oracle_epm_profitability_export_query_results',
          'oracle_epm_profitability_import_template',
          'oracle_epm_profitability_apply_data_grants',
          'oracle_epm_profitability_merge_slices',
          'oracle_epm_profitability_optimize_cube',
        ],
      },
      placeholder: 'Exact PCM Management Ledger application name',
    },
    {
      id: 'povName',
      title: 'POV name',
      type: 'short-input',
      condition: {
        field: 'operation',
        value: [
          'oracle_epm_profitability_run_calculation',
          'oracle_epm_profitability_copy_pov',
          'oracle_epm_profitability_clear_pov',
          'oracle_epm_profitability_get_rule_balancing',
          'oracle_epm_profitability_generate_program_documentation',
        ],
      },
      required: true,
      placeholder: 'POV members joined by stringDelimiter; model POV for calculations',
    },
    {
      id: 'destinationPovName',
      title: 'Destination POV name',
      type: 'short-input',
      condition: { field: 'operation', value: 'oracle_epm_profitability_copy_pov' },
      required: true,
      placeholder: 'Destination POV members joined by stringDelimiter',
    },
    {
      id: 'description',
      title: 'Description',
      type: 'long-input',
      condition: {
        field: 'operation',
        value: [
          'oracle_epm_profitability_create_application',
          'oracle_epm_profitability_import_template',
        ],
      },
      required: true,
      placeholder: 'Description of the application',
    },
    {
      id: 'ruleDimensionName',
      title: 'Rule dimension name',
      type: 'short-input',
      condition: { field: 'operation', value: 'oracle_epm_profitability_create_application' },
      required: true,
      placeholder: 'Rule dimension name',
    },
    {
      id: 'balanceDimensionName',
      title: 'Balance dimension name',
      type: 'short-input',
      condition: { field: 'operation', value: 'oracle_epm_profitability_create_application' },
      required: true,
      placeholder: 'Balance dimension name',
    },
    {
      id: 'comment',
      title: 'Comment',
      type: 'long-input',
      condition: {
        field: 'operation',
        value: ['oracle_epm_profitability_deploy_cube', 'oracle_epm_profitability_run_calculation'],
      },
      required: { field: 'operation', value: 'oracle_epm_profitability_deploy_cube' },
      placeholder: 'Comment for the operation',
    },
    {
      id: 'isKeepData',
      title: 'Keep existing data',
      type: 'switch',
      condition: { field: 'operation', value: 'oracle_epm_profitability_deploy_cube' },
      required: true,
      defaultValue: false,
    },
    {
      id: 'isReplaceCube',
      title: 'Replace cube',
      type: 'switch',
      condition: { field: 'operation', value: 'oracle_epm_profitability_deploy_cube' },
      required: true,
      defaultValue: false,
    },
    {
      id: 'dataFileName',
      title: 'Data file name',
      type: 'short-input',
      condition: { field: 'operation', value: 'oracle_epm_profitability_update_dimensions' },
      required: true,
      placeholder:
        'Filename already staged in profitinbox; dimension updates accept a delimiter-separated list',
      wandConfig: {
        enabled: true,
        prompt:
          'Generate a comma-separated list of existing PCM dimension metadata filenames. Return ONLY the filename list.',
        placeholder: 'Describe the requested selection',
      },
    },
    {
      id: 'stringDelimiter',
      title: 'String delimiter',
      type: 'short-input',
      condition: {
        field: 'operation',
        value: [
          'oracle_epm_profitability_update_dimensions',
          'oracle_epm_profitability_run_calculation',
          'oracle_epm_profitability_copy_pov',
          'oracle_epm_profitability_clear_pov',
          'oracle_epm_profitability_get_rule_balancing',
          'oracle_epm_profitability_generate_program_documentation',
        ],
      },
      required: { field: 'operation', value: 'oracle_epm_profitability_copy_pov' },
      placeholder:
        'Single separator: defaults to underscore for POVs and comma for dimension file lists',
    },
    {
      id: 'acceptableDecreasePercentage',
      title: 'Acceptable decrease percentage',
      type: 'short-input',
      condition: { field: 'operation', value: 'oracle_epm_profitability_update_dimensions' },
      mode: 'advanced',
      placeholder: 'Maximum permitted dimension member decrease percentage, 0 to 100',
    },
    {
      id: 'clearAllDataFlag',
      title: 'Clear existing data',
      type: 'switch',
      condition: { field: 'operation', value: 'oracle_epm_profitability_load_data' },
      required: true,
      defaultValue: false,
    },
    {
      id: 'dataLoadValue',
      title: 'Data load behavior',
      type: 'dropdown',
      condition: { field: 'operation', value: 'oracle_epm_profitability_load_data' },
      required: true,
      options: [
        { label: 'Add to existing values', id: 'ADD_EXISTING_VALUES' },
        { label: 'Overwrite existing values', id: 'OVERWRITE_EXISTING_VALUES' },
      ],
      value: () => 'OVERWRITE_EXISTING_VALUES',
      placeholder: 'How incoming values affect existing data',
    },
    {
      id: 'exeType',
      title: 'Calculation scope',
      type: 'dropdown',
      condition: { field: 'operation', value: 'oracle_epm_profitability_run_calculation' },
      required: true,
      options: [
        { label: 'All rules', id: 'ALL_RULES' },
        { label: 'Rule-set range', id: 'RULESET_SUBSET' },
        { label: 'Single rule', id: 'SINGLE_RULE' },
      ],
      value: () => 'ALL_RULES',
      placeholder: 'Rules to execute; dataPOVName requires ALL_RULES',
    },
    {
      id: 'dataPOVName',
      title: 'Data POV name',
      type: 'short-input',
      condition: { field: 'operation', value: 'oracle_epm_profitability_run_calculation' },
      mode: 'advanced',
      placeholder: 'Optional different data POV; requires ALL_RULES',
    },
    {
      id: 'isClearCalculated',
      title: 'Clear calculated data',
      type: 'switch',
      condition: { field: 'operation', value: 'oracle_epm_profitability_run_calculation' },
      mode: 'advanced',
      defaultValue: false,
    },
    {
      id: 'optimizeReporting',
      title: 'Optimize reporting',
      type: 'switch',
      condition: { field: 'operation', value: 'oracle_epm_profitability_run_calculation' },
      mode: 'advanced',
      defaultValue: true,
    },
    {
      id: 'subsetStart',
      title: 'Subset start',
      type: 'short-input',
      condition: (values) => ({
        field: 'operation',
        value: [
          'oracle_epm_profitability_run_calculation',
          'oracle_epm_profitability_generate_program_documentation',
        ],
        ...(values?.operation === 'oracle_epm_profitability_run_calculation'
          ? { and: { field: 'exeType', value: 'RULESET_SUBSET' } }
          : {}),
      }),
      required: {
        field: 'operation',
        value: 'oracle_epm_profitability_run_calculation',
        and: { field: 'exeType', value: 'RULESET_SUBSET' },
      },
      placeholder: 'First rule-set sequence; required for RULESET_SUBSET',
    },
    {
      id: 'subsetEnd',
      title: 'Subset end',
      type: 'short-input',
      condition: (values) => ({
        field: 'operation',
        value: [
          'oracle_epm_profitability_run_calculation',
          'oracle_epm_profitability_generate_program_documentation',
        ],
        ...(values?.operation === 'oracle_epm_profitability_run_calculation'
          ? { and: { field: 'exeType', value: 'RULESET_SUBSET' } }
          : {}),
      }),
      required: {
        field: 'operation',
        value: 'oracle_epm_profitability_run_calculation',
        and: { field: 'exeType', value: 'RULESET_SUBSET' },
      },
      placeholder: 'Last rule-set sequence; required for RULESET_SUBSET',
    },
    {
      id: 'ruleName',
      title: 'Rule name',
      type: 'short-input',
      condition: {
        field: 'operation',
        value: 'oracle_epm_profitability_run_calculation',
        and: { field: 'exeType', value: 'SINGLE_RULE' },
      },
      required: true,
      placeholder: 'Existing rule name; required for SINGLE_RULE',
    },
    {
      id: 'ruleSetName',
      title: 'Rule set name',
      type: 'short-input',
      condition: {
        field: 'operation',
        value: 'oracle_epm_profitability_run_calculation',
        and: { field: 'exeType', value: 'SINGLE_RULE' },
      },
      required: true,
      placeholder: 'Existing rule set name; required for SINGLE_RULE',
    },
    {
      id: 'isManageRule',
      title: 'Include program rules',
      type: 'switch',
      condition: {
        field: 'operation',
        value: ['oracle_epm_profitability_copy_pov', 'oracle_epm_profitability_clear_pov'],
      },
      required: { field: 'operation', value: 'oracle_epm_profitability_copy_pov' },
      defaultValue: false,
    },
    {
      id: 'isInputData',
      title: 'Include input data',
      type: 'switch',
      condition: {
        field: 'operation',
        value: ['oracle_epm_profitability_copy_pov', 'oracle_epm_profitability_clear_pov'],
      },
      required: { field: 'operation', value: 'oracle_epm_profitability_copy_pov' },
      defaultValue: false,
    },
    {
      id: 'createDestPOV',
      title: 'Create destination POV',
      type: 'switch',
      condition: { field: 'operation', value: 'oracle_epm_profitability_copy_pov' },
      required: true,
      defaultValue: false,
    },
    {
      id: 'modelViewName',
      title: 'Model view name',
      type: 'short-input',
      condition: {
        field: 'operation',
        value: ['oracle_epm_profitability_copy_pov', 'oracle_epm_profitability_get_rule_balancing'],
      },
      required: { field: 'operation', value: 'oracle_epm_profitability_get_rule_balancing' },
      placeholder: 'Existing model view to limit the data slice',
    },
    {
      id: 'nonEmptyTupleEnabled',
      title: 'Optimize nonempty tuples',
      type: 'switch',
      condition: { field: 'operation', value: 'oracle_epm_profitability_copy_pov' },
      mode: 'advanced',
      defaultValue: true,
    },
    {
      id: 'isAllocatedValues',
      title: 'Clear allocated values',
      type: 'switch',
      condition: { field: 'operation', value: 'oracle_epm_profitability_clear_pov' },
      mode: 'advanced',
      defaultValue: false,
    },
    {
      id: 'isAdjustmentValues',
      title: 'Clear adjustment values',
      type: 'switch',
      condition: { field: 'operation', value: 'oracle_epm_profitability_clear_pov' },
      mode: 'advanced',
      defaultValue: false,
    },
    {
      id: 'queryName',
      title: 'Query name',
      type: 'short-input',
      condition: {
        field: 'operation',
        value: [
          'oracle_epm_profitability_clear_pov',
          'oracle_epm_profitability_export_query_results',
        ],
      },
      mode: 'advanced',
      placeholder: 'Existing PCM query; exports with no query export all application data',
    },
    {
      id: 'fileName',
      title: 'File name',
      type: 'short-input',
      condition: {
        field: 'operation',
        value: [
          'oracle_epm_profitability_upload_file',
          'oracle_epm_profitability_export_query_results',
          'oracle_epm_profitability_generate_program_documentation',
        ],
      },
      required: {
        field: 'operation',
        value: [
          'oracle_epm_profitability_upload_file',
          'oracle_epm_profitability_export_query_results',
        ],
      },
      placeholder: 'Filename without a repository folder',
    },
    {
      id: 'fileType',
      title: 'File type',
      type: 'dropdown',
      condition: {
        field: 'operation',
        value: 'oracle_epm_profitability_generate_program_documentation',
      },
      mode: 'advanced',
      options: [
        { label: 'PDF', id: 'PDF' },
        { label: 'XML', id: 'XML' },
        { label: 'Word', id: 'WORD' },
        { label: 'Excel', id: 'EXCEL' },
        { label: 'HTML', id: 'HTML' },
      ],
      value: () => 'PDF',
      placeholder: 'Program documentation format',
    },
    {
      id: 'skipFilters',
      title: 'Skip filters',
      type: 'switch',
      condition: {
        field: 'operation',
        value: 'oracle_epm_profitability_generate_program_documentation',
      },
      mode: 'advanced',
      defaultValue: false,
    },
    {
      id: 'useAlias',
      title: 'Use aliases',
      type: 'switch',
      condition: {
        field: 'operation',
        value: 'oracle_epm_profitability_generate_program_documentation',
      },
      mode: 'advanced',
      defaultValue: false,
    },
    {
      id: 'exportOnlyLevel0Flg',
      title: 'Export only level-0 data',
      type: 'switch',
      condition: { field: 'operation', value: 'oracle_epm_profitability_export_query_results' },
      mode: 'advanced',
      defaultValue: false,
    },
    {
      id: 'fileOutputOptions',
      title: 'File output options',
      type: 'dropdown',
      condition: { field: 'operation', value: 'oracle_epm_profitability_export_query_results' },
      mode: 'advanced',
      options: [
        { label: 'ZIP only', id: 'ZIP_ONLY' },
        { label: 'ZIP and text', id: 'ZIP_AND_TEXT' },
        { label: 'Text only', id: 'TEXT_ONLY' },
      ],
      value: () => 'ZIP_ONLY',
      placeholder: 'Export compression and text-file output',
    },
    {
      id: 'roundingPrecision',
      title: 'Rounding precision',
      type: 'short-input',
      condition: { field: 'operation', value: 'oracle_epm_profitability_export_query_results' },
      mode: 'advanced',
      placeholder: 'Decimal places for named query exports; Oracle defaults to 2',
    },
    {
      id: 'dataFormat',
      title: 'Data format',
      type: 'dropdown',
      condition: { field: 'operation', value: 'oracle_epm_profitability_export_query_results' },
      mode: 'advanced',
      options: [
        { label: 'Native', id: 'NATIVE' },
        { label: 'Columnar', id: 'COLUMNAR' },
      ],
      value: () => 'NATIVE',
      placeholder:
        'NATIVE exports query data; COLUMNAR exports application data and ignores queryName',
    },
    {
      id: 'memberFilters',
      title: 'Member filters',
      type: 'long-input',
      condition: { field: 'operation', value: 'oracle_epm_profitability_export_query_results' },
      mode: 'advanced',
      placeholder:
        'JSON string mapping dimensions to level-0 member arrays; applies to COLUMNAR exports',
      wandConfig: {
        enabled: true,
        prompt:
          'Generate a JSON object mapping dimension names to arrays of level-0 member names. Return ONLY the JSON object.',
        placeholder: 'Describe the requested selection',
        generationType: 'json-object',
      },
    },
    {
      id: 'includeHeader',
      title: 'Include header',
      type: 'switch',
      condition: { field: 'operation', value: 'oracle_epm_profitability_export_query_results' },
      mode: 'advanced',
      defaultValue: true,
    },
    {
      id: 'delimiter',
      title: 'Delimiter',
      type: 'short-input',
      condition: { field: 'operation', value: 'oracle_epm_profitability_export_query_results' },
      mode: 'advanced',
      placeholder: 'Single column separator for COLUMNAR exports; Oracle defaults to space',
    },
    {
      id: 'keepDuplicateMemberFormat',
      title: 'Keep duplicate member format',
      type: 'switch',
      condition: { field: 'operation', value: 'oracle_epm_profitability_export_query_results' },
      mode: 'advanced',
      defaultValue: true,
    },
    {
      id: 'isApplicationOverwrite',
      title: 'Overwrite application',
      type: 'switch',
      condition: { field: 'operation', value: 'oracle_epm_profitability_import_template' },
      required: true,
      defaultValue: false,
    },
    {
      id: 'removeZeroCells',
      title: 'Remove zero cells',
      type: 'switch',
      condition: { field: 'operation', value: 'oracle_epm_profitability_merge_slices' },
      mode: 'advanced',
      defaultValue: false,
    },
    {
      id: 'type',
      title: 'Optimization operation',
      type: 'dropdown',
      condition: { field: 'operation', value: 'oracle_epm_profitability_optimize_cube' },
      required: true,
      options: [
        { label: 'Clear aggregations', id: 'clearAggregations' },
        { label: 'Create aggregations', id: 'createAggregations' },
        { label: 'Start query tracking', id: 'startQueryTracking' },
        { label: 'Stop query tracking', id: 'stopQueryTracking' },
        { label: 'Create query-based aggregations', id: 'createQBOAggregations' },
      ],
      placeholder: 'ASO optimization operation',
    },
    {
      id: 'processName',
      title: 'Process name',
      type: 'short-input',
      condition: {
        field: 'operation',
        value: [
          'oracle_epm_profitability_get_task_status',
          'oracle_epm_profitability_wait_for_task',
        ],
      },
      required: true,
      placeholder: 'Task processName returned by PCM submission; not a numeric EPCM job ID',
    },
    {
      id: 'maxWaitSeconds',
      title: 'Max wait seconds',
      type: 'short-input',
      condition: { field: 'operation', value: 'oracle_epm_profitability_wait_for_task' },
      mode: 'advanced',
      value: () => '300',
      placeholder: 'Maximum wait in seconds, 1 to 3600; does not cancel the remote task',
    },
    {
      id: 'inputFileSelector',
      title: 'Input file',
      type: 'file-selector',
      canonicalParamId: 'inputFileName',
      mode: 'basic',
      required: true,
      condition: {
        field: 'operation',
        value: ['oracle_epm_profitability_load_data', 'oracle_epm_profitability_import_template'],
      },
      selectorKey: 'oracleEpmPcm.inputFiles',
      serviceId: 'oracle-epm-profitability',
      dependsOn: ['oauthCredential'],
    },
    {
      id: 'inputFileManual',
      title: 'Input file',
      type: 'short-input',
      canonicalParamId: 'inputFileName',
      mode: 'advanced',
      required: true,
      condition: {
        field: 'operation',
        value: ['oracle_epm_profitability_load_data', 'oracle_epm_profitability_import_template'],
      },
      placeholder: 'Filename in profitinbox without its folder',
    },
    {
      id: 'outputFileSelector',
      title: 'Output file',
      type: 'file-selector',
      canonicalParamId: 'downloadFileName',
      mode: 'basic',
      required: true,
      condition: { field: 'operation', value: 'oracle_epm_profitability_download_file' },
      selectorKey: 'oracleEpmPcm.outputFiles',
      serviceId: 'oracle-epm-profitability',
      dependsOn: ['oauthCredential'],
    },
    {
      id: 'outputFileManual',
      title: 'Output file',
      type: 'short-input',
      canonicalParamId: 'downloadFileName',
      mode: 'advanced',
      required: true,
      condition: { field: 'operation', value: 'oracle_epm_profitability_download_file' },
      placeholder: 'Exact listed profitoutbox path',
    },
    {
      id: 'uploadFile',
      title: 'File',
      type: 'file-upload',
      canonicalParamId: 'file',
      mode: 'basic',
      required: true,
      multiple: false,
      maxSize: 100,
      condition: { field: 'operation', value: 'oracle_epm_profitability_upload_file' },
    },
    {
      id: 'fileRef',
      title: 'File',
      type: 'short-input',
      canonicalParamId: 'file',
      mode: 'advanced',
      required: true,
      placeholder: 'Reference a Sim UserFile',
      condition: { field: 'operation', value: 'oracle_epm_profitability_upload_file' },
    },
  ],
  tools: {
    access: [
      'oracle_epm_profitability_create_application',
      'oracle_epm_profitability_enable_application',
      'oracle_epm_profitability_deploy_cube',
      'oracle_epm_profitability_update_dimensions',
      'oracle_epm_profitability_load_data',
      'oracle_epm_profitability_run_calculation',
      'oracle_epm_profitability_copy_pov',
      'oracle_epm_profitability_clear_pov',
      'oracle_epm_profitability_get_rule_balancing',
      'oracle_epm_profitability_generate_program_documentation',
      'oracle_epm_profitability_export_query_results',
      'oracle_epm_profitability_import_template',
      'oracle_epm_profitability_apply_data_grants',
      'oracle_epm_profitability_merge_slices',
      'oracle_epm_profitability_optimize_cube',
      'oracle_epm_profitability_get_task_status',
      'oracle_epm_profitability_wait_for_task',
      'oracle_epm_profitability_upload_file',
      'oracle_epm_profitability_list_files',
      'oracle_epm_profitability_download_file',
    ],
    config: {
      tool: (params) => params.operation,
      params: (params) => {
        const result: Record<string, unknown> = {}
        for (const key of [
          'acceptableDecreasePercentage',
          'subsetStart',
          'subsetEnd',
          'roundingPrecision',
          'maxWaitSeconds',
        ]) {
          if (params[key] !== undefined && params[key] !== null && params[key] !== '') {
            result[key] = Number(params[key])
          }
        }
        for (const key of [
          'isKeepData',
          'isReplaceCube',
          'clearAllDataFlag',
          'isClearCalculated',
          'optimizeReporting',
          'isManageRule',
          'isInputData',
          'createDestPOV',
          'nonEmptyTupleEnabled',
          'isAllocatedValues',
          'isAdjustmentValues',
          'skipFilters',
          'useAlias',
          'exportOnlyLevel0Flg',
          'includeHeader',
          'keepDuplicateMemberFormat',
          'isApplicationOverwrite',
          'removeZeroCells',
        ]) {
          result[key] = parseOraclePcmBoolean(params[key])
        }
        if (params.operation === 'oracle_epm_profitability_load_data') {
          result.dataFileName = params.inputFileName
        }
        if (params.operation === 'oracle_epm_profitability_import_template') {
          result.fileName = params.inputFileName
        }
        if (params.operation === 'oracle_epm_profitability_download_file') {
          result.fileName = params.downloadFileName
        }
        if (params.operation === 'oracle_epm_profitability_upload_file') {
          result.file = normalizeFileInput(params.file, { single: true })
        }
        return result
      },
    },
  },
  inputs: {
    oauthCredential: { type: 'string', description: 'Reusable Oracle EPM credential' },
    inputFileName: { type: 'string', description: 'Filename in profitinbox' },
    downloadFileName: { type: 'string', description: 'Listed PCM repository path' },
    applicationName: { type: 'string', description: 'PCM Management Ledger application name' },
    povName: { type: 'string', description: 'POV members joined by stringDelimiter' },
    destinationPovName: { type: 'string', description: 'Destination POV members' },
    description: { type: 'string', description: 'Application description' },
    ruleDimensionName: { type: 'string', description: 'Rule dimension name' },
    balanceDimensionName: { type: 'string', description: 'Balance dimension name' },
    comment: { type: 'string', description: 'Operation comment' },
    isKeepData: { type: 'boolean', description: 'Preserve existing cube data' },
    isReplaceCube: { type: 'boolean', description: 'Replace the existing cube' },
    dataFileName: { type: 'string', description: 'Staged dimension filenames' },
    stringDelimiter: { type: 'string', description: 'POV or dimension filename separator' },
    acceptableDecreasePercentage: {
      type: 'number',
      description: 'Allowed member decrease percent',
    },
    clearAllDataFlag: { type: 'boolean', description: 'Clear existing data before loading' },
    dataLoadValue: { type: 'string', description: 'Add or overwrite incoming values' },
    exeType: { type: 'string', description: 'All rules, a rule-set range, or one rule' },
    dataPOVName: { type: 'string', description: 'Optional different data POV for ALL_RULES' },
    isClearCalculated: { type: 'boolean', description: 'Clear previously calculated data' },
    optimizeReporting: { type: 'boolean', description: 'Aggregate after calculation' },
    subsetStart: { type: 'number', description: 'First rule-set sequence' },
    subsetEnd: { type: 'number', description: 'Last rule-set sequence' },
    ruleName: { type: 'string', description: 'Existing rule name for SINGLE_RULE' },
    ruleSetName: { type: 'string', description: 'Existing rule set for SINGLE_RULE' },
    isManageRule: { type: 'boolean', description: 'Include program rules' },
    isInputData: { type: 'boolean', description: 'Include input data' },
    createDestPOV: { type: 'boolean', description: 'Create the destination POV if missing' },
    modelViewName: { type: 'string', description: 'Existing model view' },
    nonEmptyTupleEnabled: { type: 'boolean', description: 'Optimize nonempty tuples' },
    isAllocatedValues: { type: 'boolean', description: 'Clear allocated values' },
    isAdjustmentValues: { type: 'boolean', description: 'Clear adjustment values' },
    queryName: { type: 'string', description: 'Existing PCM query' },
    fileName: { type: 'string', description: 'Filename for upload or report output' },
    fileType: { type: 'string', description: 'Program documentation format' },
    skipFilters: { type: 'boolean', description: 'Use member counts instead of rule filters' },
    useAlias: { type: 'boolean', description: 'Use aliases in program documentation' },
    exportOnlyLevel0Flg: { type: 'boolean', description: 'Export only level-0 query data' },
    fileOutputOptions: { type: 'string', description: 'ZIP and text output options' },
    roundingPrecision: { type: 'number', description: 'Query export decimal places' },
    dataFormat: { type: 'string', description: 'Native query or columnar application export' },
    memberFilters: { type: 'string', description: 'JSON string of dimension member filters' },
    includeHeader: { type: 'boolean', description: 'Include columnar dimension headers' },
    delimiter: { type: 'string', description: 'Single columnar separator' },
    keepDuplicateMemberFormat: { type: 'boolean', description: 'Qualify duplicate members' },
    isApplicationOverwrite: { type: 'boolean', description: 'Overwrite the imported application' },
    removeZeroCells: { type: 'boolean', description: 'Remove zero-valued cells when merging' },
    type: { type: 'string', description: 'ASO optimization operation' },
    processName: { type: 'string', description: 'PCM task identifier returned by submission' },
    maxWaitSeconds: { type: 'number', description: 'Maximum wait in seconds, 1 to 3600' },
    file: { type: 'json', description: 'One canonical Sim UserFile or one-element upload array' },
  },
  outputs: {
    processName: {
      type: 'string',
      description: 'PCM task identifier for status and wait operations',
    },
    status: { type: 'number', description: '-1 pending, 0 succeeded, positive values failed' },
    state: { type: 'string', description: 'Normalized pending, succeeded, or failed state' },
    statusMessage: { type: 'string', description: 'Oracle status message' },
    details: { type: 'string', description: 'Oracle task details, including report information' },
    attempts: { type: 'number', description: 'Status reads before a terminal wait result' },
    timedOut: { type: 'boolean', description: 'Wait expired without cancelling the remote task' },
    items: {
      type: 'json',
      description:
        'Scalar rule balances: ruleNumber, name, description, sequence, scale, balanceTypeRule, balances, allocations, adjustments, input, remainders, netChange, and offset',
    },
    files: { type: 'json', description: 'PCM files with name, type, size, and lastModifiedTime' },
    fileName: { type: 'string', description: 'Uploaded repository path in profitinbox' },
    file: { type: 'file', description: 'Downloaded canonical Sim UserFile' },
  },
}

export const OraclePcmBlockMeta = {
  tags: ['data-analytics', 'automation'],
  url: 'https://www.oracle.com/performance-management/profitability-cost-management/',
  templates: [
    {
      icon: NetSuiteIcon,
      title: 'Refresh input data',
      prompt:
        'When a PCM data file is ready, upload it to profitinbox, load it into the selected application, and wait for the returned task.',
      modules: ['workflows', 'files'],
      category: 'operations',
      tags: ['automation'],
    },
    {
      icon: NetSuiteIcon,
      title: 'Run monthly allocations',
      prompt:
        'On a monthly schedule, run all rules for the selected PCM POV and wait for completion before reporting the task outcome.',
      modules: ['workflows', 'files'],
      category: 'operations',
      tags: ['automation'],
    },
    {
      icon: NetSuiteIcon,
      title: 'Compare rule balances',
      prompt:
        'After a PCM calculation, retrieve rule-balancing results for a chosen POV and model view, then summarize the documented balances and remainders.',
      modules: ['workflows', 'files'],
      category: 'operations',
      tags: ['automation'],
    },
    {
      icon: NetSuiteIcon,
      title: 'Document allocation rules',
      prompt:
        'When allocation documentation is needed, submit a program report for the chosen POV, wait for completion, then list and download the report from profitoutbox.',
      modules: ['workflows', 'files'],
      category: 'operations',
      tags: ['automation'],
    },
    {
      icon: NetSuiteIcon,
      title: 'Export profitability results',
      prompt:
        'On a reporting schedule, export an existing PCM query, wait for its task, then list and download the output file.',
      modules: ['workflows', 'files'],
      category: 'operations',
      tags: ['automation'],
    },
    {
      icon: NetSuiteIcon,
      title: 'Update dimension metadata',
      prompt:
        'When dimension metadata files are ready, stage them in profitinbox, update dimensions with a member-decrease safeguard, then wait for the task result.',
      modules: ['workflows', 'files'],
      category: 'operations',
      tags: ['automation'],
    },
    {
      icon: NetSuiteIcon,
      title: 'Prepare a scenario POV',
      prompt:
        'When a new scenario is requested, copy selected rules and input data to its PCM POV and wait for the copy task.',
      modules: ['workflows', 'files'],
      category: 'operations',
      tags: ['automation'],
    },
  ],
  skills: [
    {
      name: 'load-pcm-inputs',
      description: 'Load PCM inputs using documented PCM operations.',
      content:
        '# Load PCM Inputs\n\n## Steps\nUpload the supplied data file to profitinbox. Load the file into the selected PCM application. Wait using the returned processName.\n\n## Output\nReturn the task identifiers and results. Stop on failures and retain processName for follow-up.',
    },
    {
      name: 'calculate-pcm-allocations',
      description: 'Calculate PCM allocations using documented PCM operations.',
      content:
        '# Calculate PCM Allocations\n\n## Steps\nUse the supplied application and POV names. Select all rules, a rule-set range, or one rule. Submit the calculation and wait for its processName.\n\n## Output\nReturn the task identifiers and results. Stop on failures and retain processName for follow-up.',
    },
    {
      name: 'export-pcm-query',
      description: 'Export PCM query results using documented PCM operations.',
      content:
        '# Export PCM Query Results\n\n## Steps\nUse an existing named PCM query and choose an output filename. Submit export query results. Wait for the processName, then list and download the output file.\n\n## Output\nReturn the task identifiers and downloaded files. Stop on failures and retain processName for follow-up.',
    },
    {
      name: 'inspect-pcm-rule-balancing',
      description: 'Inspect PCM rule balancing using documented PCM operations.',
      content:
        '# Inspect PCM Rule Balancing\n\n## Steps\nRead rule balancing for the supplied application, POV, and model view. Compare balances, allocations, adjustments, and remainders. Do not infer omitted nested rule details.\n\n## Output\nReturn the documented scalar rule balances or report the failure.',
    },
    {
      name: 'document-pcm-program',
      description: 'Document PCM programs using documented PCM operations.',
      content:
        '# Document PCM Program\n\n## Steps\nSubmit program documentation for the supplied application and POV. Choose a format and filename. Wait for the processName, then list and download the report.\n\n## Output\nReturn the task identifiers and downloaded files. Stop on failures and retain processName for follow-up.',
    },
    {
      name: 'optimize-pcm-aso',
      description: 'Optimize PCM ASO queries using documented PCM operations.',
      content:
        '# Optimize PCM ASO Queries\n\n## Steps\nUse the selected PCM application. Start query tracking, run representative existing query exports, create query-based aggregates, and stop tracking. Wait for each task before the next operation.\n\n## Output\nReturn the task identifiers and results. Stop on failures and retain processName for follow-up.',
    },
  ],
} as const satisfies BlockMeta
