import type { BlockConfig, BlockMeta } from '@/blocks/types'

export const StripeBlock: BlockConfig = {
  id: 'stripe',
  integrationType: 'stripe',
  name: 'Stripe',
  description:
    'Connect Stripe: payments, customers, subscriptions, invoices, billing, and more. 20 integrated modules covering 587+ API endpoints.',
  category: 'tools',
  tags: ['payment-processor', 'billing', 'subscriptions', 'refunds', 'invoices', 'payments'],
  authMode: 'credentials',
  docsLink: 'https://stripe.com/docs/api',
  brandColor: '#635BFF',
  subBlocks: [
    {
      id: 'apiKey',
      title: 'API Key',
      type: 'short-input',
      required: true,
      visibility: 'user-only',
      password: true,
      description: 'Stripe API key (sk_live_* or sk_test_*)',
    },
    {
      id: 'category',
      title: 'Category',
      type: 'dropdown',
      required: true,
      visibility: 'user-or-llm',
      options: [
        { label: 'Core Account', id: 'core' },
        { label: 'Customers', id: 'customers' },
        { label: 'Subscriptions', id: 'subscriptions' },
        { label: 'Charges', id: 'charges' },
        { label: 'Payments', id: 'payments' },
        { label: 'Payment Methods', id: 'payment_methods' },
        { label: 'Invoices', id: 'invoices' },
        { label: 'Products & Pricing', id: 'products' },
        { label: 'Coupons & Promotions', id: 'coupons' },
        { label: 'Refunds', id: 'refunds' },
        { label: 'Transfers & Payouts', id: 'transfers' },
        { label: 'Disputes', id: 'disputes' },
        { label: 'Sources & Tokens', id: 'sources' },
        { label: 'Webhooks & Events', id: 'webhooks' },
        { label: 'Files', id: 'files' },
        { label: 'Financial Connections', id: 'financial' },
        { label: 'Tax', id: 'tax' },
        { label: 'Billing Portal', id: 'billing_portal' },
        { label: 'Checkout', id: 'checkout' },
        { label: 'Advanced Services', id: 'advanced' },
      ],
      value: () => 'customers',
    },
    // Core operations
    {
      id: 'coreOperation',
      title: 'Operation',
      type: 'dropdown',
      required: true,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'core' },
      options: [
        { label: 'Retrieve Account', id: 'retrieve_account' },
        { label: 'List Accounts', id: 'list_accounts' },
        { label: 'Create Account Link', id: 'create_account_link' },
        { label: 'Retrieve Account Link', id: 'retrieve_account_link' },
      ],
    },
    // Customers operations
    {
      id: 'customersOperation',
      title: 'Operation',
      type: 'dropdown',
      required: true,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'customers' },
      options: [
        { label: 'Create Customer', id: 'create_customer' },
        { label: 'Retrieve Customer', id: 'retrieve_customer' },
        { label: 'Update Customer', id: 'update_customer' },
        { label: 'Delete Customer', id: 'delete_customer' },
        { label: 'List Customers', id: 'list_customers' },
        { label: 'List Contacts', id: 'list_contacts' },
        { label: 'Create Customer Session', id: 'create_customer_session' },
        { label: 'Retrieve Customer Session', id: 'retrieve_customer_session' },
      ],
    },
    {
      id: 'customerId',
      title: 'Customer ID',
      type: 'short-input',
      required: false,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'customers' },
      description: 'Customer ID (required for retrieve, update, delete)',
    },
    {
      id: 'customerEmail',
      title: 'Email',
      type: 'short-input',
      required: false,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'customers' },
      description: 'Customer email (for create/update)',
    },
    {
      id: 'customerName',
      title: 'Name',
      type: 'short-input',
      required: false,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'customers' },
      description: 'Customer name (for create/update)',
    },
    // Subscriptions
    {
      id: 'subscriptionsOperation',
      title: 'Operation',
      type: 'dropdown',
      required: true,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'subscriptions' },
      options: [
        { label: 'Create Subscription', id: 'create_subscription' },
        { label: 'Retrieve Subscription', id: 'retrieve_subscription' },
        { label: 'Update Subscription', id: 'update_subscription' },
        { label: 'Cancel Subscription', id: 'cancel_subscription' },
        { label: 'Resume Subscription', id: 'resume_subscription' },
        { label: 'List Subscriptions', id: 'list_subscriptions' },
      ],
    },
    // Charges
    {
      id: 'chargesOperation',
      title: 'Operation',
      type: 'dropdown',
      required: true,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'charges' },
      options: [
        { label: 'Create Charge', id: 'create_charge' },
        { label: 'Retrieve Charge', id: 'retrieve_charge' },
        { label: 'Update Charge', id: 'update_charge' },
        { label: 'Capture Charge', id: 'capture_charge' },
        { label: 'List Charges', id: 'list_charges' },
      ],
    },
    // Payments
    {
      id: 'paymentsOperation',
      title: 'Operation',
      type: 'dropdown',
      required: true,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'payments' },
      options: [
        { label: 'Create Payment Intent', id: 'create_payment_intent' },
        { label: 'Retrieve Payment Intent', id: 'retrieve_payment_intent' },
        { label: 'Update Payment Intent', id: 'update_payment_intent' },
        { label: 'Confirm Payment Intent', id: 'confirm_payment_intent' },
        { label: 'Cancel Payment Intent', id: 'cancel_payment_intent' },
        { label: 'List Payment Intents', id: 'list_payment_intents' },
      ],
    },
    {
      id: 'paymentAmount',
      title: 'Amount (cents)',
      type: 'number',
      required: false,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'payments' },
      description: 'Amount in cents',
    },
    // Payment Methods
    {
      id: 'paymentMethodsOperation',
      title: 'Operation',
      type: 'dropdown',
      required: true,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'payment_methods' },
      options: [
        { label: 'Create Payment Method', id: 'create_payment_method' },
        { label: 'Retrieve Payment Method', id: 'retrieve_payment_method' },
        { label: 'Update Payment Method', id: 'update_payment_method' },
        { label: 'Detach Payment Method', id: 'detach_payment_method' },
        { label: 'List Payment Methods', id: 'list_payment_methods' },
      ],
    },
    // Invoices
    {
      id: 'invoicesOperation',
      title: 'Operation',
      type: 'dropdown',
      required: true,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'invoices' },
      options: [
        { label: 'Create Invoice', id: 'create_invoice' },
        { label: 'Retrieve Invoice', id: 'retrieve_invoice' },
        { label: 'Update Invoice', id: 'update_invoice' },
        { label: 'Delete Invoice', id: 'delete_invoice' },
        { label: 'Finalize Invoice', id: 'finalize_invoice' },
        { label: 'Pay Invoice', id: 'pay_invoice' },
        { label: 'List Invoices', id: 'list_invoices' },
      ],
    },
    // Products
    {
      id: 'productsOperation',
      title: 'Operation',
      type: 'dropdown',
      required: true,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'products' },
      options: [
        { label: 'Create Product', id: 'create_product' },
        { label: 'Retrieve Product', id: 'retrieve_product' },
        { label: 'Update Product', id: 'update_product' },
        { label: 'Delete Product', id: 'delete_product' },
        { label: 'List Products', id: 'list_products' },
        { label: 'Create Price', id: 'create_price' },
        { label: 'Retrieve Price', id: 'retrieve_price' },
        { label: 'Update Price', id: 'update_price' },
        { label: 'List Prices', id: 'list_prices' },
      ],
    },
    // Coupons
    {
      id: 'couponsOperation',
      title: 'Operation',
      type: 'dropdown',
      required: true,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'coupons' },
      options: [
        { label: 'Create Coupon', id: 'create_coupon' },
        { label: 'Retrieve Coupon', id: 'retrieve_coupon' },
        { label: 'Update Coupon', id: 'update_coupon' },
        { label: 'Delete Coupon', id: 'delete_coupon' },
        { label: 'List Coupons', id: 'list_coupons' },
        { label: 'Create Promotion Code', id: 'create_promotion_code' },
        { label: 'List Promotion Codes', id: 'list_promotion_codes' },
      ],
    },
    // Refunds
    {
      id: 'refundsOperation',
      title: 'Operation',
      type: 'dropdown',
      required: true,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'refunds' },
      options: [
        { label: 'Create Refund from Charge', id: 'create_refund_from_charge' },
        { label: 'Create Refund from Payment Intent', id: 'create_refund_from_payment_intent' },
        { label: 'Retrieve Refund', id: 'retrieve_refund' },
        { label: 'Update Refund', id: 'update_refund' },
        { label: 'List Refunds', id: 'list_refunds' },
      ],
    },
    {
      id: 'refundAmount',
      title: 'Amount (cents)',
      type: 'number',
      required: false,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'refunds' },
      description: 'Refund amount in cents (optional)',
    },
    // Transfers
    {
      id: 'transfersOperation',
      title: 'Operation',
      type: 'dropdown',
      required: true,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'transfers' },
      options: [
        { label: 'Create Transfer', id: 'create_transfer' },
        { label: 'Retrieve Transfer', id: 'retrieve_transfer' },
        { label: 'Update Transfer', id: 'update_transfer' },
        { label: 'List Transfers', id: 'list_transfers' },
        { label: 'Create Payout', id: 'create_payout' },
        { label: 'List Payouts', id: 'list_payouts' },
        { label: 'Retrieve Balance', id: 'retrieve_balance' },
      ],
    },
    // Disputes
    {
      id: 'disputesOperation',
      title: 'Operation',
      type: 'dropdown',
      required: true,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'disputes' },
      options: [
        { label: 'Retrieve Dispute', id: 'retrieve_dispute' },
        { label: 'Update Dispute', id: 'update_dispute' },
        { label: 'Close Dispute', id: 'close_dispute' },
        { label: 'List Disputes', id: 'list_disputes' },
      ],
    },
    // Sources
    {
      id: 'sourcesOperation',
      title: 'Operation',
      type: 'dropdown',
      required: true,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'sources' },
      options: [
        { label: 'Create Source', id: 'create_source' },
        { label: 'Retrieve Source', id: 'retrieve_source' },
        { label: 'Update Source', id: 'update_source' },
        { label: 'Detach Source', id: 'detach_source' },
        { label: 'Create Token', id: 'create_token' },
        { label: 'Retrieve Token', id: 'retrieve_token' },
      ],
    },
    // Webhooks
    {
      id: 'webhooksOperation',
      title: 'Operation',
      type: 'dropdown',
      required: true,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'webhooks' },
      options: [
        { label: 'Create Webhook Endpoint', id: 'create_webhook_endpoint' },
        { label: 'Retrieve Webhook Endpoint', id: 'retrieve_webhook_endpoint' },
        { label: 'Update Webhook Endpoint', id: 'update_webhook_endpoint' },
        { label: 'Delete Webhook Endpoint', id: 'delete_webhook_endpoint' },
        { label: 'List Webhook Endpoints', id: 'list_webhook_endpoints' },
        { label: 'Retrieve Event', id: 'retrieve_event' },
        { label: 'List Events', id: 'list_events' },
      ],
    },
    // Files
    {
      id: 'filesOperation',
      title: 'Operation',
      type: 'dropdown',
      required: true,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'files' },
      options: [
        { label: 'List Files', id: 'list_files' },
        { label: 'Retrieve File', id: 'retrieve_file' },
        { label: 'Create File Link', id: 'create_file_link' },
        { label: 'Retrieve File Link', id: 'retrieve_file_link' },
        { label: 'List File Links', id: 'list_file_links' },
      ],
    },
    // Financial
    {
      id: 'financialOperation',
      title: 'Operation',
      type: 'dropdown',
      required: true,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'financial' },
      options: [
        { label: 'Retrieve Account', id: 'retrieve_account' },
        { label: 'List Accounts', id: 'list_accounts' },
        { label: 'Create Link Account Session', id: 'create_link_account_session' },
        { label: 'Retrieve Link Account Session', id: 'retrieve_link_account_session' },
      ],
    },
    // Tax
    {
      id: 'taxOperation',
      title: 'Operation',
      type: 'dropdown',
      required: true,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'tax' },
      options: [
        { label: 'Calculate Tax', id: 'calculate_tax' },
        { label: 'Create Tax Code', id: 'create_tax_code' },
        { label: 'List Tax Codes', id: 'list_tax_codes' },
        { label: 'Create Tax Rate', id: 'create_tax_rate' },
        { label: 'Retrieve Tax Rate', id: 'retrieve_tax_rate' },
        { label: 'Update Tax Rate', id: 'update_tax_rate' },
        { label: 'List Tax Rates', id: 'list_tax_rates' },
      ],
    },
    // Billing Portal
    {
      id: 'billingPortalOperation',
      title: 'Operation',
      type: 'dropdown',
      required: true,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'billing_portal' },
      options: [
        { label: 'Create Session', id: 'create_session' },
        { label: 'Retrieve Session', id: 'retrieve_session' },
        { label: 'Create Configuration', id: 'create_configuration' },
        { label: 'Retrieve Configuration', id: 'retrieve_configuration' },
        { label: 'Update Configuration', id: 'update_configuration' },
        { label: 'List Configurations', id: 'list_configurations' },
        { label: 'Create Payment Link', id: 'create_payment_link' },
        { label: 'Retrieve Payment Link', id: 'retrieve_payment_link' },
        { label: 'Update Payment Link', id: 'update_payment_link' },
        { label: 'List Payment Links', id: 'list_payment_links' },
      ],
    },
    // Checkout
    {
      id: 'checkoutOperation',
      title: 'Operation',
      type: 'dropdown',
      required: true,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'checkout' },
      options: [
        { label: 'Create Session', id: 'create_session' },
        { label: 'Retrieve Session', id: 'retrieve_session' },
        { label: 'List Sessions', id: 'list_sessions' },
        { label: 'Expire Session', id: 'expire_session' },
      ],
    },
    // Advanced
    {
      id: 'advancedOperation',
      title: 'Operation',
      type: 'dropdown',
      required: true,
      visibility: 'user-or-llm',
      condition: { field: 'category', value: 'advanced' },
      options: [
        { label: 'Issuing: List Cards', id: 'issuing_list_cards' },
        { label: 'Issuing: Retrieve Card', id: 'issuing_retrieve_card' },
        { label: 'Terminal: List Locations', id: 'terminal_list_locations' },
        { label: 'Treasury: List Accounts', id: 'treasury_list_accounts' },
        { label: 'Radar: List Reviews', id: 'radar_list_reviews' },
        { label: 'Identity: Verify Session', id: 'identity_verify_session' },
        { label: 'Climate: List Orders', id: 'climate_list_orders' },
        { label: 'Entitlements: List Customers', id: 'entitlements_list_customers' },
      ],
    },
  ],
  tools: {
    access: [
      'stripe_core',
      'stripe_customers',
      'stripe_subscriptions',
      'stripe_charges',
      'stripe_payments',
      'stripe_payment_methods',
      'stripe_invoices',
      'stripe_products',
      'stripe_coupons',
      'stripe_refunds',
      'stripe_transfers',
      'stripe_disputes',
      'stripe_sources',
      'stripe_webhooks',
      'stripe_files',
      'stripe_financial',
      'stripe_tax',
      'stripe_billing_portal',
      'stripe_checkout',
      'stripe_advanced',
    ],
    config: {
      tool: (params) => {
        const category = params.category as string
        const categoryToToolMap: Record<string, string> = {
          core: 'stripe_core',
          customers: 'stripe_customers',
          subscriptions: 'stripe_subscriptions',
          charges: 'stripe_charges',
          payments: 'stripe_payments',
          payment_methods: 'stripe_payment_methods',
          invoices: 'stripe_invoices',
          products: 'stripe_products',
          coupons: 'stripe_coupons',
          refunds: 'stripe_refunds',
          transfers: 'stripe_transfers',
          disputes: 'stripe_disputes',
          sources: 'stripe_sources',
          webhooks: 'stripe_webhooks',
          files: 'stripe_files',
          financial: 'stripe_financial',
          tax: 'stripe_tax',
          billing_portal: 'stripe_billing_portal',
          checkout: 'stripe_checkout',
          advanced: 'stripe_advanced',
        }
        return categoryToToolMap[category] || 'stripe_customers'
      },
      params: (params) => {
        const category = params.category as string
        const operationKey = `${category}Operation`
        const operation = params[operationKey] || 'list'

        const toolParams: Record<string, unknown> = {
          apiKey: params.apiKey,
          operation,
        }

        // Map category-specific params
        if (category === 'customers') {
          toolParams.customerId = params.customerId
          toolParams.email = params.customerEmail
          toolParams.name = params.customerName
        } else if (category === 'refunds') {
          toolParams.amount = params.refundAmount
        } else if (category === 'payments') {
          toolParams.amount = params.paymentAmount
        }

        return toolParams
      },
    },
  },
}

export const StripeBlockMeta: BlockMeta = {
  id: 'stripe',
  name: 'Stripe',
  description: 'Connect Stripe: payments, customers, subscriptions, invoices, billing, and more.',
  category: 'tools',
  tags: ['payment-processor', 'billing', 'subscriptions', 'refunds'],
  authMode: 'credentials',
  docsLink: 'https://stripe.com/docs/api',
  brandColor: '#635BFF',
}
