import type { ToolOutputProperty } from '@/tools/types'

const string = (description: string, optional = true): ToolOutputProperty => ({
  type: 'string',
  description,
  optional,
})
const number = (description: string, optional = true): ToolOutputProperty => ({
  type: 'number',
  description,
  optional,
})
const boolean = (description: string, optional = true): ToolOutputProperty => ({
  type: 'boolean',
  description,
  optional,
})
const json = (description: string, optional = true): ToolOutputProperty => ({
  type: 'json',
  description,
  optional,
})
const array = (description: string, optional = true): ToolOutputProperty => ({
  type: 'array',
  description,
  optional,
  items: { type: 'json' },
})

export const SAILPOINT_IDENTITY_OUTPUT_PROPERTIES = {
  id: string('Identity ID'),
  name: string('Identity name'),
  created: string('Creation timestamp'),
  modified: string('Last modification timestamp'),
  alias: string('Identity alias'),
  emailAddress: string('Identity email address'),
  processingState: string('Identity processing state'),
  identityStatus: string('Identity status'),
  managerRef: json('Manager reference'),
  isManager: boolean('Whether the identity manages other identities'),
  lastRefresh: string('Last identity refresh timestamp'),
  attributes: json('Tenant-defined identity attributes'),
  lifecycleState: json('Lifecycle-state reference'),
} satisfies Record<string, ToolOutputProperty>

export const SAILPOINT_ACCOUNT_OUTPUT_PROPERTIES = {
  id: string('Account ID'),
  name: string('Account name'),
  created: string('Creation timestamp'),
  modified: string('Last modification timestamp'),
  sourceId: string('Source ID'),
  sourceName: string('Source name'),
  identityId: string('Correlated identity ID'),
  cloudLifecycleState: string('Cloud lifecycle state'),
  identityState: string('Identity state'),
  connectionType: string('Source connection type'),
  isMachine: boolean('Whether this is a machine account'),
  recommendation: json('Correlation recommendation'),
  attributes: json('Source-defined account attributes'),
  authoritative: boolean('Whether the account is authoritative'),
  description: string('Account description'),
  disabled: boolean('Whether the account is disabled'),
  locked: boolean('Whether the account is locked'),
  nativeIdentity: string('Native account identifier'),
  systemAccount: boolean('Whether this is a system account'),
  uncorrelated: boolean('Whether the account is uncorrelated'),
  uuid: string('Account UUID'),
  manuallyCorrelated: boolean('Whether the account was manually correlated'),
  hasEntitlements: boolean('Whether the account has entitlements'),
  identity: json('Correlated identity reference'),
  sourceOwner: json('Source owner reference'),
  features: array('Account features'),
  origin: string('Account origin'),
  ownerIdentity: json('Owner identity reference'),
} satisfies Record<string, ToolOutputProperty>

export const SAILPOINT_ACCOUNT_ACTIVITY_OUTPUT_PROPERTIES = {
  id: string('Account activity ID'),
  name: string('Account activity name'),
  created: string('Creation timestamp'),
  modified: string('Last modification timestamp'),
  completed: string('Completion timestamp'),
  completionStatus: string('Completion status'),
  type: string('Activity type'),
  requesterIdentitySummary: json('Requester identity summary'),
  targetIdentitySummary: json('Target identity summary'),
  errors: array('Provisioning errors'),
  warnings: array('Provisioning warnings'),
  items: array('Account activity items'),
  executionStatus: string('Execution status'),
  clientMetadata: json('Caller-provided string metadata'),
} satisfies Record<string, ToolOutputProperty>

export const SAILPOINT_SOURCE_OUTPUT_PROPERTIES = {
  id: string('Source ID'),
  name: string('Source name'),
  description: string('Source description'),
  owner: json('Source owner reference'),
  cluster: json('Virtual appliance cluster reference'),
  accountCorrelationConfig: json('Account correlation configuration'),
  accountCorrelationRule: json('Account correlation rule reference'),
  managerCorrelationMapping: json('Manager correlation mapping'),
  managerCorrelationRule: json('Manager correlation rule reference'),
  beforeProvisioningRule: json('Before-provisioning rule reference'),
  schemas: array('Source schemas'),
  passwordPolicies: array('Password policy references'),
  features: array('Source features'),
  type: string('Source type'),
  connector: string('Connector name'),
  connectorClass: string('Connector implementation class'),
  connectorAttributes: json('Connector-specific attributes'),
  deleteThreshold: number('Account deletion threshold'),
  authoritative: boolean('Whether the source is authoritative'),
  managementWorkgroup: json('Management workgroup reference'),
  healthy: boolean('Whether the source is healthy'),
  status: string('Source status'),
  since: string('Status start timestamp'),
  connectorId: string('Connector ID'),
  connectorName: string('Connector display name'),
  connectionType: string('Connection type'),
  connectorImplementationId: string('Connector implementation ID'),
  created: string('Creation timestamp'),
  modified: string('Last modification timestamp'),
  credentialProviderEnabled: boolean('Whether a credential provider is enabled'),
  category: string('Source category'),
} satisfies Record<string, ToolOutputProperty>

export const SAILPOINT_ENTITLEMENT_OUTPUT_PROPERTIES = {
  id: string('Entitlement ID'),
  name: string('Entitlement name'),
  attribute: string('Source entitlement attribute'),
  value: string('Source entitlement value'),
  sourceSchemaObjectType: string('Source schema object type'),
  description: string('Entitlement description'),
  privilegeLevel: json('Privilege-level details'),
  privileged: boolean('Legacy privileged flag'),
  tags: array('Entitlement tags'),
  cloudGoverned: boolean('Whether SailPoint governs the entitlement'),
  requestable: boolean('Whether the entitlement is requestable'),
  owner: json('Primary owner reference'),
  additionalOwners: array('Additional owner references'),
  manuallyUpdatedFields: json('Fields manually updated in SailPoint'),
  accessModelMetadata: json('Access-model metadata'),
  created: string('Creation timestamp'),
  modified: string('Last modification timestamp'),
  source: json('Source reference'),
  attributes: json('Source-defined entitlement attributes'),
  segments: array('Segment IDs'),
  directPermissions: array('Direct permissions'),
} satisfies Record<string, ToolOutputProperty>

export const SAILPOINT_IDENTITY_ENTITLEMENT_OUTPUT_PROPERTIES = {
  objectRef: json('Tagged entitlement reference'),
  tags: array('Tags applied to the entitlement'),
} satisfies Record<string, ToolOutputProperty>

export const SAILPOINT_ACCESS_PROFILE_OUTPUT_PROPERTIES = {
  id: string('Access profile ID'),
  name: string('Access profile name'),
  description: string('Access profile description'),
  created: string('Creation timestamp'),
  modified: string('Last modification timestamp'),
  enabled: boolean('Whether the access profile is enabled'),
  owner: json('Primary owner reference'),
  source: json('Source reference'),
  entitlements: array('Entitlement references'),
  requestable: boolean('Whether the access profile is requestable'),
  accessRequestConfig: json('Access-request configuration'),
  revocationRequestConfig: json('Revocation-request configuration'),
  segments: array('Segment IDs'),
  accessModelMetadata: json('Access-model metadata'),
  provisioningCriteria: json('Multi-account provisioning criteria'),
  additionalOwners: array('Additional owner references'),
} satisfies Record<string, ToolOutputProperty>

export const SAILPOINT_ROLE_OUTPUT_PROPERTIES = {
  id: string('Role ID'),
  name: string('Role name'),
  created: string('Creation timestamp'),
  modified: string('Last modification timestamp'),
  description: string('Role description'),
  owner: json('Primary owner reference'),
  additionalOwners: array('Additional owner references'),
  accessProfiles: array('Access profile references'),
  entitlements: array('Entitlement references'),
  membership: json('Role membership selector'),
  legacyMembershipInfo: json('Legacy membership information'),
  enabled: boolean('Whether the role is enabled'),
  requestable: boolean('Whether the role is requestable'),
  accessRequestConfig: json('Access-request configuration'),
  revocationRequestConfig: json('Revocation-request configuration'),
  segments: array('Segment IDs'),
  dimensional: boolean('Whether the role is dimensional'),
  dimensionRefs: array('Dimension references'),
  accessModelMetadata: json('Access-model metadata'),
  privilegeLevel: string('Role privilege level'),
} satisfies Record<string, ToolOutputProperty>

export const SAILPOINT_CAMPAIGN_OUTPUT_PROPERTIES = {
  id: string('Campaign ID'),
  name: string('Campaign name'),
  description: string('Campaign description'),
  deadline: string('Campaign deadline'),
  type: string('Campaign type'),
  status: string('Campaign status'),
  correlatedStatus: string('Campaign correlation status'),
  mandatoryCommentRequirement: string('Decision comment requirement'),
  created: string('Creation timestamp'),
  modified: string('Last modification timestamp'),
  recommendationsEnabled: boolean('Whether recommendations are enabled'),
  emailNotificationEnabled: boolean('Whether email notifications are enabled'),
  autoRevokeAllowed: boolean('Whether automatic revocation is allowed'),
  totalCertifications: number('Total certifications'),
  completedCertifications: number('Completed certifications'),
  alerts: array('Campaign alerts'),
  filter: json('Campaign filter reference'),
  sunsetCommentsRequired: boolean('Whether sunset-date changes require comments'),
  sourceOwnerCampaignInfo: json('Source-owner campaign configuration'),
  searchCampaignInfo: json('Search campaign configuration'),
  roleCompositionCampaignInfo: json('Role-composition campaign configuration'),
  machineAccountCampaignInfo: json('Machine-account campaign configuration'),
  sourcesWithOrphanEntitlements: array('Sources containing orphan entitlements'),
} satisfies Record<string, ToolOutputProperty>

export const SAILPOINT_CERTIFICATION_OUTPUT_PROPERTIES = {
  id: string('Certification ID'),
  name: string('Certification name'),
  campaign: json('Campaign reference'),
  completed: boolean('Whether all decisions are complete'),
  identitiesCompleted: number('Identities fully reviewed'),
  identitiesTotal: number('Total identities'),
  created: string('Creation timestamp'),
  modified: string('Last modification timestamp'),
  decisionsMade: number('Decisions made'),
  decisionsTotal: number('Total decisions'),
  due: string('Certification due timestamp'),
  signed: string('Sign-off timestamp'),
  reviewer: json('Reviewer reference'),
  reassignment: json('Reassignment details'),
  hasErrors: boolean('Whether the certification has errors'),
  errorMessage: string('Certification error message'),
  phase: string('Certification phase'),
} satisfies Record<string, ToolOutputProperty>

export const SAILPOINT_REVIEW_ITEM_OUTPUT_PROPERTIES = {
  accessSummary: json('Reviewed access summary'),
  identitySummary: json('Reviewed identity summary'),
  id: string('Review item ID'),
  completed: boolean('Whether review is complete'),
  newAccess: boolean('Whether this is newly granted access'),
  decision: string('Current certification decision'),
  comments: string('Reviewer comments'),
} satisfies Record<string, ToolOutputProperty>

export const SAILPOINT_ACCESS_REQUEST_STATUS_OUTPUT_PROPERTIES = {
  id: string('Requested item status ID'),
  name: string('Requested item name'),
  type: string('Requested item type'),
  cancelledRequestDetails: json('Cancellation details'),
  errorMessages: array('Localized request errors'),
  state: string('Request state'),
  approvalDetails: array('Approval details'),
  approvalIds: array('Approval IDs'),
  manualWorkItemDetails: array('Manual provisioning work items'),
  accountActivityItemId: string('Account activity item ID'),
  requestType: string('Access request type'),
  modified: string('Last modification timestamp'),
  created: string('Creation timestamp'),
  requester: json('Requester reference'),
  requestedFor: json('Requested-for identity reference'),
  identityType: string('HUMAN or MACHINE'),
  requesterComment: json('Requester comment'),
  sodViolationContext: json('Separation-of-duties violation context'),
  provisioningDetails: json('Provisioning details'),
  preApprovalTriggerDetails: json('Pre-approval trigger details'),
  accessRequestPhases: array('Request lifecycle phases'),
  description: string('Requested object description'),
  startDate: string('Requested start date'),
  removeDate: string('Requested removal date'),
  cancelable: boolean('Whether the request can be cancelled'),
  accessRequestId: string('Access request ID'),
  clientMetadata: json('Caller-provided string metadata'),
  requestedAccounts: array('Selected account references'),
  privilegeLevel: string('Requested object privilege level'),
  jitDetails: array('Just-in-time access details'),
  form: json('Completed request form'),
} satisfies Record<string, ToolOutputProperty>

export const SAILPOINT_PENDING_APPROVAL_OUTPUT_PROPERTIES = {
  id: string('Approval ID'),
  accessRequestId: string('Access request ID'),
  name: string('Approval name'),
  created: string('Creation timestamp'),
  modified: string('Last modification timestamp'),
  requestCreated: string('Access-request creation timestamp'),
  requestType: string('GRANT_ACCESS, REVOKE_ACCESS, or MODIFY_ACCESS'),
  identityType: string('HUMAN or MACHINE'),
  requester: json('Requester reference'),
  requestedFor: json('Requested-for identity reference'),
  owner: json('Access item owner'),
  requestedObject: json('Requested access object'),
  requesterComment: json('Requester comment'),
  previousReviewersComments: array('Previous reviewer comments'),
  forwardHistory: array('Approval forwarding history'),
  commentRequiredWhenRejected: boolean('Whether rejection requires a comment'),
  actionInProcess: string('Asynchronous action in progress'),
  removeDate: string('Requested removal date'),
  removeDateUpdateRequested: boolean('Whether this request changes the removal date'),
  currentRemoveDate: string('Removal date at request time'),
  startDate: string('Requested start date'),
  startUpdateRequested: boolean('Whether this request changes the start date'),
  currentStartDate: string('Start date at request time'),
  sodViolationContext: json('Separation-of-duties violation context'),
  clientMetadata: json('Caller-provided metadata'),
  requestedAccounts: array('Selected account references'),
  privilegeLevel: string('Requested object privilege level'),
  maxPermittedAccessDuration: json('Maximum allowed access duration'),
  jitDetails: array('Just-in-time access details'),
  form: json('Completed request form'),
} satisfies Record<string, ToolOutputProperty>

export const SAILPOINT_TASK_OUTPUT_PROPERTIES = {
  id: string('Task ID'),
  type: string('Task type'),
  uniqueName: string('Task unique name'),
  name: string('Task name'),
  description: string('Task description'),
  parentName: string('Parent task name'),
  launcher: string('Task launcher'),
  target: json('Task target'),
  created: string('Creation timestamp'),
  modified: string('Last modification timestamp'),
  launched: string('Launch timestamp'),
  completed: string('Completion timestamp'),
  completionStatus: string('Task completion status'),
  messages: array('Task messages'),
  returns: array('Task return descriptors'),
  attributes: json('Task-specific attributes'),
  progress: string('Human-readable progress'),
  percentComplete: number('Completion percentage'),
  taskDefinitionSummary: json('Task definition summary'),
} satisfies Record<string, ToolOutputProperty>

export const SAILPOINT_ACCESS_REQUEST_TRACKING_PROPERTIES = {
  requestedFor: string('Requested-for identity ID'),
  requestedItemsDetails: array('Requested item references'),
  attributesHash: number('Stable request attributes hash'),
  accessRequestIds: array('Access request tracking IDs'),
} satisfies Record<string, ToolOutputProperty>
