#!/usr/bin/env bun
/**
 * Generates the container image inventory for the Sim Helm chart.
 *
 * An operator mirroring Sim into a disconnected registry needs the complete set
 * of images an install pulls, and reading `values.yaml` by hand does not give it.
 * An image can be referenced from a template rather than named by an obvious
 * values key, and a hand-built list is then wrong in exactly the case that is
 * hardest to notice: the mirror succeeds, and one pod still pulls from the
 * internet at install time.
 *
 * The inventory is therefore derived from the rendered chart rather than from
 * values, and checked in so a chart change that adds an image has to update it.
 * Tags stay unresolved here: digests belong to a release, not to the chart, and
 * pinning them in a checked-in file would drift on every upstream rebuild. The
 * chart's `sim.image` helper already accepts a per-image `digest`, so an operator
 * pins at install time against the digests their own mirror resolved.
 *
 * Usage:
 *   bun run scripts/generate-image-manifest.ts
 *   bun run scripts/generate-image-manifest.ts --check
 */
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(SCRIPT_DIR, '..')
const CHART_DIR = resolve(ROOT, 'helm/sim')
const OUTPUT_PATH = resolve(CHART_DIR, 'images.yaml')
const CHECK_MODE = process.argv.includes('--check')

/**
 * Render arguments.
 *
 * `ci/full-values.yaml` is the chart's own "every optional component enabled"
 * profile, but it leaves `ollama.gpu.enabled` off, and the device plugin renders
 * only under that key. Enabling it here is what makes this an inventory of every
 * image the chart can pull rather than of one popular configuration.
 */
const RENDER_ARGS = [
  'template',
  'sim',
  CHART_DIR,
  '--namespace',
  'sim',
  '--values',
  resolve(CHART_DIR, 'ci/full-values.yaml'),
  '--set',
  'ollama.gpu.enabled=true',
] as const

/** Pod-spec keys whose entries carry an image reference. */
const CONTAINER_KEYS = new Set(['containers', 'initContainers', 'ephemeralContainers'])

/**
 * Collects every image reference in a set of rendered Kubernetes documents.
 *
 * Walks for container arrays by key rather than matching on workload kind, so a
 * chart that grows a Job, DaemonSet, or bare Pod is covered without changing
 * this: every workload nests its containers under the same three keys.
 */
export function collectImages(documents: readonly unknown[]): string[] {
  const images = new Set<string>()

  const visit = (node: unknown): void => {
    if (Array.isArray(node)) {
      for (const entry of node) visit(entry)
      return
    }
    if (node === null || typeof node !== 'object') return

    for (const [key, value] of Object.entries(node)) {
      if (CONTAINER_KEYS.has(key) && Array.isArray(value)) {
        for (const container of value) {
          if (container === null || typeof container !== 'object') continue
          const image = (container as { image?: unknown }).image
          if (typeof image === 'string' && image.length > 0) images.add(image)
        }
      }
      visit(value)
    }
  }

  visit(documents)
  return [...images].sort()
}

/** Renders the checked-in manifest. */
export function renderManifest(input: { appVersion: string; images: readonly string[] }): string {
  const entries = input.images.map((image) => `  - ${image}`).join('\n')

  return `# Generated by \`bun run images:generate\`. Do not edit this file directly.
#
# Every container image a complete Sim install pulls, rendered from this chart
# with all optional components enabled. Mirror all of them into a disconnected
# registry before installing.
#
# To redirect them, set \`global.imageRegistry\` to your registry AND
# \`global.useRegistryForAllImages: true\` — on its own, \`imageRegistry\` only
# rewrites the \`simstudioai/*\` images, leaving the third-party ones pointing at
# their public registries. Pin each image's \`digest\` to what your mirror
# resolved.
appVersion: ${input.appVersion}
images:
${entries}
`
}

/** Reads a scalar field from Chart.yaml without pulling in a YAML dependency for two keys. */
function readChartField(chart: string, field: string): string {
  const match = chart.match(new RegExp(`^${field}:\\s*"?([^"\\n]+)"?\\s*$`, 'm'))
  if (!match) throw new Error(`Chart.yaml is missing a \`${field}\` field`)
  return match[1].trim()
}

function renderChart(): unknown[] {
  let rendered: ReturnType<typeof Bun.spawnSync>
  try {
    rendered = Bun.spawnSync(['helm', ...RENDER_ARGS], { cwd: ROOT })
  } catch {
    throw new Error('Could not run `helm`. Install the Helm CLI to regenerate the image inventory.')
  }

  if (!rendered.success) {
    throw new Error(`helm template failed:\n${rendered.stderr.toString().trim()}`)
  }

  const documents = Bun.YAML.parse(rendered.stdout.toString())
  return Array.isArray(documents) ? documents : [documents]
}

async function main(): Promise<void> {
  const chart = await readFile(resolve(CHART_DIR, 'Chart.yaml'), 'utf8')
  const manifest = renderManifest({
    appVersion: readChartField(chart, 'appVersion'),
    images: collectImages(renderChart()),
  })

  if (!CHECK_MODE) {
    await writeFile(OUTPUT_PATH, manifest)
    console.log(`Wrote ${OUTPUT_PATH}`)
    return
  }

  const current = await readFile(OUTPUT_PATH, 'utf8').catch(() => '')
  if (current !== manifest) {
    const before = new Set(current.split('\n'))
    const after = new Set(manifest.split('\n'))
    for (const line of after) if (!before.has(line)) console.error(`+ ${line}`)
    for (const line of before) if (!after.has(line)) console.error(`- ${line}`)
    console.error(
      `\n${OUTPUT_PATH} is out of date. Run \`bun run images:generate\` and commit the result.`
    )
    process.exit(1)
  }
  console.log('Image inventory is up to date.')
}

if (import.meta.main) await main()
