/**
 * Pre-encodes the footer paintings so visitors never wait for image optimization.
 * Run `bun run scripts/generate-footer-artwork.ts` after changing either master.
 * Generated filenames include the encoded content hash for immutable caching.
 */
import { createHash } from 'node:crypto'
import { mkdir, readdir, unlink, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { createLogger } from '@sim/logger'
import sharp from 'sharp'

const logger = createLogger('FooterArtwork')
const ROOT = path.resolve(import.meta.dirname, '..')
const PUBLIC_DIR = path.join(ROOT, 'apps/sim/public/landing')
const OUTPUT_DIR = path.join(PUBLIC_DIR, 'footer-artwork')
const MANIFEST = path.join(
  ROOT,
  'apps/sim/app/(landing)/components/cta/footer-artwork.generated.ts'
)
const WIDTHS = [1200, 1920, 3840] as const
const THEMES = ['light', 'dark'] as const
/** Match the existing Next.js quality=90 WebP and AVIF encodes. */
const QUALITY = 90

interface FooterArtwork {
  avifSrcSet: string
  webpSrcSet: string
  src: string
  blurDataURL: string
}

sharp.concurrency(2)
await mkdir(OUTPUT_DIR, { recursive: true })
const generatedFiles = new Set<string>()
const artwork: Record<string, FooterArtwork> = {}

for (const theme of THEMES) {
  const master = path.join(PUBLIC_DIR, `cta-san-francisco-painted-${theme}.webp`)
  const sources: Record<'avif' | 'webp', string[]> = { avif: [], webp: [] }
  let fallback = ''
  for (const format of ['avif', 'webp'] as const) {
    for (const width of WIDTHS) {
      const image = sharp(master).rotate().resize(width, undefined, { withoutEnlargement: true })
      const buffer = await (format === 'avif'
        ? image.avif({ quality: Math.round(QUALITY * (50 / 80)), effort: 3 })
        : image.webp({ quality: QUALITY })
      ).toBuffer()
      const hash = createHash('sha256').update(buffer).digest('hex').slice(0, 12)
      const filename = `${theme}-${width}-${hash}.${format}`
      await writeFile(path.join(OUTPUT_DIR, filename), buffer)
      generatedFiles.add(filename)
      const url = `/landing/footer-artwork/${filename}`
      sources[format].push(`${url} ${width}w`)
      if (format === 'webp') fallback = url
      logger.info('Encoded footer artwork', { theme, width, format, bytes: buffer.length })
    }
  }
  const preview = await sharp(master).resize(8).webp({ quality: 70 }).toBuffer()
  artwork[theme] = {
    avifSrcSet: sources.avif.join(', '),
    webpSrcSet: sources.webp.join(', '),
    src: fallback,
    blurDataURL: `data:image/webp;base64,${preview.toString('base64')}`,
  }
}

await writeFile(
  MANIFEST,
  `/** Generated by scripts/generate-footer-artwork.ts. */\nexport const FOOTER_ARTWORK = ${JSON.stringify(artwork, null, 2)} as const\n`
)
const format = Bun.spawn(['bunx', 'biome', 'format', '--write', MANIFEST], { cwd: ROOT })
if ((await format.exited) !== 0) throw new Error('Could not format the footer artwork manifest')

for (const filename of await readdir(OUTPUT_DIR)) {
  if (
    /^(light|dark)-\d+-[a-f0-9]{12}\.(avif|webp)$/.test(filename) &&
    !generatedFiles.has(filename)
  ) {
    await unlink(path.join(OUTPUT_DIR, filename))
  }
}
