/**
 * @vitest-environment node
 */
import JSZip from 'jszip'
import { describe, expect, it } from 'vitest'
import {
  assertOoxmlArchiveWithinLimits,
  type OoxmlSizeLimits,
  ZipBombError,
} from '@/lib/file-parsers/zip-guard'

const HIGH_LIMITS: OoxmlSizeLimits = {
  maxTotalUncompressedBytes: 1024 * 1024 * 1024,
  maxCompressionRatio: 10_000,
  ratioCheckFloorBytes: 1024 * 1024 * 1024,
}

async function buildZip(
  entries: Record<string, string>,
  options: { comment?: string } = {}
): Promise<Buffer> {
  const zip = new JSZip()
  for (const [name, content] of Object.entries(entries)) {
    zip.file(name, content)
  }
  return zip.generateAsync({
    type: 'nodebuffer',
    compression: 'DEFLATE',
    comment: options.comment,
  })
}

const CENTRAL_DIRECTORY_HEADER_SIGNATURE = 0x02014b50
const LOCAL_FILE_HEADER_SIGNATURE = 0x04034b50

/**
 * Rewrite every declared uncompressed size — in both the central directory and
 * the local file headers — so the archive under-reports how much it expands to.
 * This is the bypass a declared-size-only check cannot see. Zero-length records
 * (JSZip emits a stored directory entry per folder) are left alone so the
 * archive stays well-formed apart from the lie under test.
 */
function underDeclareSizes(source: Buffer, declared: number): Buffer {
  const buffer = Buffer.from(source)
  for (let offset = 0; offset + 30 <= buffer.length; offset++) {
    const signature = buffer.readUInt32LE(offset)
    if (signature === CENTRAL_DIRECTORY_HEADER_SIGNATURE) {
      if (buffer.readUInt32LE(offset + 24) !== 0) {
        buffer.writeUInt32LE(declared, offset + 24)
      }
    } else if (signature === LOCAL_FILE_HEADER_SIGNATURE) {
      if (buffer.readUInt32LE(offset + 22) !== 0) {
        buffer.writeUInt32LE(declared, offset + 22)
      }
    }
  }
  return buffer
}

/** Overwrite the compression method on every non-empty central-directory record. */
function setCompressionMethod(source: Buffer, method: number): Buffer {
  const buffer = Buffer.from(source)
  for (let offset = 0; offset + 46 <= buffer.length; offset++) {
    if (
      buffer.readUInt32LE(offset) === CENTRAL_DIRECTORY_HEADER_SIGNATURE &&
      buffer.readUInt32LE(offset + 24) !== 0
    ) {
      buffer.writeUInt16LE(method, offset + 10)
    }
  }
  return buffer
}

describe('assertOoxmlArchiveWithinLimits', () => {
  it('accepts a well-formed archive within limits', async () => {
    const buffer = await buildZip({ 'word/document.xml': '<xml>hello world</xml>' })
    expect(() => assertOoxmlArchiveWithinLimits(buffer, HIGH_LIMITS)).not.toThrow()
  })

  it('rejects an archive whose declared expanded size exceeds the absolute cap', async () => {
    const buffer = await buildZip({ 'xl/worksheets/sheet1.xml': 'A'.repeat(200_000) })
    expect(() =>
      assertOoxmlArchiveWithinLimits(buffer, {
        maxTotalUncompressedBytes: 100_000,
        maxCompressionRatio: 10_000,
        ratioCheckFloorBytes: 1024 * 1024 * 1024,
      })
    ).toThrow(ZipBombError)
  })

  it('rejects an archive whose compression ratio exceeds the limit', async () => {
    const buffer = await buildZip({ 'xl/worksheets/sheet1.xml': 'A'.repeat(200_000) })
    expect(() =>
      assertOoxmlArchiveWithinLimits(buffer, {
        maxTotalUncompressedBytes: 1024 * 1024 * 1024,
        maxCompressionRatio: 5,
        ratioCheckFloorBytes: 1000,
      })
    ).toThrow(ZipBombError)
  })

  it('does not flag a small but highly compressible archive below the ratio floor', async () => {
    const buffer = await buildZip({ 'xl/worksheets/sheet1.xml': 'A'.repeat(200_000) })
    expect(() =>
      assertOoxmlArchiveWithinLimits(buffer, {
        maxTotalUncompressedBytes: 1024 * 1024 * 1024,
        maxCompressionRatio: 5,
        ratioCheckFloorBytes: 1024 * 1024 * 1024,
      })
    ).not.toThrow()
  })

  it('sums declared sizes across multiple entries', async () => {
    const buffer = await buildZip({
      'a.xml': 'A'.repeat(60_000),
      'b.xml': 'B'.repeat(60_000),
    })
    expect(() =>
      assertOoxmlArchiveWithinLimits(buffer, {
        maxTotalUncompressedBytes: 100_000,
        maxCompressionRatio: 10_000,
        ratioCheckFloorBytes: 1024 * 1024 * 1024,
      })
    ).toThrow(ZipBombError)
  })

  it('accepts a well-formed archive that carries a trailing comment', async () => {
    const buffer = await buildZip(
      { 'word/document.xml': '<xml>hello</xml>' },
      { comment: 'generated by test' }
    )
    expect(() => assertOoxmlArchiveWithinLimits(buffer, HIGH_LIMITS)).not.toThrow()
  })

  it('fails closed for a ZIP-shaped buffer whose central directory is unparseable', () => {
    const buffer = Buffer.alloc(64)
    buffer.writeUInt32LE(0x04034b50, 0) // local file header signature, no valid EOCD
    expect(() => assertOoxmlArchiveWithinLimits(buffer)).toThrow(ZipBombError)
  })

  it('rejects a decoy EOCD signature that does not validate against the buffer tail', async () => {
    const realZip = await buildZip({ 'xl/worksheets/sheet1.xml': 'A'.repeat(200_000) })
    // A decoy EOCD (zeroed central directory) appended after the genuine archive
    // would, without tail validation, redirect the guard to an empty directory
    // and undercount the real entries.
    const decoy = Buffer.alloc(64)
    decoy.writeUInt32LE(0x06054b50, 0)
    const tampered = Buffer.concat([realZip, decoy])
    expect(() => assertOoxmlArchiveWithinLimits(tampered)).toThrow(ZipBombError)
  })

  it('rejects an archive that under-declares its uncompressed size', async () => {
    // The declared sizes put this archive far under both limits, so only
    // inflating it reveals that it actually expands ~200x further.
    const honest = await buildZip({ 'word/document.xml': 'A'.repeat(200_000) })
    const lying = underDeclareSizes(honest, 1000)

    expect(() => assertOoxmlArchiveWithinLimits(lying, HIGH_LIMITS)).toThrow(ZipBombError)
    expect(() => assertOoxmlArchiveWithinLimits(lying, HIGH_LIMITS)).toThrow(
      /inflates beyond the 1000 bytes it declares/
    )
  })

  it('still accepts the same archive when its declared sizes are honest', async () => {
    const honest = await buildZip({ 'word/document.xml': 'A'.repeat(200_000) })
    expect(() => assertOoxmlArchiveWithinLimits(honest, HIGH_LIMITS)).not.toThrow()
  })

  it('rejects a stored entry whose declared size does not match its payload', async () => {
    const zip = new JSZip()
    zip.file('document.xml', 'A'.repeat(50_000))
    const stored = (await zip.generateAsync({
      type: 'nodebuffer',
      compression: 'STORE',
    })) as Buffer

    expect(() =>
      assertOoxmlArchiveWithinLimits(underDeclareSizes(stored, 10), HIGH_LIMITS)
    ).toThrow(/stored entry declares 10 bytes but holds 50000/)
  })

  it('rejects an entry using a compression method the parsers cannot read', async () => {
    const buffer = await buildZip({ 'word/document.xml': '<xml>hello</xml>' })
    expect(() =>
      assertOoxmlArchiveWithinLimits(setCompressionMethod(buffer, 12), HIGH_LIMITS)
    ).toThrow(/unsupported compression method 12/)
  })

  it('accepts a multi-entry archive whose entries all inflate to what they declare', async () => {
    const buffer = await buildZip({
      '[Content_Types].xml': '<?xml version="1.0"?><Types/>',
      '_rels/.rels': '<?xml version="1.0"?><Relationships/>',
      'word/document.xml': `<w:document>${'text '.repeat(5000)}</w:document>`,
      'word/styles.xml': `<w:styles>${'style '.repeat(2000)}</w:styles>`,
    })
    expect(() => assertOoxmlArchiveWithinLimits(buffer, HIGH_LIMITS)).not.toThrow()
  })

  it('no-ops for buffers that are not ZIP archives', () => {
    const plaintext = Buffer.from('this is just plain text, not a zip archive at all')
    expect(() => assertOoxmlArchiveWithinLimits(plaintext)).not.toThrow()
  })

  it('no-ops for buffers too small to contain an EOCD record', () => {
    expect(() => assertOoxmlArchiveWithinLimits(Buffer.from('PK'))).not.toThrow()
  })

  it('no-ops for an empty buffer', () => {
    expect(() => assertOoxmlArchiveWithinLimits(Buffer.alloc(0))).not.toThrow()
  })
})
