/**
 * Stripe Tools
 * Generated by Universal Integrator v8
 */

import { ToolConfig } from '@sim/workflow-types';

export const stripeCreateCustomerTool: ToolConfig = {
  id: 'stripe_create_customer',
  name: 'Create Customer',
  version: '1.0.0',
  params: {
    apiKey: { type: 'string', required: true, visibility: 'hidden' },
    email: { type: 'string', required: false, visibility: 'user-or-llm' },
    name: { type: 'string', required: false, visibility: 'user-or-llm' },
  },
  outputs: {
    id: { type: 'string' },
    email: { type: 'string', optional: true },
    name: { type: 'string', optional: true },
    created: { type: 'number' },
  },
  request: {
    url: () => 'https://api.stripe.com/v1/customers',
    method: () => 'POST',
    headers: (params) => ({
      'Authorization': `Bearer ${params.apiKey}`,
      'Content-Type': 'application/x-www-form-urlencoded',
    }),
    body: (params) => new URLSearchParams({
      email: params.email ?? '',
      name: params.name ?? '',
    }).toString(),
  },
  transformResponse: (response) => ({
    id: response.id,
    email: response.email ?? null,
    name: response.name ?? null,
    created: response.created,
  }),
};

export const stripeListCustomersTool: ToolConfig = {
  id: 'stripe_list_customers',
  name: 'List Customers',
  version: '1.0.0',
  params: {
    apiKey: { type: 'string', required: true, visibility: 'hidden' },
    limit: { type: 'number', required: false, visibility: 'user-or-llm' },
  },
  outputs: {
    data: { type: 'array' },
    has_more: { type: 'boolean' },
    total_count: { type: 'number', optional: true },
  },
  request: {
    url: (params) => `https://api.stripe.com/v1/customers?limit=${params.limit ?? 10}`,
    method: () => 'GET',
    headers: (params) => ({
      'Authorization': `Bearer ${params.apiKey}`,
    }),
  },
  transformResponse: (response) => ({
    data: response.data ?? [],
    has_more: response.has_more ?? false,
    total_count: response.total_count ?? null,
  }),
};

export const stripeCreateChargeTool: ToolConfig = {
  id: 'stripe_create_charge',
  name: 'Create Charge',
  version: '1.0.0',
  params: {
    apiKey: { type: 'string', required: true, visibility: 'hidden' },
    amount: { type: 'number', required: true, visibility: 'user-or-llm' },
    currency: { type: 'string', required: true, visibility: 'user-or-llm' },
    customer: { type: 'string', required: false, visibility: 'user-or-llm' },
  },
  outputs: {
    id: { type: 'string' },
    amount: { type: 'number' },
    status: { type: 'string' },
    customer: { type: 'string', optional: true },
  },
  request: {
    url: () => 'https://api.stripe.com/v1/charges',
    method: () => 'POST',
    headers: (params) => ({
      'Authorization': `Bearer ${params.apiKey}`,
      'Content-Type': 'application/x-www-form-urlencoded',
    }),
    body: (params) => new URLSearchParams({
      amount: String(params.amount),
      currency: params.currency,
      customer: params.customer ?? '',
    }).toString(),
  },
  transformResponse: (response) => ({
    id: response.id,
    amount: response.amount,
    status: response.status,
    customer: response.customer ?? null,
  }),
};
