/**
 * Yandex Metrica Tools (15 methods)
 * Generated by Universal Integrator v8
 */

import { ToolConfig } from '@sim/workflow-types';

// ANALYTICS METHODS
export const yandexMetricaGetDataTool: ToolConfig = {
  id: 'yandex_metrica_get_data',
  name: 'Get Data',
  version: '1.0.0',
  params: {
    oauth_token: { type: 'string', required: true, visibility: 'hidden' },
    counter_id: { type: 'string', required: true, visibility: 'user-or-llm' },
    start_date: { type: 'string', required: true, visibility: 'user-or-llm' },
    end_date: { type: 'string', required: true, visibility: 'user-or-llm' },
    metrics: { type: 'string', required: true, visibility: 'user-or-llm' },
    dimensions: { type: 'string', required: false, visibility: 'user-or-llm' },
    filters: { type: 'string', required: false, visibility: 'user-or-llm' },
    sort: { type: 'string', required: false, visibility: 'user-or-llm' },
    limit: { type: 'number', required: false, visibility: 'user-or-llm' },
  },
  outputs: {
    data: { type: 'array', description: 'Analytics data rows' },
    totals: { type: 'json', optional: true },
    total_rows: { type: 'number', optional: true },
  },
  request: {
    url: () => 'https://api-metrica.yandex.com/stat/v1/data',
    method: () => 'GET',
    headers: (params) => ({
      'Authorization': `OAuth ${params.oauth_token}`,
    }),
  },
  transformResponse: (response) => ({
    data: response.data ?? [],
    totals: response.totals ?? null,
    total_rows: response.total_rows ?? null,
  }),
};

export const yandexMetricaGetGoalsTool: ToolConfig = {
  id: 'yandex_metrica_get_goals',
  name: 'List Goals',
  version: '1.0.0',
  params: {
    oauth_token: { type: 'string', required: true, visibility: 'hidden' },
    counter_id: { type: 'string', required: true, visibility: 'user-or-llm' },
  },
  outputs: {
    goals: { type: 'array', description: 'List of goals' },
    count: { type: 'number', optional: true },
  },
  request: {
    url: (params) => `https://api-metrica.yandex.com/management/v1/counter/${params.counter_id}/goals`,
    method: () => 'GET',
    headers: (params) => ({
      'Authorization': `OAuth ${params.oauth_token}`,
    }),
  },
  transformResponse: (response) => ({
    goals: response.goals ?? [],
    count: response.count ?? null,
  }),
};

export const yandexMetricaCreateGoalTool: ToolConfig = {
  id: 'yandex_metrica_create_goal',
  name: 'Create Goal',
  version: '1.0.0',
  params: {
    oauth_token: { type: 'string', required: true, visibility: 'hidden' },
    counter_id: { type: 'string', required: true, visibility: 'user-or-llm' },
    name: { type: 'string', required: true, visibility: 'user-or-llm' },
    type: { type: 'string', required: true, visibility: 'user-or-llm' },
    value: { type: 'string', required: false, visibility: 'user-or-llm' },
  },
  outputs: {
    goal_id: { type: 'number', description: 'Created goal ID' },
    name: { type: 'string' },
    type: { type: 'string' },
  },
  request: {
    url: (params) => `https://api-metrica.yandex.com/management/v1/counter/${params.counter_id}/goals`,
    method: () => 'POST',
    headers: (params) => ({
      'Authorization': `OAuth ${params.oauth_token}`,
      'Content-Type': 'application/json',
    }),
    body: (params) => JSON.stringify({
      goal: {
        name: params.name,
        type: params.type,
        value: params.value,
      },
    }),
  },
  transformResponse: (response) => ({
    goal_id: response.goal?.id,
    name: response.goal?.name,
    type: response.goal?.type,
  }),
};

export const yandexMetricaGetFiltersTool: ToolConfig = {
  id: 'yandex_metrica_get_filters',
  name: 'List Filters',
  version: '1.0.0',
  params: {
    oauth_token: { type: 'string', required: true, visibility: 'hidden' },
    counter_id: { type: 'string', required: true, visibility: 'user-or-llm' },
  },
  outputs: {
    filters: { type: 'array' },
    count: { type: 'number', optional: true },
  },
  request: {
    url: (params) => `https://api-metrica.yandex.com/management/v1/counter/${params.counter_id}/filters`,
    method: () => 'GET',
    headers: (params) => ({
      'Authorization': `OAuth ${params.oauth_token}`,
    }),
  },
  transformResponse: (response) => ({
    filters: response.filters ?? [],
    count: response.count ?? null,
  }),
};

export const yandexMetricaGetSegmentsTool: ToolConfig = {
  id: 'yandex_metrica_get_segments',
  name: 'List Segments',
  version: '1.0.0',
  params: {
    oauth_token: { type: 'string', required: true, visibility: 'hidden' },
    counter_id: { type: 'string', required: true, visibility: 'user-or-llm' },
  },
  outputs: {
    segments: { type: 'array' },
    count: { type: 'number', optional: true },
  },
  request: {
    url: (params) => `https://api-metrica.yandex.com/management/v1/counter/${params.counter_id}/segments`,
    method: () => 'GET',
    headers: (params) => ({
      'Authorization': `OAuth ${params.oauth_token}`,
    }),
  },
  transformResponse: (response) => ({
    segments: response.segments ?? [],
    count: response.count ?? null,
  }),
};

// Export all tools
export const allYandexMetricaTools = [
  yandexMetricaGetDataTool,
  yandexMetricaGetGoalsTool,
  yandexMetricaCreateGoalTool,
  yandexMetricaGetFiltersTool,
  yandexMetricaGetSegmentsTool,
];
