/** Locked template / SDK versions stamped on revisions and releases. */
export const APP_TEMPLATE_VERSION = '1.0.0'
export const APP_SDK_VERSION = '0.1.0'
export const APP_LOCKFILE_HASH_PLACEHOLDER = 'curated-no-user-npm'

export const APP_TEMPLATE_FILES: Record<string, string> = {
  'package.json': JSON.stringify(
    {
      name: 'sim-app',
      private: true,
      type: 'module',
      dependencies: {
        react: '19.0.0',
        'react-dom': '19.0.0',
        '@sim/app-sdk': '0.1.0',
      },
      scripts: {
        build: 'vite build',
        preview: 'vite preview',
      },
    },
    null,
    2
  ),
  'index.html': `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sim App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./src/main.tsx"></script>
  </body>
</html>
`,
  'src/main.tsx': `import { createRoot } from 'react-dom/client'
import { App } from './App'
import './styles.css'

createRoot(document.getElementById('root')!).render(<App />)
`,
  'src/App.tsx': `import { useState } from 'react'
import { main } from './sim.generated'

export function App() {
  const [result, setResult] = useState<string>('')
  const [busy, setBusy] = useState(false)

  async function onRun() {
    setBusy(true)
    try {
      const outputs = await main({})
      setResult(JSON.stringify(outputs, null, 2))
    } catch (e) {
      setResult(e instanceof Error ? e.message : 'Error')
    } finally {
      setBusy(false)
    }
  }

  return (
    <main style={{ fontFamily: 'system-ui', padding: 24 }}>
      <h1>Sim App</h1>
      <button disabled={busy} onClick={onRun}>{busy ? 'Running…' : 'Run'}</button>
      <pre>{result}</pre>
    </main>
  )
}
`,
  'src/styles.css': `body { margin: 0; background: #0b0d10; color: #e8eaed; }
button { cursor: pointer; padding: 0.5rem 1rem; }
pre { white-space: pre-wrap; }
`,
  'src/sim.generated.ts': `/** Placeholder — overwritten by the trusted build worker from revision actions. */
export async function main(_input: Record<string, never>): Promise<Record<string, unknown>> {
  throw new Error('sim.generated.ts was not regenerated by the build worker')
}
`,
}
