name: Build GHCR Images (Build Only)

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # AMD64 builds on x86 runners
          - dockerfile: ./docker/app.Dockerfile
            image: ghcr.io/simstudioai/simstudio
            platform: linux/amd64
            arch: amd64
            runner: linux-x64-8-core
          - dockerfile: ./docker/db.Dockerfile
            image: ghcr.io/simstudioai/migrations
            platform: linux/amd64
            arch: amd64
            runner: linux-x64-8-core
          - dockerfile: ./docker/realtime.Dockerfile
            image: ghcr.io/simstudioai/realtime
            platform: linux/amd64
            arch: amd64
            runner: linux-x64-8-core
          # ARM64 builds on native ARM64 runners
          - dockerfile: ./docker/app.Dockerfile
            image: ghcr.io/simstudioai/simstudio
            platform: linux/arm64
            arch: arm64
            runner: linux-arm64-8-core
          - dockerfile: ./docker/db.Dockerfile
            image: ghcr.io/simstudioai/migrations
            platform: linux/arm64
            arch: arm64
            runner: linux-arm64-8-core
          - dockerfile: ./docker/realtime.Dockerfile
            image: ghcr.io/simstudioai/realtime
            platform: linux/arm64
            arch: arm64
            runner: linux-arm64-8-core
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value=latest-${{ matrix.arch }},enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=staging-${{ matrix.arch }},enable=${{ github.ref == 'refs/heads/staging' }}
            type=raw,value=staging-${{ github.sha }}-${{ matrix.arch }},enable=${{ github.ref == 'refs/heads/staging' }}
            type=sha,format=long,suffix=-${{ matrix.arch }}

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platform }}
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=build-v3
          cache-to: type=gha,mode=max,scope=build-v3
          provenance: false
          sbom: false 